// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_mobilenet_v1_Pipeline_BN_PW2_C_BN_PW2_H (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ifmap_dw3_address0,
        ifmap_dw3_ce0,
        ifmap_dw3_we0,
        ifmap_dw3_d0,
        ifmap_dw3_4_address0,
        ifmap_dw3_4_ce0,
        ifmap_dw3_4_we0,
        ifmap_dw3_4_d0,
        ifmap_dw3_8_address0,
        ifmap_dw3_8_ce0,
        ifmap_dw3_8_we0,
        ifmap_dw3_8_d0,
        ifmap_dw3_12_address0,
        ifmap_dw3_12_ce0,
        ifmap_dw3_12_we0,
        ifmap_dw3_12_d0,
        ifmap_dw3_1_address0,
        ifmap_dw3_1_ce0,
        ifmap_dw3_1_we0,
        ifmap_dw3_1_d0,
        ifmap_dw3_5_address0,
        ifmap_dw3_5_ce0,
        ifmap_dw3_5_we0,
        ifmap_dw3_5_d0,
        ifmap_dw3_9_address0,
        ifmap_dw3_9_ce0,
        ifmap_dw3_9_we0,
        ifmap_dw3_9_d0,
        ifmap_dw3_13_address0,
        ifmap_dw3_13_ce0,
        ifmap_dw3_13_we0,
        ifmap_dw3_13_d0,
        ifmap_dw3_2_address0,
        ifmap_dw3_2_ce0,
        ifmap_dw3_2_we0,
        ifmap_dw3_2_d0,
        ifmap_dw3_6_address0,
        ifmap_dw3_6_ce0,
        ifmap_dw3_6_we0,
        ifmap_dw3_6_d0,
        ifmap_dw3_10_address0,
        ifmap_dw3_10_ce0,
        ifmap_dw3_10_we0,
        ifmap_dw3_10_d0,
        ifmap_dw3_14_address0,
        ifmap_dw3_14_ce0,
        ifmap_dw3_14_we0,
        ifmap_dw3_14_d0,
        ifmap_dw3_3_address0,
        ifmap_dw3_3_ce0,
        ifmap_dw3_3_we0,
        ifmap_dw3_3_d0,
        ifmap_dw3_7_address0,
        ifmap_dw3_7_ce0,
        ifmap_dw3_7_we0,
        ifmap_dw3_7_d0,
        ifmap_dw3_11_address0,
        ifmap_dw3_11_ce0,
        ifmap_dw3_11_we0,
        ifmap_dw3_11_d0,
        ifmap_dw3_15_address0,
        ifmap_dw3_15_ce0,
        ifmap_dw3_15_we0,
        ifmap_dw3_15_d0,
        ofmap_pw2_address0,
        ofmap_pw2_ce0,
        ofmap_pw2_q0,
        ofmap_pw2_1_address0,
        ofmap_pw2_1_ce0,
        ofmap_pw2_1_q0,
        ofmap_pw2_2_address0,
        ofmap_pw2_2_ce0,
        ofmap_pw2_2_q0,
        ofmap_pw2_3_address0,
        ofmap_pw2_3_ce0,
        ofmap_pw2_3_q0,
        grp_fu_2467_p_din0,
        grp_fu_2467_p_din1,
        grp_fu_2467_p_opcode,
        grp_fu_2467_p_dout0,
        grp_fu_2467_p_ce,
        grp_fu_2471_p_din0,
        grp_fu_2471_p_din1,
        grp_fu_2471_p_opcode,
        grp_fu_2471_p_dout0,
        grp_fu_2471_p_ce,
        grp_fu_2475_p_din0,
        grp_fu_2475_p_din1,
        grp_fu_2475_p_opcode,
        grp_fu_2475_p_dout0,
        grp_fu_2475_p_ce,
        grp_fu_2479_p_din0,
        grp_fu_2479_p_din1,
        grp_fu_2479_p_opcode,
        grp_fu_2479_p_dout0,
        grp_fu_2479_p_ce,
        grp_fu_2523_p_din0,
        grp_fu_2523_p_din1,
        grp_fu_2523_p_dout0,
        grp_fu_2523_p_ce,
        grp_fu_2527_p_din0,
        grp_fu_2527_p_din1,
        grp_fu_2527_p_dout0,
        grp_fu_2527_p_ce,
        grp_fu_2531_p_din0,
        grp_fu_2531_p_din1,
        grp_fu_2531_p_dout0,
        grp_fu_2531_p_ce,
        grp_fu_2535_p_din0,
        grp_fu_2535_p_din1,
        grp_fu_2535_p_dout0,
        grp_fu_2535_p_ce,
        grp_fu_2599_p_din0,
        grp_fu_2599_p_din1,
        grp_fu_2599_p_opcode,
        grp_fu_2599_p_dout0,
        grp_fu_2599_p_ce,
        grp_fu_2603_p_din0,
        grp_fu_2603_p_din1,
        grp_fu_2603_p_opcode,
        grp_fu_2603_p_dout0,
        grp_fu_2603_p_ce,
        grp_fu_2607_p_din0,
        grp_fu_2607_p_din1,
        grp_fu_2607_p_opcode,
        grp_fu_2607_p_dout0,
        grp_fu_2607_p_ce,
        grp_fu_2611_p_din0,
        grp_fu_2611_p_din1,
        grp_fu_2611_p_opcode,
        grp_fu_2611_p_dout0,
        grp_fu_2611_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] ifmap_dw3_address0;
output   ifmap_dw3_ce0;
output   ifmap_dw3_we0;
output  [31:0] ifmap_dw3_d0;
output  [6:0] ifmap_dw3_4_address0;
output   ifmap_dw3_4_ce0;
output   ifmap_dw3_4_we0;
output  [31:0] ifmap_dw3_4_d0;
output  [6:0] ifmap_dw3_8_address0;
output   ifmap_dw3_8_ce0;
output   ifmap_dw3_8_we0;
output  [31:0] ifmap_dw3_8_d0;
output  [6:0] ifmap_dw3_12_address0;
output   ifmap_dw3_12_ce0;
output   ifmap_dw3_12_we0;
output  [31:0] ifmap_dw3_12_d0;
output  [6:0] ifmap_dw3_1_address0;
output   ifmap_dw3_1_ce0;
output   ifmap_dw3_1_we0;
output  [31:0] ifmap_dw3_1_d0;
output  [6:0] ifmap_dw3_5_address0;
output   ifmap_dw3_5_ce0;
output   ifmap_dw3_5_we0;
output  [31:0] ifmap_dw3_5_d0;
output  [6:0] ifmap_dw3_9_address0;
output   ifmap_dw3_9_ce0;
output   ifmap_dw3_9_we0;
output  [31:0] ifmap_dw3_9_d0;
output  [6:0] ifmap_dw3_13_address0;
output   ifmap_dw3_13_ce0;
output   ifmap_dw3_13_we0;
output  [31:0] ifmap_dw3_13_d0;
output  [6:0] ifmap_dw3_2_address0;
output   ifmap_dw3_2_ce0;
output   ifmap_dw3_2_we0;
output  [31:0] ifmap_dw3_2_d0;
output  [6:0] ifmap_dw3_6_address0;
output   ifmap_dw3_6_ce0;
output   ifmap_dw3_6_we0;
output  [31:0] ifmap_dw3_6_d0;
output  [6:0] ifmap_dw3_10_address0;
output   ifmap_dw3_10_ce0;
output   ifmap_dw3_10_we0;
output  [31:0] ifmap_dw3_10_d0;
output  [6:0] ifmap_dw3_14_address0;
output   ifmap_dw3_14_ce0;
output   ifmap_dw3_14_we0;
output  [31:0] ifmap_dw3_14_d0;
output  [6:0] ifmap_dw3_3_address0;
output   ifmap_dw3_3_ce0;
output   ifmap_dw3_3_we0;
output  [31:0] ifmap_dw3_3_d0;
output  [6:0] ifmap_dw3_7_address0;
output   ifmap_dw3_7_ce0;
output   ifmap_dw3_7_we0;
output  [31:0] ifmap_dw3_7_d0;
output  [6:0] ifmap_dw3_11_address0;
output   ifmap_dw3_11_ce0;
output   ifmap_dw3_11_we0;
output  [31:0] ifmap_dw3_11_d0;
output  [6:0] ifmap_dw3_15_address0;
output   ifmap_dw3_15_ce0;
output   ifmap_dw3_15_we0;
output  [31:0] ifmap_dw3_15_d0;
output  [8:0] ofmap_pw2_address0;
output   ofmap_pw2_ce0;
input  [31:0] ofmap_pw2_q0;
output  [8:0] ofmap_pw2_1_address0;
output   ofmap_pw2_1_ce0;
input  [31:0] ofmap_pw2_1_q0;
output  [8:0] ofmap_pw2_2_address0;
output   ofmap_pw2_2_ce0;
input  [31:0] ofmap_pw2_2_q0;
output  [8:0] ofmap_pw2_3_address0;
output   ofmap_pw2_3_ce0;
input  [31:0] ofmap_pw2_3_q0;
output  [31:0] grp_fu_2467_p_din0;
output  [31:0] grp_fu_2467_p_din1;
output  [1:0] grp_fu_2467_p_opcode;
input  [31:0] grp_fu_2467_p_dout0;
output   grp_fu_2467_p_ce;
output  [31:0] grp_fu_2471_p_din0;
output  [31:0] grp_fu_2471_p_din1;
output  [1:0] grp_fu_2471_p_opcode;
input  [31:0] grp_fu_2471_p_dout0;
output   grp_fu_2471_p_ce;
output  [31:0] grp_fu_2475_p_din0;
output  [31:0] grp_fu_2475_p_din1;
output  [1:0] grp_fu_2475_p_opcode;
input  [31:0] grp_fu_2475_p_dout0;
output   grp_fu_2475_p_ce;
output  [31:0] grp_fu_2479_p_din0;
output  [31:0] grp_fu_2479_p_din1;
output  [1:0] grp_fu_2479_p_opcode;
input  [31:0] grp_fu_2479_p_dout0;
output   grp_fu_2479_p_ce;
output  [31:0] grp_fu_2523_p_din0;
output  [31:0] grp_fu_2523_p_din1;
input  [31:0] grp_fu_2523_p_dout0;
output   grp_fu_2523_p_ce;
output  [31:0] grp_fu_2527_p_din0;
output  [31:0] grp_fu_2527_p_din1;
input  [31:0] grp_fu_2527_p_dout0;
output   grp_fu_2527_p_ce;
output  [31:0] grp_fu_2531_p_din0;
output  [31:0] grp_fu_2531_p_din1;
input  [31:0] grp_fu_2531_p_dout0;
output   grp_fu_2531_p_ce;
output  [31:0] grp_fu_2535_p_din0;
output  [31:0] grp_fu_2535_p_din1;
input  [31:0] grp_fu_2535_p_dout0;
output   grp_fu_2535_p_ce;
output  [31:0] grp_fu_2599_p_din0;
output  [31:0] grp_fu_2599_p_din1;
output  [4:0] grp_fu_2599_p_opcode;
input  [0:0] grp_fu_2599_p_dout0;
output   grp_fu_2599_p_ce;
output  [31:0] grp_fu_2603_p_din0;
output  [31:0] grp_fu_2603_p_din1;
output  [4:0] grp_fu_2603_p_opcode;
input  [0:0] grp_fu_2603_p_dout0;
output   grp_fu_2603_p_ce;
output  [31:0] grp_fu_2607_p_din0;
output  [31:0] grp_fu_2607_p_din1;
output  [4:0] grp_fu_2607_p_opcode;
input  [0:0] grp_fu_2607_p_dout0;
output   grp_fu_2607_p_ce;
output  [31:0] grp_fu_2611_p_din0;
output  [31:0] grp_fu_2611_p_din1;
output  [4:0] grp_fu_2611_p_opcode;
input  [0:0] grp_fu_2611_p_dout0;
output   grp_fu_2611_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln135_fu_1210_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln135_1_fu_1248_p3;
reg   [7:0] select_ln135_1_reg_2595;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter1_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter2_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter3_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter4_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter5_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter6_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter7_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter8_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter9_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter10_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter11_reg;
reg   [7:0] select_ln135_1_reg_2595_pp0_iter12_reg;
wire   [6:0] trunc_ln135_fu_1256_p1;
reg   [6:0] trunc_ln135_reg_2600;
reg   [6:0] trunc_ln135_reg_2600_pp0_iter1_reg;
reg   [6:0] trunc_ln135_reg_2600_pp0_iter2_reg;
reg   [6:0] trunc_ln135_reg_2600_pp0_iter3_reg;
reg   [6:0] trunc_ln135_reg_2600_pp0_iter4_reg;
wire   [1:0] trunc_ln136_fu_1286_p1;
reg   [1:0] trunc_ln136_reg_2626;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter1_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter2_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter3_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter4_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter5_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter6_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter7_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter8_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter9_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter10_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter11_reg;
reg   [1:0] trunc_ln136_reg_2626_pp0_iter12_reg;
wire   [31:0] tmp_99_fu_1321_p259;
reg   [31:0] tmp_99_reg_2630;
reg   [31:0] ofmap_pw2_load_reg_2638;
reg   [31:0] ofmap_pw2_1_load_reg_2643;
reg   [31:0] ofmap_pw2_2_load_reg_2648;
reg   [31:0] ofmap_pw2_3_load_reg_2653;
wire   [31:0] tmp_100_fu_1840_p259;
reg   [31:0] tmp_100_reg_2658;
reg   [31:0] mul_i4_reg_2666;
reg   [31:0] mul_1_i3_reg_2671;
reg   [31:0] mul_2_i3_reg_2676;
reg   [31:0] mul_3_i3_reg_2681;
reg   [31:0] x_assign_s_reg_2686;
reg   [31:0] x_assign_s_reg_2686_pp0_iter11_reg;
reg   [31:0] x_assign_2_reg_2693;
reg   [31:0] x_assign_2_reg_2693_pp0_iter11_reg;
reg   [31:0] x_assign_3_reg_2700;
reg   [31:0] x_assign_3_reg_2700_pp0_iter11_reg;
reg   [31:0] x_assign_4_reg_2707;
reg   [31:0] x_assign_4_reg_2707_pp0_iter11_reg;
wire   [31:0] select_ln4_fu_2400_p3;
reg   [31:0] select_ln4_reg_2714;
wire   [31:0] select_ln4_2_fu_2448_p3;
reg   [31:0] select_ln4_2_reg_2722;
wire   [31:0] select_ln4_3_fu_2496_p3;
reg   [31:0] select_ln4_3_reg_2730;
wire   [31:0] select_ln4_4_fu_2544_p3;
reg   [31:0] select_ln4_4_reg_2738;
wire   [63:0] zext_ln139_1_fu_1278_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln135_fu_2551_p1;
reg   [2:0] h_fu_868;
wire   [2:0] add_ln136_fu_1300_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_h_load;
reg   [7:0] c_fu_872;
reg   [7:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten60_fu_876;
wire   [9:0] add_ln135_1_fu_1216_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten60_load;
reg    ofmap_pw2_ce0_local;
reg    ofmap_pw2_1_ce0_local;
reg    ofmap_pw2_2_ce0_local;
reg    ofmap_pw2_3_ce0_local;
reg    ifmap_dw3_8_we0_local;
reg    ifmap_dw3_8_ce0_local;
reg    ifmap_dw3_9_we0_local;
reg    ifmap_dw3_9_ce0_local;
reg    ifmap_dw3_10_we0_local;
reg    ifmap_dw3_10_ce0_local;
reg    ifmap_dw3_11_we0_local;
reg    ifmap_dw3_11_ce0_local;
reg    ifmap_dw3_4_we0_local;
reg    ifmap_dw3_4_ce0_local;
reg    ifmap_dw3_5_we0_local;
reg    ifmap_dw3_5_ce0_local;
reg    ifmap_dw3_6_we0_local;
reg    ifmap_dw3_6_ce0_local;
reg    ifmap_dw3_7_we0_local;
reg    ifmap_dw3_7_ce0_local;
reg    ifmap_dw3_we0_local;
reg    ifmap_dw3_ce0_local;
reg    ifmap_dw3_1_we0_local;
reg    ifmap_dw3_1_ce0_local;
reg    ifmap_dw3_2_we0_local;
reg    ifmap_dw3_2_ce0_local;
reg    ifmap_dw3_3_we0_local;
reg    ifmap_dw3_3_ce0_local;
reg    ifmap_dw3_12_we0_local;
reg    ifmap_dw3_12_ce0_local;
reg    ifmap_dw3_13_we0_local;
reg    ifmap_dw3_13_ce0_local;
reg    ifmap_dw3_14_we0_local;
reg    ifmap_dw3_14_ce0_local;
reg    ifmap_dw3_15_we0_local;
reg    ifmap_dw3_15_ce0_local;
wire   [0:0] icmp_ln136_fu_1234_p2;
wire   [7:0] add_ln135_fu_1228_p2;
wire   [2:0] select_ln135_fu_1240_p3;
wire   [8:0] tmp_s_fu_1260_p3;
wire   [8:0] zext_ln139_fu_1268_p1;
wire   [8:0] add_ln139_fu_1272_p2;
wire   [31:0] tmp_99_fu_1321_p257;
wire   [31:0] tmp_100_fu_1840_p257;
wire   [31:0] bitcast_ln4_fu_2359_p1;
wire   [7:0] tmp_43_fu_2362_p4;
wire   [22:0] trunc_ln4_fu_2372_p1;
wire   [0:0] icmp_ln4_4_fu_2382_p2;
wire   [0:0] icmp_ln4_fu_2376_p2;
wire   [0:0] or_ln4_fu_2388_p2;
wire   [0:0] and_ln4_fu_2394_p2;
wire   [31:0] bitcast_ln4_2_fu_2407_p1;
wire   [7:0] tmp_45_fu_2410_p4;
wire   [22:0] trunc_ln4_2_fu_2420_p1;
wire   [0:0] icmp_ln4_6_fu_2430_p2;
wire   [0:0] icmp_ln4_5_fu_2424_p2;
wire   [0:0] or_ln4_2_fu_2436_p2;
wire   [0:0] and_ln4_2_fu_2442_p2;
wire   [31:0] bitcast_ln4_3_fu_2455_p1;
wire   [7:0] tmp_47_fu_2458_p4;
wire   [22:0] trunc_ln4_3_fu_2468_p1;
wire   [0:0] icmp_ln4_8_fu_2478_p2;
wire   [0:0] icmp_ln4_7_fu_2472_p2;
wire   [0:0] or_ln4_3_fu_2484_p2;
wire   [0:0] and_ln4_3_fu_2490_p2;
wire   [31:0] bitcast_ln4_4_fu_2503_p1;
wire   [7:0] tmp_49_fu_2506_p4;
wire   [22:0] trunc_ln4_4_fu_2516_p1;
wire   [0:0] icmp_ln4_10_fu_2526_p2;
wire   [0:0] icmp_ln4_9_fu_2520_p2;
wire   [0:0] or_ln4_4_fu_2532_p2;
wire   [0:0] and_ln4_4_fu_2538_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [6:0] tmp_99_fu_1321_p1;
wire   [6:0] tmp_99_fu_1321_p3;
wire   [6:0] tmp_99_fu_1321_p5;
wire   [6:0] tmp_99_fu_1321_p7;
wire   [6:0] tmp_99_fu_1321_p9;
wire   [6:0] tmp_99_fu_1321_p11;
wire   [6:0] tmp_99_fu_1321_p13;
wire   [6:0] tmp_99_fu_1321_p15;
wire   [6:0] tmp_99_fu_1321_p17;
wire   [6:0] tmp_99_fu_1321_p19;
wire   [6:0] tmp_99_fu_1321_p21;
wire   [6:0] tmp_99_fu_1321_p23;
wire   [6:0] tmp_99_fu_1321_p25;
wire   [6:0] tmp_99_fu_1321_p27;
wire   [6:0] tmp_99_fu_1321_p29;
wire   [6:0] tmp_99_fu_1321_p31;
wire   [6:0] tmp_99_fu_1321_p33;
wire   [6:0] tmp_99_fu_1321_p35;
wire   [6:0] tmp_99_fu_1321_p37;
wire   [6:0] tmp_99_fu_1321_p39;
wire   [6:0] tmp_99_fu_1321_p41;
wire   [6:0] tmp_99_fu_1321_p43;
wire   [6:0] tmp_99_fu_1321_p45;
wire   [6:0] tmp_99_fu_1321_p47;
wire   [6:0] tmp_99_fu_1321_p49;
wire   [6:0] tmp_99_fu_1321_p51;
wire   [6:0] tmp_99_fu_1321_p53;
wire   [6:0] tmp_99_fu_1321_p55;
wire   [6:0] tmp_99_fu_1321_p57;
wire   [6:0] tmp_99_fu_1321_p59;
wire   [6:0] tmp_99_fu_1321_p61;
wire   [6:0] tmp_99_fu_1321_p63;
wire   [6:0] tmp_99_fu_1321_p65;
wire   [6:0] tmp_99_fu_1321_p67;
wire   [6:0] tmp_99_fu_1321_p69;
wire   [6:0] tmp_99_fu_1321_p71;
wire   [6:0] tmp_99_fu_1321_p73;
wire   [6:0] tmp_99_fu_1321_p75;
wire   [6:0] tmp_99_fu_1321_p77;
wire   [6:0] tmp_99_fu_1321_p79;
wire   [6:0] tmp_99_fu_1321_p81;
wire   [6:0] tmp_99_fu_1321_p83;
wire   [6:0] tmp_99_fu_1321_p85;
wire   [6:0] tmp_99_fu_1321_p87;
wire   [6:0] tmp_99_fu_1321_p89;
wire   [6:0] tmp_99_fu_1321_p91;
wire   [6:0] tmp_99_fu_1321_p93;
wire   [6:0] tmp_99_fu_1321_p95;
wire   [6:0] tmp_99_fu_1321_p97;
wire   [6:0] tmp_99_fu_1321_p99;
wire   [6:0] tmp_99_fu_1321_p101;
wire   [6:0] tmp_99_fu_1321_p103;
wire   [6:0] tmp_99_fu_1321_p105;
wire   [6:0] tmp_99_fu_1321_p107;
wire   [6:0] tmp_99_fu_1321_p109;
wire   [6:0] tmp_99_fu_1321_p111;
wire   [6:0] tmp_99_fu_1321_p113;
wire   [6:0] tmp_99_fu_1321_p115;
wire   [6:0] tmp_99_fu_1321_p117;
wire   [6:0] tmp_99_fu_1321_p119;
wire   [6:0] tmp_99_fu_1321_p121;
wire   [6:0] tmp_99_fu_1321_p123;
wire   [6:0] tmp_99_fu_1321_p125;
wire   [6:0] tmp_99_fu_1321_p127;
wire  signed [6:0] tmp_99_fu_1321_p129;
wire  signed [6:0] tmp_99_fu_1321_p131;
wire  signed [6:0] tmp_99_fu_1321_p133;
wire  signed [6:0] tmp_99_fu_1321_p135;
wire  signed [6:0] tmp_99_fu_1321_p137;
wire  signed [6:0] tmp_99_fu_1321_p139;
wire  signed [6:0] tmp_99_fu_1321_p141;
wire  signed [6:0] tmp_99_fu_1321_p143;
wire  signed [6:0] tmp_99_fu_1321_p145;
wire  signed [6:0] tmp_99_fu_1321_p147;
wire  signed [6:0] tmp_99_fu_1321_p149;
wire  signed [6:0] tmp_99_fu_1321_p151;
wire  signed [6:0] tmp_99_fu_1321_p153;
wire  signed [6:0] tmp_99_fu_1321_p155;
wire  signed [6:0] tmp_99_fu_1321_p157;
wire  signed [6:0] tmp_99_fu_1321_p159;
wire  signed [6:0] tmp_99_fu_1321_p161;
wire  signed [6:0] tmp_99_fu_1321_p163;
wire  signed [6:0] tmp_99_fu_1321_p165;
wire  signed [6:0] tmp_99_fu_1321_p167;
wire  signed [6:0] tmp_99_fu_1321_p169;
wire  signed [6:0] tmp_99_fu_1321_p171;
wire  signed [6:0] tmp_99_fu_1321_p173;
wire  signed [6:0] tmp_99_fu_1321_p175;
wire  signed [6:0] tmp_99_fu_1321_p177;
wire  signed [6:0] tmp_99_fu_1321_p179;
wire  signed [6:0] tmp_99_fu_1321_p181;
wire  signed [6:0] tmp_99_fu_1321_p183;
wire  signed [6:0] tmp_99_fu_1321_p185;
wire  signed [6:0] tmp_99_fu_1321_p187;
wire  signed [6:0] tmp_99_fu_1321_p189;
wire  signed [6:0] tmp_99_fu_1321_p191;
wire  signed [6:0] tmp_99_fu_1321_p193;
wire  signed [6:0] tmp_99_fu_1321_p195;
wire  signed [6:0] tmp_99_fu_1321_p197;
wire  signed [6:0] tmp_99_fu_1321_p199;
wire  signed [6:0] tmp_99_fu_1321_p201;
wire  signed [6:0] tmp_99_fu_1321_p203;
wire  signed [6:0] tmp_99_fu_1321_p205;
wire  signed [6:0] tmp_99_fu_1321_p207;
wire  signed [6:0] tmp_99_fu_1321_p209;
wire  signed [6:0] tmp_99_fu_1321_p211;
wire  signed [6:0] tmp_99_fu_1321_p213;
wire  signed [6:0] tmp_99_fu_1321_p215;
wire  signed [6:0] tmp_99_fu_1321_p217;
wire  signed [6:0] tmp_99_fu_1321_p219;
wire  signed [6:0] tmp_99_fu_1321_p221;
wire  signed [6:0] tmp_99_fu_1321_p223;
wire  signed [6:0] tmp_99_fu_1321_p225;
wire  signed [6:0] tmp_99_fu_1321_p227;
wire  signed [6:0] tmp_99_fu_1321_p229;
wire  signed [6:0] tmp_99_fu_1321_p231;
wire  signed [6:0] tmp_99_fu_1321_p233;
wire  signed [6:0] tmp_99_fu_1321_p235;
wire  signed [6:0] tmp_99_fu_1321_p237;
wire  signed [6:0] tmp_99_fu_1321_p239;
wire  signed [6:0] tmp_99_fu_1321_p241;
wire  signed [6:0] tmp_99_fu_1321_p243;
wire  signed [6:0] tmp_99_fu_1321_p245;
wire  signed [6:0] tmp_99_fu_1321_p247;
wire  signed [6:0] tmp_99_fu_1321_p249;
wire  signed [6:0] tmp_99_fu_1321_p251;
wire  signed [6:0] tmp_99_fu_1321_p253;
wire  signed [6:0] tmp_99_fu_1321_p255;
wire   [6:0] tmp_100_fu_1840_p1;
wire   [6:0] tmp_100_fu_1840_p3;
wire   [6:0] tmp_100_fu_1840_p5;
wire   [6:0] tmp_100_fu_1840_p7;
wire   [6:0] tmp_100_fu_1840_p9;
wire   [6:0] tmp_100_fu_1840_p11;
wire   [6:0] tmp_100_fu_1840_p13;
wire   [6:0] tmp_100_fu_1840_p15;
wire   [6:0] tmp_100_fu_1840_p17;
wire   [6:0] tmp_100_fu_1840_p19;
wire   [6:0] tmp_100_fu_1840_p21;
wire   [6:0] tmp_100_fu_1840_p23;
wire   [6:0] tmp_100_fu_1840_p25;
wire   [6:0] tmp_100_fu_1840_p27;
wire   [6:0] tmp_100_fu_1840_p29;
wire   [6:0] tmp_100_fu_1840_p31;
wire   [6:0] tmp_100_fu_1840_p33;
wire   [6:0] tmp_100_fu_1840_p35;
wire   [6:0] tmp_100_fu_1840_p37;
wire   [6:0] tmp_100_fu_1840_p39;
wire   [6:0] tmp_100_fu_1840_p41;
wire   [6:0] tmp_100_fu_1840_p43;
wire   [6:0] tmp_100_fu_1840_p45;
wire   [6:0] tmp_100_fu_1840_p47;
wire   [6:0] tmp_100_fu_1840_p49;
wire   [6:0] tmp_100_fu_1840_p51;
wire   [6:0] tmp_100_fu_1840_p53;
wire   [6:0] tmp_100_fu_1840_p55;
wire   [6:0] tmp_100_fu_1840_p57;
wire   [6:0] tmp_100_fu_1840_p59;
wire   [6:0] tmp_100_fu_1840_p61;
wire   [6:0] tmp_100_fu_1840_p63;
wire   [6:0] tmp_100_fu_1840_p65;
wire   [6:0] tmp_100_fu_1840_p67;
wire   [6:0] tmp_100_fu_1840_p69;
wire   [6:0] tmp_100_fu_1840_p71;
wire   [6:0] tmp_100_fu_1840_p73;
wire   [6:0] tmp_100_fu_1840_p75;
wire   [6:0] tmp_100_fu_1840_p77;
wire   [6:0] tmp_100_fu_1840_p79;
wire   [6:0] tmp_100_fu_1840_p81;
wire   [6:0] tmp_100_fu_1840_p83;
wire   [6:0] tmp_100_fu_1840_p85;
wire   [6:0] tmp_100_fu_1840_p87;
wire   [6:0] tmp_100_fu_1840_p89;
wire   [6:0] tmp_100_fu_1840_p91;
wire   [6:0] tmp_100_fu_1840_p93;
wire   [6:0] tmp_100_fu_1840_p95;
wire   [6:0] tmp_100_fu_1840_p97;
wire   [6:0] tmp_100_fu_1840_p99;
wire   [6:0] tmp_100_fu_1840_p101;
wire   [6:0] tmp_100_fu_1840_p103;
wire   [6:0] tmp_100_fu_1840_p105;
wire   [6:0] tmp_100_fu_1840_p107;
wire   [6:0] tmp_100_fu_1840_p109;
wire   [6:0] tmp_100_fu_1840_p111;
wire   [6:0] tmp_100_fu_1840_p113;
wire   [6:0] tmp_100_fu_1840_p115;
wire   [6:0] tmp_100_fu_1840_p117;
wire   [6:0] tmp_100_fu_1840_p119;
wire   [6:0] tmp_100_fu_1840_p121;
wire   [6:0] tmp_100_fu_1840_p123;
wire   [6:0] tmp_100_fu_1840_p125;
wire   [6:0] tmp_100_fu_1840_p127;
wire  signed [6:0] tmp_100_fu_1840_p129;
wire  signed [6:0] tmp_100_fu_1840_p131;
wire  signed [6:0] tmp_100_fu_1840_p133;
wire  signed [6:0] tmp_100_fu_1840_p135;
wire  signed [6:0] tmp_100_fu_1840_p137;
wire  signed [6:0] tmp_100_fu_1840_p139;
wire  signed [6:0] tmp_100_fu_1840_p141;
wire  signed [6:0] tmp_100_fu_1840_p143;
wire  signed [6:0] tmp_100_fu_1840_p145;
wire  signed [6:0] tmp_100_fu_1840_p147;
wire  signed [6:0] tmp_100_fu_1840_p149;
wire  signed [6:0] tmp_100_fu_1840_p151;
wire  signed [6:0] tmp_100_fu_1840_p153;
wire  signed [6:0] tmp_100_fu_1840_p155;
wire  signed [6:0] tmp_100_fu_1840_p157;
wire  signed [6:0] tmp_100_fu_1840_p159;
wire  signed [6:0] tmp_100_fu_1840_p161;
wire  signed [6:0] tmp_100_fu_1840_p163;
wire  signed [6:0] tmp_100_fu_1840_p165;
wire  signed [6:0] tmp_100_fu_1840_p167;
wire  signed [6:0] tmp_100_fu_1840_p169;
wire  signed [6:0] tmp_100_fu_1840_p171;
wire  signed [6:0] tmp_100_fu_1840_p173;
wire  signed [6:0] tmp_100_fu_1840_p175;
wire  signed [6:0] tmp_100_fu_1840_p177;
wire  signed [6:0] tmp_100_fu_1840_p179;
wire  signed [6:0] tmp_100_fu_1840_p181;
wire  signed [6:0] tmp_100_fu_1840_p183;
wire  signed [6:0] tmp_100_fu_1840_p185;
wire  signed [6:0] tmp_100_fu_1840_p187;
wire  signed [6:0] tmp_100_fu_1840_p189;
wire  signed [6:0] tmp_100_fu_1840_p191;
wire  signed [6:0] tmp_100_fu_1840_p193;
wire  signed [6:0] tmp_100_fu_1840_p195;
wire  signed [6:0] tmp_100_fu_1840_p197;
wire  signed [6:0] tmp_100_fu_1840_p199;
wire  signed [6:0] tmp_100_fu_1840_p201;
wire  signed [6:0] tmp_100_fu_1840_p203;
wire  signed [6:0] tmp_100_fu_1840_p205;
wire  signed [6:0] tmp_100_fu_1840_p207;
wire  signed [6:0] tmp_100_fu_1840_p209;
wire  signed [6:0] tmp_100_fu_1840_p211;
wire  signed [6:0] tmp_100_fu_1840_p213;
wire  signed [6:0] tmp_100_fu_1840_p215;
wire  signed [6:0] tmp_100_fu_1840_p217;
wire  signed [6:0] tmp_100_fu_1840_p219;
wire  signed [6:0] tmp_100_fu_1840_p221;
wire  signed [6:0] tmp_100_fu_1840_p223;
wire  signed [6:0] tmp_100_fu_1840_p225;
wire  signed [6:0] tmp_100_fu_1840_p227;
wire  signed [6:0] tmp_100_fu_1840_p229;
wire  signed [6:0] tmp_100_fu_1840_p231;
wire  signed [6:0] tmp_100_fu_1840_p233;
wire  signed [6:0] tmp_100_fu_1840_p235;
wire  signed [6:0] tmp_100_fu_1840_p237;
wire  signed [6:0] tmp_100_fu_1840_p239;
wire  signed [6:0] tmp_100_fu_1840_p241;
wire  signed [6:0] tmp_100_fu_1840_p243;
wire  signed [6:0] tmp_100_fu_1840_p245;
wire  signed [6:0] tmp_100_fu_1840_p247;
wire  signed [6:0] tmp_100_fu_1840_p249;
wire  signed [6:0] tmp_100_fu_1840_p251;
wire  signed [6:0] tmp_100_fu_1840_p253;
wire  signed [6:0] tmp_100_fu_1840_p255;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 h_fu_868 = 3'd0;
#0 c_fu_872 = 8'd0;
#0 indvar_flatten60_fu_876 = 10'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mobilenet_v1_sparsemux_257_7_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 7'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 7'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 7'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 7'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 7'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 7'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 7'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 7'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 7'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 7'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 7'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 7'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 7'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 7'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 7'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 7'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 7'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 7'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 7'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 7'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 7'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 7'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 7'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 7'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 7'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 7'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 7'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 7'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 7'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 7'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 7'h1F ),
    .din31_WIDTH( 32 ),
    .CASE32( 7'h20 ),
    .din32_WIDTH( 32 ),
    .CASE33( 7'h21 ),
    .din33_WIDTH( 32 ),
    .CASE34( 7'h22 ),
    .din34_WIDTH( 32 ),
    .CASE35( 7'h23 ),
    .din35_WIDTH( 32 ),
    .CASE36( 7'h24 ),
    .din36_WIDTH( 32 ),
    .CASE37( 7'h25 ),
    .din37_WIDTH( 32 ),
    .CASE38( 7'h26 ),
    .din38_WIDTH( 32 ),
    .CASE39( 7'h27 ),
    .din39_WIDTH( 32 ),
    .CASE40( 7'h28 ),
    .din40_WIDTH( 32 ),
    .CASE41( 7'h29 ),
    .din41_WIDTH( 32 ),
    .CASE42( 7'h2A ),
    .din42_WIDTH( 32 ),
    .CASE43( 7'h2B ),
    .din43_WIDTH( 32 ),
    .CASE44( 7'h2C ),
    .din44_WIDTH( 32 ),
    .CASE45( 7'h2D ),
    .din45_WIDTH( 32 ),
    .CASE46( 7'h2E ),
    .din46_WIDTH( 32 ),
    .CASE47( 7'h2F ),
    .din47_WIDTH( 32 ),
    .CASE48( 7'h30 ),
    .din48_WIDTH( 32 ),
    .CASE49( 7'h31 ),
    .din49_WIDTH( 32 ),
    .CASE50( 7'h32 ),
    .din50_WIDTH( 32 ),
    .CASE51( 7'h33 ),
    .din51_WIDTH( 32 ),
    .CASE52( 7'h34 ),
    .din52_WIDTH( 32 ),
    .CASE53( 7'h35 ),
    .din53_WIDTH( 32 ),
    .CASE54( 7'h36 ),
    .din54_WIDTH( 32 ),
    .CASE55( 7'h37 ),
    .din55_WIDTH( 32 ),
    .CASE56( 7'h38 ),
    .din56_WIDTH( 32 ),
    .CASE57( 7'h39 ),
    .din57_WIDTH( 32 ),
    .CASE58( 7'h3A ),
    .din58_WIDTH( 32 ),
    .CASE59( 7'h3B ),
    .din59_WIDTH( 32 ),
    .CASE60( 7'h3C ),
    .din60_WIDTH( 32 ),
    .CASE61( 7'h3D ),
    .din61_WIDTH( 32 ),
    .CASE62( 7'h3E ),
    .din62_WIDTH( 32 ),
    .CASE63( 7'h3F ),
    .din63_WIDTH( 32 ),
    .CASE64( 7'h40 ),
    .din64_WIDTH( 32 ),
    .CASE65( 7'h41 ),
    .din65_WIDTH( 32 ),
    .CASE66( 7'h42 ),
    .din66_WIDTH( 32 ),
    .CASE67( 7'h43 ),
    .din67_WIDTH( 32 ),
    .CASE68( 7'h44 ),
    .din68_WIDTH( 32 ),
    .CASE69( 7'h45 ),
    .din69_WIDTH( 32 ),
    .CASE70( 7'h46 ),
    .din70_WIDTH( 32 ),
    .CASE71( 7'h47 ),
    .din71_WIDTH( 32 ),
    .CASE72( 7'h48 ),
    .din72_WIDTH( 32 ),
    .CASE73( 7'h49 ),
    .din73_WIDTH( 32 ),
    .CASE74( 7'h4A ),
    .din74_WIDTH( 32 ),
    .CASE75( 7'h4B ),
    .din75_WIDTH( 32 ),
    .CASE76( 7'h4C ),
    .din76_WIDTH( 32 ),
    .CASE77( 7'h4D ),
    .din77_WIDTH( 32 ),
    .CASE78( 7'h4E ),
    .din78_WIDTH( 32 ),
    .CASE79( 7'h4F ),
    .din79_WIDTH( 32 ),
    .CASE80( 7'h50 ),
    .din80_WIDTH( 32 ),
    .CASE81( 7'h51 ),
    .din81_WIDTH( 32 ),
    .CASE82( 7'h52 ),
    .din82_WIDTH( 32 ),
    .CASE83( 7'h53 ),
    .din83_WIDTH( 32 ),
    .CASE84( 7'h54 ),
    .din84_WIDTH( 32 ),
    .CASE85( 7'h55 ),
    .din85_WIDTH( 32 ),
    .CASE86( 7'h56 ),
    .din86_WIDTH( 32 ),
    .CASE87( 7'h57 ),
    .din87_WIDTH( 32 ),
    .CASE88( 7'h58 ),
    .din88_WIDTH( 32 ),
    .CASE89( 7'h59 ),
    .din89_WIDTH( 32 ),
    .CASE90( 7'h5A ),
    .din90_WIDTH( 32 ),
    .CASE91( 7'h5B ),
    .din91_WIDTH( 32 ),
    .CASE92( 7'h5C ),
    .din92_WIDTH( 32 ),
    .CASE93( 7'h5D ),
    .din93_WIDTH( 32 ),
    .CASE94( 7'h5E ),
    .din94_WIDTH( 32 ),
    .CASE95( 7'h5F ),
    .din95_WIDTH( 32 ),
    .CASE96( 7'h60 ),
    .din96_WIDTH( 32 ),
    .CASE97( 7'h61 ),
    .din97_WIDTH( 32 ),
    .CASE98( 7'h62 ),
    .din98_WIDTH( 32 ),
    .CASE99( 7'h63 ),
    .din99_WIDTH( 32 ),
    .CASE100( 7'h64 ),
    .din100_WIDTH( 32 ),
    .CASE101( 7'h65 ),
    .din101_WIDTH( 32 ),
    .CASE102( 7'h66 ),
    .din102_WIDTH( 32 ),
    .CASE103( 7'h67 ),
    .din103_WIDTH( 32 ),
    .CASE104( 7'h68 ),
    .din104_WIDTH( 32 ),
    .CASE105( 7'h69 ),
    .din105_WIDTH( 32 ),
    .CASE106( 7'h6A ),
    .din106_WIDTH( 32 ),
    .CASE107( 7'h6B ),
    .din107_WIDTH( 32 ),
    .CASE108( 7'h6C ),
    .din108_WIDTH( 32 ),
    .CASE109( 7'h6D ),
    .din109_WIDTH( 32 ),
    .CASE110( 7'h6E ),
    .din110_WIDTH( 32 ),
    .CASE111( 7'h6F ),
    .din111_WIDTH( 32 ),
    .CASE112( 7'h70 ),
    .din112_WIDTH( 32 ),
    .CASE113( 7'h71 ),
    .din113_WIDTH( 32 ),
    .CASE114( 7'h72 ),
    .din114_WIDTH( 32 ),
    .CASE115( 7'h73 ),
    .din115_WIDTH( 32 ),
    .CASE116( 7'h74 ),
    .din116_WIDTH( 32 ),
    .CASE117( 7'h75 ),
    .din117_WIDTH( 32 ),
    .CASE118( 7'h76 ),
    .din118_WIDTH( 32 ),
    .CASE119( 7'h77 ),
    .din119_WIDTH( 32 ),
    .CASE120( 7'h78 ),
    .din120_WIDTH( 32 ),
    .CASE121( 7'h79 ),
    .din121_WIDTH( 32 ),
    .CASE122( 7'h7A ),
    .din122_WIDTH( 32 ),
    .CASE123( 7'h7B ),
    .din123_WIDTH( 32 ),
    .CASE124( 7'h7C ),
    .din124_WIDTH( 32 ),
    .CASE125( 7'h7D ),
    .din125_WIDTH( 32 ),
    .CASE126( 7'h7E ),
    .din126_WIDTH( 32 ),
    .CASE127( 7'h7F ),
    .din127_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
sparsemux_257_7_32_1_1_U1124(
    .din0(32'd1061545973),
    .din1(32'd1052597739),
    .din2(32'd1052050136),
    .din3(32'd1060350856),
    .din4(32'd1041951149),
    .din5(32'd1058253141),
    .din6(32'd1053182601),
    .din7(32'd1060365912),
    .din8(32'd1050601792),
    .din9(32'd1056878634),
    .din10(32'd1054072856),
    .din11(32'd1061647833),
    .din12(32'd1057231000),
    .din13(32'd1061443648),
    .din14(32'd1052666908),
    .din15(32'd1056128928),
    .din16(32'd1046209329),
    .din17(32'd1057542927),
    .din18(32'd1051191993),
    .din19(32'd1054179315),
    .din20(32'd1058057939),
    .din21(32'd1058552134),
    .din22(32'd1055494390),
    .din23(32'd1049264413),
    .din24(32'd1058274912),
    .din25(32'd1052417613),
    .din26(32'd1060420998),
    .din27(32'd1055047448),
    .din28(32'd1060824118),
    .din29(32'd1052728525),
    .din30(32'd1049433735),
    .din31(32'd1051733752),
    .din32(32'd1061435475),
    .din33(32'd1059888858),
    .din34(32'd1050010488),
    .din35(32'd1057600287),
    .din36(32'd1052102803),
    .din37(32'd1051819550),
    .din38(32'd1057655068),
    .din39(32'd1054602688),
    .din40(32'd1053118079),
    .din41(32'd1060543337),
    .din42(32'd1050390108),
    .din43(32'd1053001118),
    .din44(32'd1062691500),
    .din45(32'd1049758518),
    .din46(32'd1052658486),
    .din47(32'd1059171191),
    .din48(32'd1065056480),
    .din49(32'd1049466544),
    .din50(32'd1064230748),
    .din51(32'd1051435178),
    .din52(32'd1059288553),
    .din53(32'd1053391388),
    .din54(32'd1051246027),
    .din55(32'd1048627906),
    .din56(32'd1056624318),
    .din57(32'd1048574450),
    .din58(32'd1058480115),
    .din59(32'd1047055988),
    .din60(32'd1063087966),
    .din61(32'd1051536337),
    .din62(32'd1049950984),
    .din63(32'd1051190429),
    .din64(32'd1051020372),
    .din65(32'd1051204234),
    .din66(32'd1050450841),
    .din67(32'd1061240049),
    .din68(32'd1048649927),
    .din69(32'd1050507978),
    .din70(32'd1049079663),
    .din71(32'd1055735947),
    .din72(32'd1054825263),
    .din73(32'd1053824745),
    .din74(32'd1058783243),
    .din75(32'd1056505289),
    .din76(32'd1057685231),
    .din77(32'd1065595682),
    .din78(32'd1057900345),
    .din79(32'd1057769645),
    .din80(32'd1063186726),
    .din81(32'd1052343622),
    .din82(32'd1040196917),
    .din83(32'd1055445033),
    .din84(32'd1056479148),
    .din85(32'd1052720442),
    .din86(32'd1051047408),
    .din87(32'd1046796664),
    .din88(32'd1055214358),
    .din89(32'd1049262330),
    .din90(32'd1053567899),
    .din91(32'd1054919196),
    .din92(32'd1062673102),
    .din93(32'd1054742283),
    .din94(32'd1054264085),
    .din95(32'd1062639179),
    .din96(32'd1057162651),
    .din97(32'd1054377213),
    .din98(32'd1051531785),
    .din99(32'd1060102213),
    .din100(32'd1057511799),
    .din101(32'd1053647493),
    .din102(32'd1049362161),
    .din103(32'd1057774953),
    .din104(32'd1046027240),
    .din105(32'd1052845943),
    .din106(32'd1047769401),
    .din107(32'd1063032772),
    .din108(32'd1056970379),
    .din109(32'd1052557165),
    .din110(32'd1065625246),
    .din111(32'd1054252655),
    .din112(32'd1058844081),
    .din113(32'd1054734005),
    .din114(32'd1054667721),
    .din115(32'd1053722493),
    .din116(32'd1061322791),
    .din117(32'd1058859216),
    .din118(32'd1049723962),
    .din119(32'd1054404914),
    .din120(32'd1050991562),
    .din121(32'd1053937849),
    .din122(32'd1049143277),
    .din123(32'd1052914505),
    .din124(32'd1049620006),
    .din125(32'd1056493190),
    .din126(32'd1062014464),
    .din127(32'd1057171337),
    .def(tmp_99_fu_1321_p257),
    .sel(trunc_ln135_reg_2600),
    .dout(tmp_99_fu_1321_p259)
);

(* dissolve_hierarchy = "yes" *) mobilenet_v1_sparsemux_257_7_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 7'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 7'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 7'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 7'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 7'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 7'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 7'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 7'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 7'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 7'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 7'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 7'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 7'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 7'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 7'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 7'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 7'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 7'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 7'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 7'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 7'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 7'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 7'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 7'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 7'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 7'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 7'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 7'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 7'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 7'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 7'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 7'h1F ),
    .din31_WIDTH( 32 ),
    .CASE32( 7'h20 ),
    .din32_WIDTH( 32 ),
    .CASE33( 7'h21 ),
    .din33_WIDTH( 32 ),
    .CASE34( 7'h22 ),
    .din34_WIDTH( 32 ),
    .CASE35( 7'h23 ),
    .din35_WIDTH( 32 ),
    .CASE36( 7'h24 ),
    .din36_WIDTH( 32 ),
    .CASE37( 7'h25 ),
    .din37_WIDTH( 32 ),
    .CASE38( 7'h26 ),
    .din38_WIDTH( 32 ),
    .CASE39( 7'h27 ),
    .din39_WIDTH( 32 ),
    .CASE40( 7'h28 ),
    .din40_WIDTH( 32 ),
    .CASE41( 7'h29 ),
    .din41_WIDTH( 32 ),
    .CASE42( 7'h2A ),
    .din42_WIDTH( 32 ),
    .CASE43( 7'h2B ),
    .din43_WIDTH( 32 ),
    .CASE44( 7'h2C ),
    .din44_WIDTH( 32 ),
    .CASE45( 7'h2D ),
    .din45_WIDTH( 32 ),
    .CASE46( 7'h2E ),
    .din46_WIDTH( 32 ),
    .CASE47( 7'h2F ),
    .din47_WIDTH( 32 ),
    .CASE48( 7'h30 ),
    .din48_WIDTH( 32 ),
    .CASE49( 7'h31 ),
    .din49_WIDTH( 32 ),
    .CASE50( 7'h32 ),
    .din50_WIDTH( 32 ),
    .CASE51( 7'h33 ),
    .din51_WIDTH( 32 ),
    .CASE52( 7'h34 ),
    .din52_WIDTH( 32 ),
    .CASE53( 7'h35 ),
    .din53_WIDTH( 32 ),
    .CASE54( 7'h36 ),
    .din54_WIDTH( 32 ),
    .CASE55( 7'h37 ),
    .din55_WIDTH( 32 ),
    .CASE56( 7'h38 ),
    .din56_WIDTH( 32 ),
    .CASE57( 7'h39 ),
    .din57_WIDTH( 32 ),
    .CASE58( 7'h3A ),
    .din58_WIDTH( 32 ),
    .CASE59( 7'h3B ),
    .din59_WIDTH( 32 ),
    .CASE60( 7'h3C ),
    .din60_WIDTH( 32 ),
    .CASE61( 7'h3D ),
    .din61_WIDTH( 32 ),
    .CASE62( 7'h3E ),
    .din62_WIDTH( 32 ),
    .CASE63( 7'h3F ),
    .din63_WIDTH( 32 ),
    .CASE64( 7'h40 ),
    .din64_WIDTH( 32 ),
    .CASE65( 7'h41 ),
    .din65_WIDTH( 32 ),
    .CASE66( 7'h42 ),
    .din66_WIDTH( 32 ),
    .CASE67( 7'h43 ),
    .din67_WIDTH( 32 ),
    .CASE68( 7'h44 ),
    .din68_WIDTH( 32 ),
    .CASE69( 7'h45 ),
    .din69_WIDTH( 32 ),
    .CASE70( 7'h46 ),
    .din70_WIDTH( 32 ),
    .CASE71( 7'h47 ),
    .din71_WIDTH( 32 ),
    .CASE72( 7'h48 ),
    .din72_WIDTH( 32 ),
    .CASE73( 7'h49 ),
    .din73_WIDTH( 32 ),
    .CASE74( 7'h4A ),
    .din74_WIDTH( 32 ),
    .CASE75( 7'h4B ),
    .din75_WIDTH( 32 ),
    .CASE76( 7'h4C ),
    .din76_WIDTH( 32 ),
    .CASE77( 7'h4D ),
    .din77_WIDTH( 32 ),
    .CASE78( 7'h4E ),
    .din78_WIDTH( 32 ),
    .CASE79( 7'h4F ),
    .din79_WIDTH( 32 ),
    .CASE80( 7'h50 ),
    .din80_WIDTH( 32 ),
    .CASE81( 7'h51 ),
    .din81_WIDTH( 32 ),
    .CASE82( 7'h52 ),
    .din82_WIDTH( 32 ),
    .CASE83( 7'h53 ),
    .din83_WIDTH( 32 ),
    .CASE84( 7'h54 ),
    .din84_WIDTH( 32 ),
    .CASE85( 7'h55 ),
    .din85_WIDTH( 32 ),
    .CASE86( 7'h56 ),
    .din86_WIDTH( 32 ),
    .CASE87( 7'h57 ),
    .din87_WIDTH( 32 ),
    .CASE88( 7'h58 ),
    .din88_WIDTH( 32 ),
    .CASE89( 7'h59 ),
    .din89_WIDTH( 32 ),
    .CASE90( 7'h5A ),
    .din90_WIDTH( 32 ),
    .CASE91( 7'h5B ),
    .din91_WIDTH( 32 ),
    .CASE92( 7'h5C ),
    .din92_WIDTH( 32 ),
    .CASE93( 7'h5D ),
    .din93_WIDTH( 32 ),
    .CASE94( 7'h5E ),
    .din94_WIDTH( 32 ),
    .CASE95( 7'h5F ),
    .din95_WIDTH( 32 ),
    .CASE96( 7'h60 ),
    .din96_WIDTH( 32 ),
    .CASE97( 7'h61 ),
    .din97_WIDTH( 32 ),
    .CASE98( 7'h62 ),
    .din98_WIDTH( 32 ),
    .CASE99( 7'h63 ),
    .din99_WIDTH( 32 ),
    .CASE100( 7'h64 ),
    .din100_WIDTH( 32 ),
    .CASE101( 7'h65 ),
    .din101_WIDTH( 32 ),
    .CASE102( 7'h66 ),
    .din102_WIDTH( 32 ),
    .CASE103( 7'h67 ),
    .din103_WIDTH( 32 ),
    .CASE104( 7'h68 ),
    .din104_WIDTH( 32 ),
    .CASE105( 7'h69 ),
    .din105_WIDTH( 32 ),
    .CASE106( 7'h6A ),
    .din106_WIDTH( 32 ),
    .CASE107( 7'h6B ),
    .din107_WIDTH( 32 ),
    .CASE108( 7'h6C ),
    .din108_WIDTH( 32 ),
    .CASE109( 7'h6D ),
    .din109_WIDTH( 32 ),
    .CASE110( 7'h6E ),
    .din110_WIDTH( 32 ),
    .CASE111( 7'h6F ),
    .din111_WIDTH( 32 ),
    .CASE112( 7'h70 ),
    .din112_WIDTH( 32 ),
    .CASE113( 7'h71 ),
    .din113_WIDTH( 32 ),
    .CASE114( 7'h72 ),
    .din114_WIDTH( 32 ),
    .CASE115( 7'h73 ),
    .din115_WIDTH( 32 ),
    .CASE116( 7'h74 ),
    .din116_WIDTH( 32 ),
    .CASE117( 7'h75 ),
    .din117_WIDTH( 32 ),
    .CASE118( 7'h76 ),
    .din118_WIDTH( 32 ),
    .CASE119( 7'h77 ),
    .din119_WIDTH( 32 ),
    .CASE120( 7'h78 ),
    .din120_WIDTH( 32 ),
    .CASE121( 7'h79 ),
    .din121_WIDTH( 32 ),
    .CASE122( 7'h7A ),
    .din122_WIDTH( 32 ),
    .CASE123( 7'h7B ),
    .din123_WIDTH( 32 ),
    .CASE124( 7'h7C ),
    .din124_WIDTH( 32 ),
    .CASE125( 7'h7D ),
    .din125_WIDTH( 32 ),
    .CASE126( 7'h7E ),
    .din126_WIDTH( 32 ),
    .CASE127( 7'h7F ),
    .din127_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
sparsemux_257_7_32_1_1_U1125(
    .din0(32'd3210795350),
    .din1(32'd1053307532),
    .din2(32'd1054748430),
    .din3(32'd1065894991),
    .din4(32'd1060384640),
    .din5(32'd1063413088),
    .din6(32'd1066824548),
    .din7(32'd1067123518),
    .din8(32'd1045351499),
    .din9(32'd1057725295),
    .din10(32'd3205191050),
    .din11(32'd1066330427),
    .din12(32'd1069887559),
    .din13(32'd3214767175),
    .din14(32'd3213815978),
    .din15(32'd1034136851),
    .din16(32'd3176479287),
    .din17(32'd1057507937),
    .din18(32'd1052636979),
    .din19(32'd1058164950),
    .din20(32'd3179213973),
    .din21(32'd1055879140),
    .din22(32'd1059021491),
    .din23(32'd1063674782),
    .din24(32'd1057774833),
    .din25(32'd1061672860),
    .din26(32'd1022574252),
    .din27(32'd3207857072),
    .din28(32'd3141871807),
    .din29(32'd1062192055),
    .din30(32'd1052682210),
    .din31(32'd1065489835),
    .din32(32'd1067308761),
    .din33(32'd1052227876),
    .din34(32'd1060299506),
    .din35(32'd3186822750),
    .din36(32'd1059841558),
    .din37(32'd3185684596),
    .din38(32'd1067669634),
    .din39(32'd3199911515),
    .din40(32'd1065955357),
    .din41(32'd1055406738),
    .din42(32'd1050049514),
    .din43(32'd1059455855),
    .din44(32'd1061149306),
    .din45(32'd1069301237),
    .din46(32'd1050713251),
    .din47(32'd1059838186),
    .din48(32'd1062724590),
    .din49(32'd1066499443),
    .din50(32'd3190341266),
    .din51(32'd1051445792),
    .din52(32'd3198415602),
    .din53(32'd1046015340),
    .din54(32'd1037019511),
    .din55(32'd1060704745),
    .din56(32'd3207609458),
    .din57(32'd1063385370),
    .din58(32'd3215817368),
    .din59(32'd1060284213),
    .din60(32'd1062936957),
    .din61(32'd1023726055),
    .din62(32'd1050571168),
    .din63(32'd1052362579),
    .din64(32'd1057753846),
    .din65(32'd1062198188),
    .din66(32'd1061696291),
    .din67(32'd1052005487),
    .din68(32'd1063448137),
    .din69(32'd3168233264),
    .din70(32'd3192768496),
    .din71(32'd3181974926),
    .din72(32'd1065377702),
    .din73(32'd1036524987),
    .din74(32'd1071532912),
    .din75(32'd1027501857),
    .din76(32'd1072111121),
    .din77(32'd1066699116),
    .din78(32'd1057414912),
    .din79(32'd1067355165),
    .din80(32'd1067531614),
    .din81(32'd3199274483),
    .din82(32'd1061898554),
    .din83(32'd1055103238),
    .din84(32'd3182627908),
    .din85(32'd3189895024),
    .din86(32'd1049859708),
    .din87(32'd1064166858),
    .din88(32'd1065867190),
    .din89(32'd1066992069),
    .din90(32'd3207106388),
    .din91(32'd1065901618),
    .din92(32'd1063437909),
    .din93(32'd1057978710),
    .din94(32'd1070768516),
    .din95(32'd3209566525),
    .din96(32'd3205303444),
    .din97(32'd1065597599),
    .din98(32'd1050579322),
    .din99(32'd1058044246),
    .din100(32'd3177474551),
    .din101(32'd3165585744),
    .din102(32'd1049074724),
    .din103(32'd1057464307),
    .din104(32'd1058318942),
    .din105(32'd1023171225),
    .din106(32'd1052213392),
    .din107(32'd3209689630),
    .din108(32'd1061581689),
    .din109(32'd1050349745),
    .din110(32'd1074147499),
    .din111(32'd1053438464),
    .din112(32'd1052534838),
    .din113(32'd1067574338),
    .din114(32'd1045917182),
    .din115(32'd3168357055),
    .din116(32'd3177767090),
    .din117(32'd1069276059),
    .din118(32'd1060169675),
    .din119(32'd1035042044),
    .din120(32'd1061020460),
    .din121(32'd1047979714),
    .din122(32'd1061458294),
    .din123(32'd1057061974),
    .din124(32'd1058220300),
    .din125(32'd1070586250),
    .din126(32'd3186003153),
    .din127(32'd3209135761),
    .def(tmp_100_fu_1840_p257),
    .sel(trunc_ln135_reg_2600_pp0_iter4_reg),
    .dout(tmp_100_fu_1840_p259)
);

mobilenet_v1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln135_fu_1210_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_872 <= select_ln135_1_fu_1248_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_872 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln135_fu_1210_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            h_fu_868 <= add_ln136_fu_1300_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            h_fu_868 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln135_fu_1210_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten60_fu_876 <= add_ln135_1_fu_1216_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten60_fu_876 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul_1_i3_reg_2671 <= grp_fu_2527_p_dout0;
        mul_2_i3_reg_2676 <= grp_fu_2531_p_dout0;
        mul_3_i3_reg_2681 <= grp_fu_2535_p_dout0;
        mul_i4_reg_2666 <= grp_fu_2523_p_dout0;
        select_ln135_1_reg_2595_pp0_iter10_reg <= select_ln135_1_reg_2595_pp0_iter9_reg;
        select_ln135_1_reg_2595_pp0_iter11_reg <= select_ln135_1_reg_2595_pp0_iter10_reg;
        select_ln135_1_reg_2595_pp0_iter12_reg <= select_ln135_1_reg_2595_pp0_iter11_reg;
        select_ln135_1_reg_2595_pp0_iter2_reg <= select_ln135_1_reg_2595_pp0_iter1_reg;
        select_ln135_1_reg_2595_pp0_iter3_reg <= select_ln135_1_reg_2595_pp0_iter2_reg;
        select_ln135_1_reg_2595_pp0_iter4_reg <= select_ln135_1_reg_2595_pp0_iter3_reg;
        select_ln135_1_reg_2595_pp0_iter5_reg <= select_ln135_1_reg_2595_pp0_iter4_reg;
        select_ln135_1_reg_2595_pp0_iter6_reg <= select_ln135_1_reg_2595_pp0_iter5_reg;
        select_ln135_1_reg_2595_pp0_iter7_reg <= select_ln135_1_reg_2595_pp0_iter6_reg;
        select_ln135_1_reg_2595_pp0_iter8_reg <= select_ln135_1_reg_2595_pp0_iter7_reg;
        select_ln135_1_reg_2595_pp0_iter9_reg <= select_ln135_1_reg_2595_pp0_iter8_reg;
        select_ln4_2_reg_2722 <= select_ln4_2_fu_2448_p3;
        select_ln4_3_reg_2730 <= select_ln4_3_fu_2496_p3;
        select_ln4_4_reg_2738 <= select_ln4_4_fu_2544_p3;
        select_ln4_reg_2714 <= select_ln4_fu_2400_p3;
        tmp_100_reg_2658 <= tmp_100_fu_1840_p259;
        trunc_ln135_reg_2600_pp0_iter2_reg <= trunc_ln135_reg_2600_pp0_iter1_reg;
        trunc_ln135_reg_2600_pp0_iter3_reg <= trunc_ln135_reg_2600_pp0_iter2_reg;
        trunc_ln135_reg_2600_pp0_iter4_reg <= trunc_ln135_reg_2600_pp0_iter3_reg;
        trunc_ln136_reg_2626_pp0_iter10_reg <= trunc_ln136_reg_2626_pp0_iter9_reg;
        trunc_ln136_reg_2626_pp0_iter11_reg <= trunc_ln136_reg_2626_pp0_iter10_reg;
        trunc_ln136_reg_2626_pp0_iter12_reg <= trunc_ln136_reg_2626_pp0_iter11_reg;
        trunc_ln136_reg_2626_pp0_iter2_reg <= trunc_ln136_reg_2626_pp0_iter1_reg;
        trunc_ln136_reg_2626_pp0_iter3_reg <= trunc_ln136_reg_2626_pp0_iter2_reg;
        trunc_ln136_reg_2626_pp0_iter4_reg <= trunc_ln136_reg_2626_pp0_iter3_reg;
        trunc_ln136_reg_2626_pp0_iter5_reg <= trunc_ln136_reg_2626_pp0_iter4_reg;
        trunc_ln136_reg_2626_pp0_iter6_reg <= trunc_ln136_reg_2626_pp0_iter5_reg;
        trunc_ln136_reg_2626_pp0_iter7_reg <= trunc_ln136_reg_2626_pp0_iter6_reg;
        trunc_ln136_reg_2626_pp0_iter8_reg <= trunc_ln136_reg_2626_pp0_iter7_reg;
        trunc_ln136_reg_2626_pp0_iter9_reg <= trunc_ln136_reg_2626_pp0_iter8_reg;
        x_assign_2_reg_2693 <= grp_fu_2471_p_dout0;
        x_assign_2_reg_2693_pp0_iter11_reg <= x_assign_2_reg_2693;
        x_assign_3_reg_2700 <= grp_fu_2475_p_dout0;
        x_assign_3_reg_2700_pp0_iter11_reg <= x_assign_3_reg_2700;
        x_assign_4_reg_2707 <= grp_fu_2479_p_dout0;
        x_assign_4_reg_2707_pp0_iter11_reg <= x_assign_4_reg_2707;
        x_assign_s_reg_2686 <= grp_fu_2467_p_dout0;
        x_assign_s_reg_2686_pp0_iter11_reg <= x_assign_s_reg_2686;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ofmap_pw2_1_load_reg_2643 <= ofmap_pw2_1_q0;
        ofmap_pw2_2_load_reg_2648 <= ofmap_pw2_2_q0;
        ofmap_pw2_3_load_reg_2653 <= ofmap_pw2_3_q0;
        ofmap_pw2_load_reg_2638 <= ofmap_pw2_q0;
        select_ln135_1_reg_2595 <= select_ln135_1_fu_1248_p3;
        select_ln135_1_reg_2595_pp0_iter1_reg <= select_ln135_1_reg_2595;
        tmp_99_reg_2630 <= tmp_99_fu_1321_p259;
        trunc_ln135_reg_2600 <= trunc_ln135_fu_1256_p1;
        trunc_ln135_reg_2600_pp0_iter1_reg <= trunc_ln135_reg_2600;
        trunc_ln136_reg_2626 <= trunc_ln136_fu_1286_p1;
        trunc_ln136_reg_2626_pp0_iter1_reg <= trunc_ln136_reg_2626;
    end
end

always @ (*) begin
    if (((icmp_ln135_fu_1210_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 8'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_872;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_h_load = 3'd0;
    end else begin
        ap_sig_allocacmp_h_load = h_fu_868;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten60_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten60_load = indvar_flatten60_fu_876;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_10_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd2))) begin
        ifmap_dw3_10_we0_local = 1'b1;
    end else begin
        ifmap_dw3_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_11_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd2))) begin
        ifmap_dw3_11_we0_local = 1'b1;
    end else begin
        ifmap_dw3_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_12_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd3))) begin
        ifmap_dw3_12_we0_local = 1'b1;
    end else begin
        ifmap_dw3_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_13_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd3))) begin
        ifmap_dw3_13_we0_local = 1'b1;
    end else begin
        ifmap_dw3_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_14_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd3))) begin
        ifmap_dw3_14_we0_local = 1'b1;
    end else begin
        ifmap_dw3_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_15_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd3))) begin
        ifmap_dw3_15_we0_local = 1'b1;
    end else begin
        ifmap_dw3_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_1_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd0))) begin
        ifmap_dw3_1_we0_local = 1'b1;
    end else begin
        ifmap_dw3_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_2_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd0))) begin
        ifmap_dw3_2_we0_local = 1'b1;
    end else begin
        ifmap_dw3_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_3_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd0))) begin
        ifmap_dw3_3_we0_local = 1'b1;
    end else begin
        ifmap_dw3_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_4_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd1))) begin
        ifmap_dw3_4_we0_local = 1'b1;
    end else begin
        ifmap_dw3_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_5_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd1))) begin
        ifmap_dw3_5_we0_local = 1'b1;
    end else begin
        ifmap_dw3_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_6_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd1))) begin
        ifmap_dw3_6_we0_local = 1'b1;
    end else begin
        ifmap_dw3_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_7_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd1))) begin
        ifmap_dw3_7_we0_local = 1'b1;
    end else begin
        ifmap_dw3_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_8_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd2))) begin
        ifmap_dw3_8_we0_local = 1'b1;
    end else begin
        ifmap_dw3_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_9_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd2))) begin
        ifmap_dw3_9_we0_local = 1'b1;
    end else begin
        ifmap_dw3_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ifmap_dw3_ce0_local = 1'b1;
    end else begin
        ifmap_dw3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln136_reg_2626_pp0_iter12_reg == 2'd0))) begin
        ifmap_dw3_we0_local = 1'b1;
    end else begin
        ifmap_dw3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofmap_pw2_1_ce0_local = 1'b1;
    end else begin
        ofmap_pw2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofmap_pw2_2_ce0_local = 1'b1;
    end else begin
        ofmap_pw2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofmap_pw2_3_ce0_local = 1'b1;
    end else begin
        ofmap_pw2_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ofmap_pw2_ce0_local = 1'b1;
    end else begin
        ofmap_pw2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln135_1_fu_1216_p2 = (ap_sig_allocacmp_indvar_flatten60_load + 10'd1);

assign add_ln135_fu_1228_p2 = (ap_sig_allocacmp_c_load + 8'd1);

assign add_ln136_fu_1300_p2 = (select_ln135_fu_1240_p3 + 3'd1);

assign add_ln139_fu_1272_p2 = (tmp_s_fu_1260_p3 + zext_ln139_fu_1268_p1);

assign and_ln4_2_fu_2442_p2 = (or_ln4_2_fu_2436_p2 & grp_fu_2603_p_dout0);

assign and_ln4_3_fu_2490_p2 = (or_ln4_3_fu_2484_p2 & grp_fu_2607_p_dout0);

assign and_ln4_4_fu_2538_p2 = (or_ln4_4_fu_2532_p2 & grp_fu_2611_p_dout0);

assign and_ln4_fu_2394_p2 = (or_ln4_fu_2388_p2 & grp_fu_2599_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln4_2_fu_2407_p1 = x_assign_2_reg_2693_pp0_iter11_reg;

assign bitcast_ln4_3_fu_2455_p1 = x_assign_3_reg_2700_pp0_iter11_reg;

assign bitcast_ln4_4_fu_2503_p1 = x_assign_4_reg_2707_pp0_iter11_reg;

assign bitcast_ln4_fu_2359_p1 = x_assign_s_reg_2686_pp0_iter11_reg;

assign grp_fu_2467_p_ce = 1'b1;

assign grp_fu_2467_p_din0 = mul_i4_reg_2666;

assign grp_fu_2467_p_din1 = tmp_100_reg_2658;

assign grp_fu_2467_p_opcode = 2'd0;

assign grp_fu_2471_p_ce = 1'b1;

assign grp_fu_2471_p_din0 = mul_1_i3_reg_2671;

assign grp_fu_2471_p_din1 = tmp_100_reg_2658;

assign grp_fu_2471_p_opcode = 2'd0;

assign grp_fu_2475_p_ce = 1'b1;

assign grp_fu_2475_p_din0 = mul_2_i3_reg_2676;

assign grp_fu_2475_p_din1 = tmp_100_reg_2658;

assign grp_fu_2475_p_opcode = 2'd0;

assign grp_fu_2479_p_ce = 1'b1;

assign grp_fu_2479_p_din0 = mul_3_i3_reg_2681;

assign grp_fu_2479_p_din1 = tmp_100_reg_2658;

assign grp_fu_2479_p_opcode = 2'd0;

assign grp_fu_2523_p_ce = 1'b1;

assign grp_fu_2523_p_din0 = ofmap_pw2_load_reg_2638;

assign grp_fu_2523_p_din1 = tmp_99_reg_2630;

assign grp_fu_2527_p_ce = 1'b1;

assign grp_fu_2527_p_din0 = ofmap_pw2_1_load_reg_2643;

assign grp_fu_2527_p_din1 = tmp_99_reg_2630;

assign grp_fu_2531_p_ce = 1'b1;

assign grp_fu_2531_p_din0 = ofmap_pw2_2_load_reg_2648;

assign grp_fu_2531_p_din1 = tmp_99_reg_2630;

assign grp_fu_2535_p_ce = 1'b1;

assign grp_fu_2535_p_din0 = ofmap_pw2_3_load_reg_2653;

assign grp_fu_2535_p_din1 = tmp_99_reg_2630;

assign grp_fu_2599_p_ce = 1'b1;

assign grp_fu_2599_p_din0 = x_assign_s_reg_2686;

assign grp_fu_2599_p_din1 = 32'd0;

assign grp_fu_2599_p_opcode = 5'd2;

assign grp_fu_2603_p_ce = 1'b1;

assign grp_fu_2603_p_din0 = x_assign_2_reg_2693;

assign grp_fu_2603_p_din1 = 32'd0;

assign grp_fu_2603_p_opcode = 5'd2;

assign grp_fu_2607_p_ce = 1'b1;

assign grp_fu_2607_p_din0 = x_assign_3_reg_2700;

assign grp_fu_2607_p_din1 = 32'd0;

assign grp_fu_2607_p_opcode = 5'd2;

assign grp_fu_2611_p_ce = 1'b1;

assign grp_fu_2611_p_din0 = x_assign_4_reg_2707;

assign grp_fu_2611_p_din1 = 32'd0;

assign grp_fu_2611_p_opcode = 5'd2;

assign icmp_ln135_fu_1210_p2 = ((ap_sig_allocacmp_indvar_flatten60_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_1234_p2 = ((ap_sig_allocacmp_h_load == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln4_10_fu_2526_p2 = ((trunc_ln4_4_fu_2516_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln4_4_fu_2382_p2 = ((trunc_ln4_fu_2372_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln4_5_fu_2424_p2 = ((tmp_45_fu_2410_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln4_6_fu_2430_p2 = ((trunc_ln4_2_fu_2420_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln4_7_fu_2472_p2 = ((tmp_47_fu_2458_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln4_8_fu_2478_p2 = ((trunc_ln4_3_fu_2468_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln4_9_fu_2520_p2 = ((tmp_49_fu_2506_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln4_fu_2376_p2 = ((tmp_43_fu_2362_p4 != 8'd255) ? 1'b1 : 1'b0);

assign ifmap_dw3_10_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_10_ce0 = ifmap_dw3_10_ce0_local;

assign ifmap_dw3_10_d0 = select_ln4_3_reg_2730;

assign ifmap_dw3_10_we0 = ifmap_dw3_10_we0_local;

assign ifmap_dw3_11_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_11_ce0 = ifmap_dw3_11_ce0_local;

assign ifmap_dw3_11_d0 = select_ln4_4_reg_2738;

assign ifmap_dw3_11_we0 = ifmap_dw3_11_we0_local;

assign ifmap_dw3_12_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_12_ce0 = ifmap_dw3_12_ce0_local;

assign ifmap_dw3_12_d0 = select_ln4_reg_2714;

assign ifmap_dw3_12_we0 = ifmap_dw3_12_we0_local;

assign ifmap_dw3_13_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_13_ce0 = ifmap_dw3_13_ce0_local;

assign ifmap_dw3_13_d0 = select_ln4_2_reg_2722;

assign ifmap_dw3_13_we0 = ifmap_dw3_13_we0_local;

assign ifmap_dw3_14_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_14_ce0 = ifmap_dw3_14_ce0_local;

assign ifmap_dw3_14_d0 = select_ln4_3_reg_2730;

assign ifmap_dw3_14_we0 = ifmap_dw3_14_we0_local;

assign ifmap_dw3_15_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_15_ce0 = ifmap_dw3_15_ce0_local;

assign ifmap_dw3_15_d0 = select_ln4_4_reg_2738;

assign ifmap_dw3_15_we0 = ifmap_dw3_15_we0_local;

assign ifmap_dw3_1_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_1_ce0 = ifmap_dw3_1_ce0_local;

assign ifmap_dw3_1_d0 = select_ln4_2_reg_2722;

assign ifmap_dw3_1_we0 = ifmap_dw3_1_we0_local;

assign ifmap_dw3_2_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_2_ce0 = ifmap_dw3_2_ce0_local;

assign ifmap_dw3_2_d0 = select_ln4_3_reg_2730;

assign ifmap_dw3_2_we0 = ifmap_dw3_2_we0_local;

assign ifmap_dw3_3_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_3_ce0 = ifmap_dw3_3_ce0_local;

assign ifmap_dw3_3_d0 = select_ln4_4_reg_2738;

assign ifmap_dw3_3_we0 = ifmap_dw3_3_we0_local;

assign ifmap_dw3_4_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_4_ce0 = ifmap_dw3_4_ce0_local;

assign ifmap_dw3_4_d0 = select_ln4_reg_2714;

assign ifmap_dw3_4_we0 = ifmap_dw3_4_we0_local;

assign ifmap_dw3_5_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_5_ce0 = ifmap_dw3_5_ce0_local;

assign ifmap_dw3_5_d0 = select_ln4_2_reg_2722;

assign ifmap_dw3_5_we0 = ifmap_dw3_5_we0_local;

assign ifmap_dw3_6_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_6_ce0 = ifmap_dw3_6_ce0_local;

assign ifmap_dw3_6_d0 = select_ln4_3_reg_2730;

assign ifmap_dw3_6_we0 = ifmap_dw3_6_we0_local;

assign ifmap_dw3_7_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_7_ce0 = ifmap_dw3_7_ce0_local;

assign ifmap_dw3_7_d0 = select_ln4_4_reg_2738;

assign ifmap_dw3_7_we0 = ifmap_dw3_7_we0_local;

assign ifmap_dw3_8_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_8_ce0 = ifmap_dw3_8_ce0_local;

assign ifmap_dw3_8_d0 = select_ln4_reg_2714;

assign ifmap_dw3_8_we0 = ifmap_dw3_8_we0_local;

assign ifmap_dw3_9_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_9_ce0 = ifmap_dw3_9_ce0_local;

assign ifmap_dw3_9_d0 = select_ln4_2_reg_2722;

assign ifmap_dw3_9_we0 = ifmap_dw3_9_we0_local;

assign ifmap_dw3_address0 = zext_ln135_fu_2551_p1;

assign ifmap_dw3_ce0 = ifmap_dw3_ce0_local;

assign ifmap_dw3_d0 = select_ln4_reg_2714;

assign ifmap_dw3_we0 = ifmap_dw3_we0_local;

assign ofmap_pw2_1_address0 = zext_ln139_1_fu_1278_p1;

assign ofmap_pw2_1_ce0 = ofmap_pw2_1_ce0_local;

assign ofmap_pw2_2_address0 = zext_ln139_1_fu_1278_p1;

assign ofmap_pw2_2_ce0 = ofmap_pw2_2_ce0_local;

assign ofmap_pw2_3_address0 = zext_ln139_1_fu_1278_p1;

assign ofmap_pw2_3_ce0 = ofmap_pw2_3_ce0_local;

assign ofmap_pw2_address0 = zext_ln139_1_fu_1278_p1;

assign ofmap_pw2_ce0 = ofmap_pw2_ce0_local;

assign or_ln4_2_fu_2436_p2 = (icmp_ln4_6_fu_2430_p2 | icmp_ln4_5_fu_2424_p2);

assign or_ln4_3_fu_2484_p2 = (icmp_ln4_8_fu_2478_p2 | icmp_ln4_7_fu_2472_p2);

assign or_ln4_4_fu_2532_p2 = (icmp_ln4_9_fu_2520_p2 | icmp_ln4_10_fu_2526_p2);

assign or_ln4_fu_2388_p2 = (icmp_ln4_fu_2376_p2 | icmp_ln4_4_fu_2382_p2);

assign select_ln135_1_fu_1248_p3 = ((icmp_ln136_fu_1234_p2[0:0] == 1'b1) ? add_ln135_fu_1228_p2 : ap_sig_allocacmp_c_load);

assign select_ln135_fu_1240_p3 = ((icmp_ln136_fu_1234_p2[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_h_load);

assign select_ln4_2_fu_2448_p3 = ((and_ln4_2_fu_2442_p2[0:0] == 1'b1) ? x_assign_2_reg_2693_pp0_iter11_reg : 32'd0);

assign select_ln4_3_fu_2496_p3 = ((and_ln4_3_fu_2490_p2[0:0] == 1'b1) ? x_assign_3_reg_2700_pp0_iter11_reg : 32'd0);

assign select_ln4_4_fu_2544_p3 = ((and_ln4_4_fu_2538_p2[0:0] == 1'b1) ? x_assign_4_reg_2707_pp0_iter11_reg : 32'd0);

assign select_ln4_fu_2400_p3 = ((and_ln4_fu_2394_p2[0:0] == 1'b1) ? x_assign_s_reg_2686_pp0_iter11_reg : 32'd0);

assign tmp_100_fu_1840_p257 = 'bx;

assign tmp_43_fu_2362_p4 = {{bitcast_ln4_fu_2359_p1[30:23]}};

assign tmp_45_fu_2410_p4 = {{bitcast_ln4_2_fu_2407_p1[30:23]}};

assign tmp_47_fu_2458_p4 = {{bitcast_ln4_3_fu_2455_p1[30:23]}};

assign tmp_49_fu_2506_p4 = {{bitcast_ln4_4_fu_2503_p1[30:23]}};

assign tmp_99_fu_1321_p257 = 'bx;

assign tmp_s_fu_1260_p3 = {{trunc_ln135_fu_1256_p1}, {2'd0}};

assign trunc_ln135_fu_1256_p1 = select_ln135_1_fu_1248_p3[6:0];

assign trunc_ln136_fu_1286_p1 = select_ln135_fu_1240_p3[1:0];

assign trunc_ln4_2_fu_2420_p1 = bitcast_ln4_2_fu_2407_p1[22:0];

assign trunc_ln4_3_fu_2468_p1 = bitcast_ln4_3_fu_2455_p1[22:0];

assign trunc_ln4_4_fu_2516_p1 = bitcast_ln4_4_fu_2503_p1[22:0];

assign trunc_ln4_fu_2372_p1 = bitcast_ln4_fu_2359_p1[22:0];

assign zext_ln135_fu_2551_p1 = select_ln135_1_reg_2595_pp0_iter12_reg;

assign zext_ln139_1_fu_1278_p1 = add_ln139_fu_1272_p2;

assign zext_ln139_fu_1268_p1 = select_ln135_fu_1240_p3;

endmodule //mobilenet_v1_mobilenet_v1_Pipeline_BN_PW2_C_BN_PW2_H
