// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_fc_Pipeline_FC_OUTPUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add8_reload,
        add_19_reload,
        add_210_reload,
        add_311_reload,
        add_412_reload,
        add_513_reload,
        add_614_reload,
        add_715_reload,
        add_816_reload,
        add_917_reload,
        ofmap_address0,
        ofmap_ce0,
        ofmap_we0,
        ofmap_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] add8_reload;
input  [31:0] add_19_reload;
input  [31:0] add_210_reload;
input  [31:0] add_311_reload;
input  [31:0] add_412_reload;
input  [31:0] add_513_reload;
input  [31:0] add_614_reload;
input  [31:0] add_715_reload;
input  [31:0] add_816_reload;
input  [31:0] add_917_reload;
output  [3:0] ofmap_address0;
output   ofmap_ce0;
output   ofmap_we0;
output  [31:0] ofmap_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln25_fu_155_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln25_fu_167_p1;
reg   [3:0] oc_fu_70;
wire   [3:0] add_ln25_fu_161_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_oc_1;
reg    ofmap_we0_local;
wire   [31:0] tmp_fu_172_p23;
reg    ofmap_ce0_local;
wire   [31:0] tmp_fu_172_p21;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_fu_172_p1;
wire   [3:0] tmp_fu_172_p3;
wire   [3:0] tmp_fu_172_p5;
wire   [3:0] tmp_fu_172_p7;
wire   [3:0] tmp_fu_172_p9;
wire   [3:0] tmp_fu_172_p11;
wire   [3:0] tmp_fu_172_p13;
wire   [3:0] tmp_fu_172_p15;
wire  signed [3:0] tmp_fu_172_p17;
wire  signed [3:0] tmp_fu_172_p19;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 oc_fu_70 = 4'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mobilenet_v1_sparsemux_21_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_21_4_32_1_1_U1285(
    .din0(add8_reload),
    .din1(add_19_reload),
    .din2(add_210_reload),
    .din3(add_311_reload),
    .din4(add_412_reload),
    .din5(add_513_reload),
    .din6(add_614_reload),
    .din7(add_715_reload),
    .din8(add_816_reload),
    .din9(add_917_reload),
    .def(tmp_fu_172_p21),
    .sel(ap_sig_allocacmp_oc_1),
    .dout(tmp_fu_172_p23)
);

mobilenet_v1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln25_fu_155_p2 == 1'd0)) begin
            oc_fu_70 <= add_ln25_fu_161_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_70 <= 4'd0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_155_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_oc_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_oc_1 = oc_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ofmap_ce0_local = 1'b1;
    end else begin
        ofmap_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_155_p2 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ofmap_we0_local = 1'b1;
    end else begin
        ofmap_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln25_fu_161_p2 = (ap_sig_allocacmp_oc_1 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln25_fu_155_p2 = ((ap_sig_allocacmp_oc_1 == 4'd10) ? 1'b1 : 1'b0);

assign ofmap_address0 = zext_ln25_fu_167_p1;

assign ofmap_ce0 = ofmap_ce0_local;

assign ofmap_d0 = tmp_fu_172_p23;

assign ofmap_we0 = ofmap_we0_local;

assign tmp_fu_172_p21 = 'bx;

assign zext_ln25_fu_167_p1 = ap_sig_allocacmp_oc_1;

endmodule //mobilenet_v1_fc_Pipeline_FC_OUTPUT
