-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_conv0_p_ZL13conv_0_weight_1_1_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_conv0_p_ZL13conv_0_weight_1_1_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111111000111100101110011110001", 1 => "00000000000000000000000000000000", 2 => "10111111010010110010111111101110", 3 => "00000000000000000000000000000000", 
    4 => "10111110101100010100010101111110", 5 => "00000000000000000000000000000000", 6 => "10111110101011001000010111011000", 7 => "00000000000000000000000000000000", 
    8 => "10111111000011100100010001110011", 9 => "00000000000000000000000000000000", 10 => "00111110011000011101010101111010", 11 => "00000000000000000000000000000000", 
    12 => "10111101100000010000100011111110", 13 => "00000000000000000000000000000000", 14 => "00111110000100111111001111011001", 15 => "00000000000000000000000000000000", 
    16 => "00111101100101100101000100111000", 17 => "00000000000000000000000000000000", 18 => "10111110011011111000010010101001", 19 => "00000000000000000000000000000000", 
    20 => "10111110011111011011011100010110", 21 => "00000000000000000000000000000000", 22 => "00111111000101101001011100010001", 23 => "00000000000000000000000000000000", 
    24 => "10111111000010101111001101011011", 25 => "00000000000000000000000000000000", 26 => "00111110000100111101000000101110", 27 => "00000000000000000000000000000000", 
    28 => "00111101100010010011100110011000", 29 => "00000000000000000000000000000000", 30 => "00111100101010000011010000101100", 31 => "00000000000000000000000000000000");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

