-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_conv0_p_ZL13conv_0_weight_0_0_0_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_conv0_p_ZL13conv_0_weight_0_0_0_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "10111110010001110110100111011111", 1 => "10111110010011011110001111100000", 2 => "10111100010111000101001111111110", 3 => "00111101010101010100110111010010", 
    4 => "00111110001010111110011100011111", 5 => "10111100110011010000010110010111", 6 => "00111110010111110100100010010001", 7 => "10111101110010011010001010110010", 
    8 => "00111110000110110010011110000010", 9 => "00111110010111000011101111100111", 10 => "10111101101110010001011101011001", 11 => "00111111000101001010011101011001", 
    12 => "00111111001110101001011111010010", 13 => "00111101101110001100110011000011", 14 => "00111110010010101011011011000010", 15 => "00111100010001010110110111111110", 
    16 => "00111110010001111111010100111000", 17 => "00111111000011111001011000000000", 18 => "00111100100100110000001011110111", 19 => "00111101000001010001110111011111", 
    20 => "10111110011111100000010000000001", 21 => "10111011101001011010110011001101", 22 => "00111110100101000111101011111111", 23 => "10111101101110011011010000111011", 
    24 => "10111001101110100101011110101010", 25 => "00111110000110001111110011000111", 26 => "10111110110100111111110000100000", 27 => "00111110101100010110101101000111", 
    28 => "00111110100010000000001110101010", 29 => "00111110001101100100100000001101", 30 => "10111101100001110010001111101101", 31 => "00111110001000011001010110010111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

