-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_1_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_1_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110101100000011011011000000", 1 => "00111110101101110100000010011000", 2 => "10111110001100101111000101010111", 3 => "00111110110100011010110100010110", 
    4 => "10111111000110101001110111000110", 5 => "00111111000010010011010110111111", 6 => "00111110100011000100110001010000", 7 => "10111110100001000011101101000000", 
    8 => "10111111000011100010001101100111", 9 => "00111110111011111110000110010111", 10 => "00111110101010111110011100001100", 11 => "00111110000010011101010111010101", 
    12 => "10111101111110110000000110111010", 13 => "10111110000011010011111110110101", 14 => "00111110110000110000001101101011", 15 => "00111101011111000101001011000100", 
    16 => "00111110111001110010010001101011", 17 => "10111110110111111110000100101000", 18 => "00111101011011001010000011110110", 19 => "00111101010100111010000010000001", 
    20 => "00111101101011010100110000010011", 21 => "10111111000001000101010010000010", 22 => "10111101101011100011001001010000", 23 => "00111110011010101001110011001001", 
    24 => "00111110100101111110000101100111", 25 => "10111111000000110001100100011010", 26 => "10111110101010111101001001000000", 27 => "00111111000101001001011100100001", 
    28 => "00111110011001100110100110111001", 29 => "00111110010100001001110000100111", 30 => "00111110100101010001010000011100", 31 => "10111110001010010001111110001110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

