-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_0_1_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_0_1_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110110101101101100010110011", 1 => "00111110101001110000011000101111", 2 => "10111111000010000000111011111001", 3 => "00111101111010000001110110101001", 
    4 => "00111101110110100001001000111010", 5 => "00111110011001010001110011010100", 6 => "00111110110101111110110110000110", 7 => "10111111000101111000011100010010", 
    8 => "10111110011001001001000100111100", 9 => "00111110000100000000100011000000", 10 => "00111110110100011001111100001000", 11 => "10111110101111000001111000001100", 
    12 => "10111110110010000110110111110111", 13 => "10111110100000011000011111110100", 14 => "10111111000010000101100111010000", 15 => "10111110111111110011100011111010", 
    16 => "00111101101001100110001110001010", 17 => "10111110001100101011110000101010", 18 => "00111101010000001001010010000000", 19 => "10111111000000110111101110001100", 
    20 => "00111111000011011101101000100011", 21 => "00111101001011010001001101011100", 22 => "10111110011000010101001001001110", 23 => "00111110100111101100000100000000", 
    24 => "00111110100010110101001111110010", 25 => "10111110010000010110001000001111", 26 => "00111101111000011111110101100111", 27 => "00111101111001110011001101000100", 
    28 => "00111110011010111111000011001110", 29 => "00111110100101101101000111000000", 30 => "00111110111011011101000000001000", 31 => "10111110100001011100110100010100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

