// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_qat_mobilenet_v1_qat_Pipeline_GAP_C (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pw3_out_address0,
        pw3_out_ce0,
        pw3_out_q0,
        pw3_out_address1,
        pw3_out_ce1,
        pw3_out_q1,
        pw3_out_1_address0,
        pw3_out_1_ce0,
        pw3_out_1_q0,
        pw3_out_1_address1,
        pw3_out_1_ce1,
        pw3_out_1_q1,
        gap_out_address0,
        gap_out_ce0,
        gap_out_we0,
        gap_out_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] pw3_out_address0;
output   pw3_out_ce0;
input  [6:0] pw3_out_q0;
output  [8:0] pw3_out_address1;
output   pw3_out_ce1;
input  [6:0] pw3_out_q1;
output  [8:0] pw3_out_1_address0;
output   pw3_out_1_ce0;
input  [6:0] pw3_out_1_q0;
output  [8:0] pw3_out_1_address1;
output   pw3_out_1_ce1;
input  [6:0] pw3_out_1_q1;
output  [7:0] gap_out_address0;
output   gap_out_ce0;
output   gap_out_we0;
output  [6:0] gap_out_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln7_fu_119_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [8:0] c_1_reg_235;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] c_1_reg_235_pp0_iter1_reg;
reg   [6:0] trunc_ln_reg_264;
wire   [63:0] zext_ln14_1_fu_141_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln14_3_fu_155_p1;
wire   [63:0] zext_ln7_fu_224_p1;
reg   [8:0] c_fu_44;
wire   [8:0] add_ln7_fu_125_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_c_1;
reg    pw3_out_ce1_local;
reg    pw3_out_ce0_local;
reg    pw3_out_1_ce1_local;
reg    pw3_out_1_ce0_local;
reg    gap_out_we0_local;
reg    gap_out_ce0_local;
wire   [8:0] shl_ln14_fu_135_p2;
wire   [7:0] trunc_ln7_fu_131_p1;
wire   [8:0] tmp_s_fu_147_p3;
wire   [7:0] zext_ln9_fu_166_p1;
wire   [7:0] zext_ln14_fu_170_p1;
wire   [7:0] add_ln17_fu_182_p2;
wire   [7:0] zext_ln17_fu_178_p1;
wire   [7:0] add_ln17_1_fu_192_p2;
wire   [8:0] zext_ln17_2_fu_198_p1;
wire   [8:0] zext_ln14_2_fu_174_p1;
wire   [8:0] add_ln17_2_fu_202_p2;
wire   [8:0] zext_ln17_1_fu_188_p1;
wire   [8:0] add_ln17_3_fu_208_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 c_fu_44 = 9'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_v1_qat_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln7_fu_119_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_44 <= add_ln7_fu_125_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_44 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        c_1_reg_235 <= ap_sig_allocacmp_c_1;
        c_1_reg_235_pp0_iter1_reg <= c_1_reg_235;
        trunc_ln_reg_264 <= {{add_ln17_3_fu_208_p2[8:2]}};
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_119_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_1 = 9'd0;
    end else begin
        ap_sig_allocacmp_c_1 = c_fu_44;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gap_out_ce0_local = 1'b1;
    end else begin
        gap_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        gap_out_we0_local = 1'b1;
    end else begin
        gap_out_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pw3_out_1_ce0_local = 1'b1;
    end else begin
        pw3_out_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pw3_out_1_ce1_local = 1'b1;
    end else begin
        pw3_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pw3_out_ce0_local = 1'b1;
    end else begin
        pw3_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pw3_out_ce1_local = 1'b1;
    end else begin
        pw3_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln17_1_fu_192_p2 = (zext_ln17_fu_178_p1 + 8'd2);

assign add_ln17_2_fu_202_p2 = (zext_ln17_2_fu_198_p1 + zext_ln14_2_fu_174_p1);

assign add_ln17_3_fu_208_p2 = (add_ln17_2_fu_202_p2 + zext_ln17_1_fu_188_p1);

assign add_ln17_fu_182_p2 = (zext_ln9_fu_166_p1 + zext_ln14_fu_170_p1);

assign add_ln7_fu_125_p2 = (ap_sig_allocacmp_c_1 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign gap_out_address0 = zext_ln7_fu_224_p1;

assign gap_out_ce0 = gap_out_ce0_local;

assign gap_out_d0 = trunc_ln_reg_264;

assign gap_out_we0 = gap_out_we0_local;

assign icmp_ln7_fu_119_p2 = ((ap_sig_allocacmp_c_1 == 9'd256) ? 1'b1 : 1'b0);

assign pw3_out_1_address0 = zext_ln14_3_fu_155_p1;

assign pw3_out_1_address1 = zext_ln14_1_fu_141_p1;

assign pw3_out_1_ce0 = pw3_out_1_ce0_local;

assign pw3_out_1_ce1 = pw3_out_1_ce1_local;

assign pw3_out_address0 = zext_ln14_3_fu_155_p1;

assign pw3_out_address1 = zext_ln14_1_fu_141_p1;

assign pw3_out_ce0 = pw3_out_ce0_local;

assign pw3_out_ce1 = pw3_out_ce1_local;

assign shl_ln14_fu_135_p2 = ap_sig_allocacmp_c_1 << 9'd1;

assign tmp_s_fu_147_p3 = {{trunc_ln7_fu_131_p1}, {1'd1}};

assign trunc_ln7_fu_131_p1 = ap_sig_allocacmp_c_1[7:0];

assign zext_ln14_1_fu_141_p1 = shl_ln14_fu_135_p2;

assign zext_ln14_2_fu_174_p1 = pw3_out_q0;

assign zext_ln14_3_fu_155_p1 = tmp_s_fu_147_p3;

assign zext_ln14_fu_170_p1 = pw3_out_1_q1;

assign zext_ln17_1_fu_188_p1 = add_ln17_fu_182_p2;

assign zext_ln17_2_fu_198_p1 = add_ln17_1_fu_192_p2;

assign zext_ln17_fu_178_p1 = pw3_out_1_q0;

assign zext_ln7_fu_224_p1 = c_1_reg_235_pp0_iter1_reg;

assign zext_ln9_fu_166_p1 = pw3_out_q1;

endmodule //mobilenet_v1_qat_mobilenet_v1_qat_Pipeline_GAP_C
