-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_0_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 128
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_0_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101111", 1 => "1111101", 2 => "1111010", 3 => "0001011", 
    4 => "0000001", 5 => "0011010", 6 => "0001101", 7 => "1101100", 
    8 => "0001010", 9 => "1100101", 10 => "1111010", 11 => "0000011", 
    12 => "1101101", 13 => "0001011", 14 => "1110100", 15 => "0001000", 
    16 => "0001111", 17 => "0010000", 18 => "1110010", 19 => "0011010", 
    20 => "1110001", 21 => "1111101", 22 => "1110111", 23 => "1110011", 
    24 => "1111110", 25 => "1101000", 26 => "1110110", 27 => "1110001", 
    28 => "1111111", 29 => "1111110", 30 => "1000000", 31 => "0010010", 
    32 => "1111100", 33 => "0001010", 34 => "1111111", 35 => "0010101", 
    36 => "1111000", 37 => "0010100", 38 => "1011010", 39 => "1111011", 
    40 => "1110001", 41 => "0000101", 42 => "0000101", 43 => "1110001", 
    44 => "1101110", 45 => "0001010", 46 => "1111110", 47 => "0001111", 
    48 => "0000000", 49 => "0000100", 50 => "1101111", 51 => "1101001", 
    52 => "0000000", 53 => "1010100", 54 => "0000001", 55 => "1100111", 
    56 => "1011111", 57 => "0011000", 58 => "1110011", 59 => "0011010", 
    60 => "1110011", 61 => "1110011", 62 => "0101001", 63 => "0110000", 
    64 => "1010110", 65 => "0001110", 66 => "0000111", 67 => "0010110", 
    68 => "0011001", 69 => "0110000", 70 => "0000011", 71 => "1110111", 
    72 => "0000001", 73 => "1111001", 74 => "1110110", 75 => "0000101", 
    76 => "0000111", 77 => "1111000", 78 => "0001100", 79 => "1100011", 
    80 => "1111100", 81 => "0000101", 82 => "1101111", 83 => "0001000", 
    84 => "0000110", 85 => "1111001", 86 => "0100010", 87 => "0001100", 
    88 => "0000101", 89 => "0010000", 90 => "0000101", 91 => "1010001", 
    92 => "1110111", 93 => "1101101", 94 => "0000010", 95 => "1111001", 
    96 => "0000011", 97 => "0001000", 98 => "0010111", 99 => "1111101", 
    100 => "1010010", 101 => "1110101", 102 => "1111011", 103 => "1101011", 
    104 => "0110100", 105 => "1100011", 106 => "0011010", 107 => "1111000", 
    108 => "1110100", 109 => "0101001", 110 => "0010101", 111 => "0000000", 
    112 => "0000100", 113 => "1011010", 114 => "0010100", 115 => "0001111", 
    116 => "1101111", 117 => "1101101", 118 => "0001011", 119 => "1111011", 
    120 => "0010101", 121 => "0011010", 122 => "0000001", 123 => "0000111", 
    124 => "1111101", 125 => "1011111", 126 => "1111011", 127 => "1111011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

