-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_2_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 128
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_2_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0101000", 1 => "0010001", 2 => "1100010", 3 => "0000110", 
    4 => "0011000", 5 => "0010111", 6 => "0001111", 7 => "1111100", 
    8 => "0000101", 9 => "1101001", 10 => "0000101", 11 => "0011111", 
    12 => "1101011", 13 => "0101011", 14 => "0011011", 15 => "0001010", 
    16 => "0000001", 17 => "0001000", 18 => "1110111", 19 => "1110010", 
    20 => "0001001", 21 => "0010110", 22 => "1110111", 23 => "0000100", 
    24 => "0011100", 25 => "1100000", 26 => "0011011", 27 => "1101100", 
    28 => "0001101", 29 => "0011100", 30 => "0011001", 31 => "0001100", 
    32 => "1111011", 33 => "0001011", 34 => "0010100", 35 => "0100000", 
    36 => "0001001", 37 => "1101011", 38 => "1101111", 39 => "1110101", 
    40 => "1111011", 41 => "0010101", 42 => "0000011", 43 => "0000100", 
    44 => "0001010", 45 => "0000100", 46 => "1101111", 47 => "1110101", 
    48 => "0001100", 49 => "0000011", 50 => "0011011", 51 => "1110001", 
    52 => "1101011", 53 => "1111111", 54 => "1110100", 55 => "0011111", 
    56 => "1111011", 57 => "0001100", 58 => "0001000", 59 => "0010001", 
    60 => "0001111", 61 => "1111101", 62 => "1010100", 63 => "1100101", 
    64 => "1110010", 65 => "0010000", 66 => "1101101", 67 => "1110111", 
    68 => "0001010", 69 => "1101111", 70 => "0010110", 71 => "1111001", 
    72 => "0000101", 73 => "0011111", 74 => "0000110", 75 => "1100101", 
    76 => "0011101", 77 => "0100010", 78 => "0001001", 79 => "0000010", 
    80 => "1111010", 81 => "0001011", 82 => "0001011", 83 => "1101010", 
    84 => "1011001", 85 => "0000000", 86 => "1110101", 87 => "1101110", 
    88 => "0001101", 89 => "1100010", 90 => "0001101", 91 => "0010101", 
    92 => "0001101", 93 => "1110101", 94 => "0011100", 95 => "1110001", 
    96 => "1110101", 97 => "0001101", 98 => "1100111", 99 => "1100011", 
    100 => "0011011", 101 => "0001110", 102 => "1111101", 103 => "0011011", 
    104 => "0000111", 105 => "0011000", 106 => "1100011", 107 => "0000011", 
    108 => "1111100", 109 => "1110110", 110 => "1101100", 111 => "0011010", 
    112 => "0000111", 113 => "1110011", 114 => "1101001", 115 => "0001110", 
    116 => "1111101", 117 => "1101111", 118 => "0000111", 119 => "1011101", 
    120 => "1101101", 121 => "1101101", 122 => "0000010", 123 => "0000001", 
    124 => "0010101", 125 => "0100100", 126 => "1111110", 127 => "0100100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

