-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_conv0_p_ZL13conv_0_weight_0_1_0_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_conv0_p_ZL13conv_0_weight_0_1_0_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110001001110100001001101010", 1 => "00111110110111000010110100101011", 2 => "10111101110010110000010010011010", 3 => "10111101000001100011111100000100", 
    4 => "10111011100100000111110110100111", 5 => "10111110100001001011001010110000", 6 => "00111110111100001111000001010110", 7 => "10111011001000001101000111110010", 
    8 => "00111110011111110101101011110100", 9 => "00111110001001001001010100011111", 10 => "10111110101111110010111000010011", 11 => "10111110101011110011110000011000", 
    12 => "10111101000110111000010100010100", 13 => "10111110001010111101011010111101", 14 => "10111101001111001100000011111001", 15 => "10111101101011110010010111001100", 
    16 => "10111110001010111010100011000011", 17 => "10111110110001111000011001101110", 18 => "00111110001101101001101000100111", 19 => "10111101000010011111001000010100", 
    20 => "10111110100011111110010111011001", 21 => "10111100110110001101011100010001", 22 => "10111110011011011001100010100011", 23 => "10111101100000011101110100001110", 
    24 => "10111110011000111101001101111011", 25 => "10111101011110110001110110000101", 26 => "10111111000100011110110011101010", 27 => "00111110011111010111010101001000", 
    28 => "00111110010010001101101000111000", 29 => "00111110110010101111110001110010", 30 => "10111101010010010111100110111111", 31 => "00111110101011101110001101100001");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

