-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_qat_dw2_qat_p_ZL20features_2_dw_w_fold_2_0_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_qat_dw2_qat_p_ZL20features_2_dw_w_fold_2_0_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1010010", 1 => "1110000", 2 => "0000011", 3 => "1101010", 
    4 => "0000001", 5 => "0000100", 6 => "0101101", 7 => "0001000", 
    8 => "0011010", 9 => "0011011", 10 => "1100110", 11 => "0000000", 
    12 => "1101111", 13 => "0001010", 14 => "1111110", 15 => "1100010", 
    16 => "0011101", 17 => "1111101", 18 => "1010101", 19 => "0010001", 
    20 => "0010010", 21 => "1110100", 22 => "1111011", 23 => "1111011", 
    24 => "1010010", 25 => "1110101", 26 => "0001010", 27 => "0100010", 
    28 => "0000010", 29 => "0000100", 30 => "0000110", 31 => "0000100", 
    32 => "1111110", 33 => "0001111", 34 => "0000101", 35 => "1011100", 
    36 => "1111100", 37 => "0011110", 38 => "0011101", 39 => "1011000", 
    40 => "0000100", 41 => "1101000", 42 => "1111010", 43 => "1111101", 
    44 => "0000001", 45 => "0011111", 46 => "0001101", 47 => "0000011", 
    48 => "1110100", 49 => "0000100", 50 => "0111111", 51 => "0011010", 
    52 => "1101100", 53 => "0001111", 54 => "0001100", 55 => "1010001", 
    56 => "1100101", 57 => "0010001", 58 => "1100110", 59 => "1101110", 
    60 => "1111011", 61 => "1111111", 62 => "0001001", 63 => "1111011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

