-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_qat_dw2_qat_p_ZL20features_2_dw_w_fold_2_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 64
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_qat_dw2_qat_p_ZL20features_2_dw_w_fold_2_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11010010", 1 => "11101010", 2 => "00000001", 3 => "11101011", 
    4 => "11111101", 5 => "11111011", 6 => "11101100", 7 => "00001011", 
    8 => "00010111", 9 => "11110100", 10 => "11100110", 11 => "00001101", 
    12 => "11100000", 13 => "00010011", 14 => "11111001", 15 => "11101011", 
    16 => "00001110", 17 => "11101010", 18 => "11101100", 19 => "11110010", 
    20 => "00011011", 21 => "11011100", 22 => "00001100", 23 => "00010001", 
    24 => "00010001", 25 => "11101110", 26 => "00001011", 27 => "00100101", 
    28 => "11111110", 29 => "00000101", 30 => "11101010", 31 => "00000010", 
    32 => "00000010", 33 => "11110110", 34 => "00001011", 35 => "00101011", 
    36 => "11111110", 37 => "11101101", 38 => "10111010", 39 => "00100000", 
    40 => "00001010", 41 => "00101010", 42 => "11110101", 43 => "00011000", 
    44 => "11101001", 45 => "11110101", 46 => "00010100", 47 => "00000001", 
    48 => "11110010", 49 => "00001011", 50 => "00100101", 51 => "00010100", 
    52 => "11011110", 53 => "00010011", 54 => "00011110", 55 => "00011011", 
    56 => "11110001", 57 => "11101100", 58 => "11100001", 59 => "11110110", 
    60 => "11111100", 61 => "11100111", 62 => "11111101", 63 => "11011110");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

