-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_qat_dw1_qat_p_ZL20features_1_dw_w_fold_1_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_qat_dw1_qat_p_ZL20features_1_dw_w_fold_1_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00001001", 1 => "11110001", 2 => "10110111", 3 => "11101110", 
    4 => "00011001", 5 => "00010110", 6 => "00111111", 7 => "00110101", 
    8 => "11100010", 9 => "00000101", 10 => "00001010", 11 => "01000001", 
    12 => "00001010", 13 => "11110110", 14 => "11110110", 15 => "00000101", 
    16 => "00000000", 17 => "11110000", 18 => "00010111", 19 => "00101100", 
    20 => "00001100", 21 => "00101000", 22 => "01001100", 23 => "00000010", 
    24 => "00001110", 25 => "00010110", 26 => "11011001", 27 => "00100011", 
    28 => "11011100", 29 => "11100101", 30 => "11101011", 31 => "01011100");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

