-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_1_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 7; 
             AddressWidth     : integer := 7; 
             AddressRange    : integer := 128
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_1_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "1101101", 1 => "1111010", 2 => "1101110", 3 => "0011000", 
    4 => "0100100", 5 => "0010011", 6 => "0010000", 7 => "1110010", 
    8 => "0010010", 9 => "1101100", 10 => "0000000", 11 => "0011001", 
    12 => "1101110", 13 => "1100110", 14 => "1011111", 15 => "0010010", 
    16 => "0001011", 17 => "0101011", 18 => "1100000", 19 => "1101110", 
    20 => "1110110", 21 => "0001000", 22 => "0010011", 23 => "0000100", 
    24 => "0100001", 25 => "1100011", 26 => "0000100", 27 => "1011001", 
    28 => "1110000", 29 => "1101011", 30 => "0011011", 31 => "0011000", 
    32 => "0011010", 33 => "0000001", 34 => "0001001", 35 => "1001110", 
    36 => "0010101", 37 => "0011000", 38 => "1111110", 39 => "0000000", 
    40 => "1100010", 41 => "0001011", 42 => "0010000", 43 => "1111011", 
    44 => "0000101", 45 => "0001000", 46 => "1111000", 47 => "1101110", 
    48 => "0001111", 49 => "0000001", 50 => "0000000", 51 => "1110110", 
    52 => "1101111", 53 => "0001001", 54 => "1110101", 55 => "1111001", 
    56 => "1110000", 57 => "0010111", 58 => "0001001", 59 => "0100110", 
    60 => "1110011", 61 => "1111101", 62 => "1111110", 63 => "1111001", 
    64 => "1011010", 65 => "0010110", 66 => "1101010", 67 => "1110100", 
    68 => "0010010", 69 => "0100001", 70 => "0100101", 71 => "0000011", 
    72 => "1110110", 73 => "1101010", 74 => "1110100", 75 => "1100000", 
    76 => "0011010", 77 => "1110001", 78 => "0011000", 79 => "0010101", 
    80 => "1111001", 81 => "0000111", 82 => "1011101", 83 => "1100011", 
    84 => "0110001", 85 => "0011011", 86 => "0000101", 87 => "1111111", 
    88 => "0000110", 89 => "0001010", 90 => "0010011", 91 => "1011010", 
    92 => "0000110", 93 => "0001011", 94 => "0001100", 95 => "1101101", 
    96 => "0000011", 97 => "0001101", 98 => "0001101", 99 => "0000001", 
    100 => "1010011", 101 => "0001111", 102 => "0011001", 103 => "0000100", 
    104 => "0010101", 105 => "1011011", 106 => "0000011", 107 => "0101001", 
    108 => "0010110", 109 => "0100010", 110 => "1110010", 111 => "0100011", 
    112 => "0010010", 113 => "0000101", 114 => "0001001", 115 => "0001100", 
    116 => "0010010", 117 => "1100000", 118 => "1111010", 119 => "1011111", 
    120 => "1111001", 121 => "0001010", 122 => "1100110", 123 => "0000011", 
    124 => "1111110", 125 => "1010111", 126 => "0010000", 127 => "0000101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

