// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_fc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ifmap_address0,
        ifmap_ce0,
        ifmap_q0,
        ofmap_address0,
        ofmap_ce0,
        ofmap_we0,
        ofmap_d0,
        grp_fu_2467_p_din0,
        grp_fu_2467_p_din1,
        grp_fu_2467_p_opcode,
        grp_fu_2467_p_dout0,
        grp_fu_2467_p_ce,
        grp_fu_2471_p_din0,
        grp_fu_2471_p_din1,
        grp_fu_2471_p_opcode,
        grp_fu_2471_p_dout0,
        grp_fu_2471_p_ce,
        grp_fu_2523_p_din0,
        grp_fu_2523_p_din1,
        grp_fu_2523_p_dout0,
        grp_fu_2523_p_ce,
        grp_fu_2527_p_din0,
        grp_fu_2527_p_din1,
        grp_fu_2527_p_dout0,
        grp_fu_2527_p_ce
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] ifmap_address0;
output   ifmap_ce0;
input  [31:0] ifmap_q0;
output  [3:0] ofmap_address0;
output   ofmap_ce0;
output   ofmap_we0;
output  [31:0] ofmap_d0;
output  [31:0] grp_fu_2467_p_din0;
output  [31:0] grp_fu_2467_p_din1;
output  [1:0] grp_fu_2467_p_opcode;
input  [31:0] grp_fu_2467_p_dout0;
output   grp_fu_2467_p_ce;
output  [31:0] grp_fu_2471_p_din0;
output  [31:0] grp_fu_2471_p_din1;
output  [1:0] grp_fu_2471_p_opcode;
input  [31:0] grp_fu_2471_p_dout0;
output   grp_fu_2471_p_ce;
output  [31:0] grp_fu_2523_p_din0;
output  [31:0] grp_fu_2523_p_din1;
input  [31:0] grp_fu_2523_p_dout0;
output   grp_fu_2523_p_ce;
output  [31:0] grp_fu_2527_p_din0;
output  [31:0] grp_fu_2527_p_din1;
input  [31:0] grp_fu_2527_p_dout0;
output   grp_fu_2527_p_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_ap_start;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_ap_done;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_ap_idle;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_ap_ready;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_9_promoted21_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_9_promoted21_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_8_promoted19_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_8_promoted19_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_7_promoted17_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_7_promoted17_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_6_promoted15_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_6_promoted15_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_5_promoted13_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_5_promoted13_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_4_promoted11_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_4_promoted11_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_3_promoted9_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_3_promoted9_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_2_promoted7_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_2_promoted7_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_1_promoted5_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_1_promoted5_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_promoted3_out;
wire    grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_promoted3_out_ap_vld;
wire    grp_fc_Pipeline_FC_IC_fu_130_ap_start;
wire    grp_fc_Pipeline_FC_IC_fu_130_ap_done;
wire    grp_fc_Pipeline_FC_IC_fu_130_ap_idle;
wire    grp_fc_Pipeline_FC_IC_fu_130_ap_ready;
wire   [7:0] grp_fc_Pipeline_FC_IC_fu_130_ifmap_address0;
wire    grp_fc_Pipeline_FC_IC_fu_130_ifmap_ce0;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_917_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_917_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_816_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_816_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_715_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_715_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_614_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_614_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_513_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_513_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_412_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_412_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_311_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_311_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_210_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_210_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add_19_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add_19_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_add8_out;
wire    grp_fc_Pipeline_FC_IC_fu_130_add8_out_ap_vld;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_din0;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_din1;
wire   [1:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_opcode;
wire    grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_ce;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_din0;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_din1;
wire   [1:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_opcode;
wire    grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_ce;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_din0;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_din1;
wire    grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_ce;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_din0;
wire   [31:0] grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_din1;
wire    grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_ce;
wire    grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start;
wire    grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_done;
wire    grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_idle;
wire    grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_ready;
wire   [3:0] grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_address0;
wire    grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_ce0;
wire    grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_we0;
wire   [31:0] grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_d0;
reg    grp_fc_Pipeline_FC_BIAS_fu_114_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_fc_Pipeline_FC_IC_fu_130_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_fu_452_ce;
reg    grp_fu_456_ce;
reg    grp_fu_460_ce;
reg    grp_fu_464_ce;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_fc_Pipeline_FC_BIAS_fu_114_ap_start_reg = 1'b0;
#0 grp_fc_Pipeline_FC_IC_fu_130_ap_start_reg = 1'b0;
#0 grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start_reg = 1'b0;
end

mobilenet_v1_fc_Pipeline_FC_BIAS grp_fc_Pipeline_FC_BIAS_fu_114(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fc_Pipeline_FC_BIAS_fu_114_ap_start),
    .ap_done(grp_fc_Pipeline_FC_BIAS_fu_114_ap_done),
    .ap_idle(grp_fc_Pipeline_FC_BIAS_fu_114_ap_idle),
    .ap_ready(grp_fc_Pipeline_FC_BIAS_fu_114_ap_ready),
    .arrayidx19_9_promoted21_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_9_promoted21_out),
    .arrayidx19_9_promoted21_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_9_promoted21_out_ap_vld),
    .arrayidx19_8_promoted19_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_8_promoted19_out),
    .arrayidx19_8_promoted19_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_8_promoted19_out_ap_vld),
    .arrayidx19_7_promoted17_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_7_promoted17_out),
    .arrayidx19_7_promoted17_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_7_promoted17_out_ap_vld),
    .arrayidx19_6_promoted15_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_6_promoted15_out),
    .arrayidx19_6_promoted15_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_6_promoted15_out_ap_vld),
    .arrayidx19_5_promoted13_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_5_promoted13_out),
    .arrayidx19_5_promoted13_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_5_promoted13_out_ap_vld),
    .arrayidx19_4_promoted11_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_4_promoted11_out),
    .arrayidx19_4_promoted11_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_4_promoted11_out_ap_vld),
    .arrayidx19_3_promoted9_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_3_promoted9_out),
    .arrayidx19_3_promoted9_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_3_promoted9_out_ap_vld),
    .arrayidx19_2_promoted7_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_2_promoted7_out),
    .arrayidx19_2_promoted7_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_2_promoted7_out_ap_vld),
    .arrayidx19_1_promoted5_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_1_promoted5_out),
    .arrayidx19_1_promoted5_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_1_promoted5_out_ap_vld),
    .arrayidx19_promoted3_out(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_promoted3_out),
    .arrayidx19_promoted3_out_ap_vld(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_promoted3_out_ap_vld)
);

mobilenet_v1_fc_Pipeline_FC_IC grp_fc_Pipeline_FC_IC_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fc_Pipeline_FC_IC_fu_130_ap_start),
    .ap_done(grp_fc_Pipeline_FC_IC_fu_130_ap_done),
    .ap_idle(grp_fc_Pipeline_FC_IC_fu_130_ap_idle),
    .ap_ready(grp_fc_Pipeline_FC_IC_fu_130_ap_ready),
    .arrayidx19_9_promoted21_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_9_promoted21_out),
    .arrayidx19_8_promoted19_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_8_promoted19_out),
    .arrayidx19_7_promoted17_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_7_promoted17_out),
    .arrayidx19_6_promoted15_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_6_promoted15_out),
    .arrayidx19_5_promoted13_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_5_promoted13_out),
    .arrayidx19_4_promoted11_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_4_promoted11_out),
    .arrayidx19_3_promoted9_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_3_promoted9_out),
    .arrayidx19_2_promoted7_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_2_promoted7_out),
    .arrayidx19_1_promoted5_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_1_promoted5_out),
    .arrayidx19_promoted3_reload(grp_fc_Pipeline_FC_BIAS_fu_114_arrayidx19_promoted3_out),
    .ifmap_address0(grp_fc_Pipeline_FC_IC_fu_130_ifmap_address0),
    .ifmap_ce0(grp_fc_Pipeline_FC_IC_fu_130_ifmap_ce0),
    .ifmap_q0(ifmap_q0),
    .add_917_out(grp_fc_Pipeline_FC_IC_fu_130_add_917_out),
    .add_917_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_917_out_ap_vld),
    .add_816_out(grp_fc_Pipeline_FC_IC_fu_130_add_816_out),
    .add_816_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_816_out_ap_vld),
    .add_715_out(grp_fc_Pipeline_FC_IC_fu_130_add_715_out),
    .add_715_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_715_out_ap_vld),
    .add_614_out(grp_fc_Pipeline_FC_IC_fu_130_add_614_out),
    .add_614_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_614_out_ap_vld),
    .add_513_out(grp_fc_Pipeline_FC_IC_fu_130_add_513_out),
    .add_513_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_513_out_ap_vld),
    .add_412_out(grp_fc_Pipeline_FC_IC_fu_130_add_412_out),
    .add_412_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_412_out_ap_vld),
    .add_311_out(grp_fc_Pipeline_FC_IC_fu_130_add_311_out),
    .add_311_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_311_out_ap_vld),
    .add_210_out(grp_fc_Pipeline_FC_IC_fu_130_add_210_out),
    .add_210_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_210_out_ap_vld),
    .add_19_out(grp_fc_Pipeline_FC_IC_fu_130_add_19_out),
    .add_19_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add_19_out_ap_vld),
    .add8_out(grp_fc_Pipeline_FC_IC_fu_130_add8_out),
    .add8_out_ap_vld(grp_fc_Pipeline_FC_IC_fu_130_add8_out_ap_vld),
    .grp_fu_452_p_din0(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_din0),
    .grp_fu_452_p_din1(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_din1),
    .grp_fu_452_p_opcode(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_opcode),
    .grp_fu_452_p_dout0(grp_fu_2467_p_dout0),
    .grp_fu_452_p_ce(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_ce),
    .grp_fu_456_p_din0(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_din0),
    .grp_fu_456_p_din1(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_din1),
    .grp_fu_456_p_opcode(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_opcode),
    .grp_fu_456_p_dout0(grp_fu_2471_p_dout0),
    .grp_fu_456_p_ce(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_ce),
    .grp_fu_460_p_din0(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_din0),
    .grp_fu_460_p_din1(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_din1),
    .grp_fu_460_p_dout0(grp_fu_2523_p_dout0),
    .grp_fu_460_p_ce(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_ce),
    .grp_fu_464_p_din0(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_din0),
    .grp_fu_464_p_din1(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_din1),
    .grp_fu_464_p_dout0(grp_fu_2527_p_dout0),
    .grp_fu_464_p_ce(grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_ce)
);

mobilenet_v1_fc_Pipeline_FC_OUTPUT grp_fc_Pipeline_FC_OUTPUT_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start),
    .ap_done(grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_done),
    .ap_idle(grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_idle),
    .ap_ready(grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_ready),
    .add8_reload(grp_fc_Pipeline_FC_IC_fu_130_add8_out),
    .add_19_reload(grp_fc_Pipeline_FC_IC_fu_130_add_19_out),
    .add_210_reload(grp_fc_Pipeline_FC_IC_fu_130_add_210_out),
    .add_311_reload(grp_fc_Pipeline_FC_IC_fu_130_add_311_out),
    .add_412_reload(grp_fc_Pipeline_FC_IC_fu_130_add_412_out),
    .add_513_reload(grp_fc_Pipeline_FC_IC_fu_130_add_513_out),
    .add_614_reload(grp_fc_Pipeline_FC_IC_fu_130_add_614_out),
    .add_715_reload(grp_fc_Pipeline_FC_IC_fu_130_add_715_out),
    .add_816_reload(grp_fc_Pipeline_FC_IC_fu_130_add_816_out),
    .add_917_reload(grp_fc_Pipeline_FC_IC_fu_130_add_917_out),
    .ofmap_address0(grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_address0),
    .ofmap_ce0(grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_ce0),
    .ofmap_we0(grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_we0),
    .ofmap_d0(grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fc_Pipeline_FC_BIAS_fu_114_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_fc_Pipeline_FC_BIAS_fu_114_ap_start_reg <= 1'b1;
        end else if ((grp_fc_Pipeline_FC_BIAS_fu_114_ap_ready == 1'b1)) begin
            grp_fc_Pipeline_FC_BIAS_fu_114_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fc_Pipeline_FC_IC_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fc_Pipeline_FC_IC_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_fc_Pipeline_FC_IC_fu_130_ap_ready == 1'b1)) begin
            grp_fc_Pipeline_FC_IC_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_ready == 1'b1)) begin
            grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fc_Pipeline_FC_BIAS_fu_114_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fc_Pipeline_FC_IC_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state6) & (grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_452_ce = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_ce;
    end else begin
        grp_fu_452_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_456_ce = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_ce;
    end else begin
        grp_fu_456_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_460_ce = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_ce;
    end else begin
        grp_fu_460_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_464_ce = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_ce;
    end else begin
        grp_fu_464_ce = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_fc_Pipeline_FC_BIAS_fu_114_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fc_Pipeline_FC_IC_fu_130_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_fc_Pipeline_FC_BIAS_fu_114_ap_start = grp_fc_Pipeline_FC_BIAS_fu_114_ap_start_reg;

assign grp_fc_Pipeline_FC_IC_fu_130_ap_start = grp_fc_Pipeline_FC_IC_fu_130_ap_start_reg;

assign grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start = grp_fc_Pipeline_FC_OUTPUT_fu_176_ap_start_reg;

assign grp_fu_2467_p_ce = grp_fu_452_ce;

assign grp_fu_2467_p_din0 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_din0;

assign grp_fu_2467_p_din1 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_452_p_din1;

assign grp_fu_2467_p_opcode = 2'd0;

assign grp_fu_2471_p_ce = grp_fu_456_ce;

assign grp_fu_2471_p_din0 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_din0;

assign grp_fu_2471_p_din1 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_456_p_din1;

assign grp_fu_2471_p_opcode = 2'd0;

assign grp_fu_2523_p_ce = grp_fu_460_ce;

assign grp_fu_2523_p_din0 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_din0;

assign grp_fu_2523_p_din1 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_460_p_din1;

assign grp_fu_2527_p_ce = grp_fu_464_ce;

assign grp_fu_2527_p_din0 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_din0;

assign grp_fu_2527_p_din1 = grp_fc_Pipeline_FC_IC_fu_130_grp_fu_464_p_din1;

assign ifmap_address0 = grp_fc_Pipeline_FC_IC_fu_130_ifmap_address0;

assign ifmap_ce0 = grp_fc_Pipeline_FC_IC_fu_130_ifmap_ce0;

assign ofmap_address0 = grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_address0;

assign ofmap_ce0 = grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_ce0;

assign ofmap_d0 = grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_d0;

assign ofmap_we0 = grp_fc_Pipeline_FC_OUTPUT_fu_176_ofmap_we0;

endmodule //mobilenet_v1_fc
