// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_mobilenet_v1_Pipeline_BN_DW0_C_BN_DW0_H_BN_DW0_W (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ofmap_dw0_address0,
        ofmap_dw0_ce0,
        ofmap_dw0_q0,
        ifmap_pw0_address1,
        ifmap_pw0_ce1,
        ifmap_pw0_we1,
        ifmap_pw0_d1,
        ifmap_pw0_1_address1,
        ifmap_pw0_1_ce1,
        ifmap_pw0_1_we1,
        ifmap_pw0_1_d1,
        grp_fu_2467_p_din0,
        grp_fu_2467_p_din1,
        grp_fu_2467_p_opcode,
        grp_fu_2467_p_dout0,
        grp_fu_2467_p_ce,
        grp_fu_2523_p_din0,
        grp_fu_2523_p_din1,
        grp_fu_2523_p_dout0,
        grp_fu_2523_p_ce,
        grp_fu_2599_p_din0,
        grp_fu_2599_p_din1,
        grp_fu_2599_p_opcode,
        grp_fu_2599_p_dout0,
        grp_fu_2599_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] ofmap_dw0_address0;
output   ofmap_dw0_ce0;
input  [31:0] ofmap_dw0_q0;
output  [10:0] ifmap_pw0_address1;
output   ifmap_pw0_ce1;
output   ifmap_pw0_we1;
output  [31:0] ifmap_pw0_d1;
output  [10:0] ifmap_pw0_1_address1;
output   ifmap_pw0_1_ce1;
output   ifmap_pw0_1_we1;
output  [31:0] ifmap_pw0_1_d1;
output  [31:0] grp_fu_2467_p_din0;
output  [31:0] grp_fu_2467_p_din1;
output  [1:0] grp_fu_2467_p_opcode;
input  [31:0] grp_fu_2467_p_dout0;
output   grp_fu_2467_p_ce;
output  [31:0] grp_fu_2523_p_din0;
output  [31:0] grp_fu_2523_p_din1;
input  [31:0] grp_fu_2523_p_dout0;
output   grp_fu_2523_p_ce;
output  [31:0] grp_fu_2599_p_din0;
output  [31:0] grp_fu_2599_p_din1;
output  [4:0] grp_fu_2599_p_opcode;
input  [0:0] grp_fu_2599_p_dout0;
output   grp_fu_2599_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln35_fu_291_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] trunc_ln36_fu_358_p1;
reg   [3:0] trunc_ln36_reg_755;
reg   [3:0] trunc_ln36_reg_755_pp0_iter2_reg;
reg   [3:0] trunc_ln36_reg_755_pp0_iter3_reg;
reg   [3:0] trunc_ln36_reg_755_pp0_iter4_reg;
reg   [3:0] trunc_ln36_reg_755_pp0_iter5_reg;
reg   [3:0] trunc_ln36_reg_755_pp0_iter6_reg;
wire   [4:0] w_mid2_fu_374_p3;
reg   [4:0] w_mid2_reg_762;
wire   [4:0] select_ln36_fu_382_p3;
reg   [4:0] select_ln36_reg_768;
wire   [0:0] trunc_ln35_fu_390_p1;
reg   [0:0] trunc_ln35_reg_774;
reg   [0:0] trunc_ln35_reg_774_pp0_iter2_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter3_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter4_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter5_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter6_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter7_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter8_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter9_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter10_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter11_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter12_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter13_reg;
reg   [0:0] trunc_ln35_reg_774_pp0_iter14_reg;
reg   [2:0] lshr_ln_reg_778;
wire   [10:0] add_ln39_4_fu_514_p2;
reg   [10:0] add_ln39_4_reg_788;
reg   [10:0] add_ln39_4_reg_788_pp0_iter3_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter4_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter5_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter6_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter7_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter8_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter9_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter10_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter11_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter12_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter13_reg;
reg   [10:0] add_ln39_4_reg_788_pp0_iter14_reg;
reg   [31:0] ofmap_dw0_load_reg_793;
wire   [31:0] tmp_fu_520_p35;
wire   [31:0] tmp_s_fu_592_p35;
reg   [31:0] tmp_s_reg_803;
reg   [31:0] mul_i_reg_808;
reg   [31:0] x_assign_8_reg_813;
reg   [31:0] x_assign_8_reg_813_pp0_iter13_reg;
wire   [31:0] select_ln4_8_fu_704_p3;
reg   [31:0] select_ln4_8_reg_820;
wire   [63:0] zext_ln39_4_fu_509_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln39_5_fu_711_p1;
reg   [4:0] w_fu_180;
wire   [4:0] add_ln37_fu_404_p2;
wire    ap_loop_init;
reg   [4:0] h_fu_184;
reg   [9:0] indvar_flatten19_fu_188;
wire   [9:0] select_ln36_1_fu_416_p3;
reg   [4:0] c_fu_192;
wire   [4:0] select_ln35_1_fu_350_p3;
reg   [12:0] indvar_flatten32_fu_196;
wire   [12:0] add_ln35_1_fu_297_p2;
reg    ofmap_dw0_ce0_local;
reg    ifmap_pw0_we1_local;
reg    ifmap_pw0_ce1_local;
reg    ifmap_pw0_1_we1_local;
reg    ifmap_pw0_1_ce1_local;
wire   [0:0] icmp_ln36_fu_318_p2;
wire   [0:0] icmp_ln37_fu_338_p2;
wire   [0:0] xor_ln35_fu_332_p2;
wire   [4:0] add_ln35_fu_312_p2;
wire   [4:0] select_ln35_fu_324_p3;
wire   [0:0] and_ln35_fu_344_p2;
wire   [0:0] empty_fu_368_p2;
wire   [4:0] add_ln36_fu_362_p2;
wire   [9:0] add_ln36_1_fu_410_p2;
wire   [7:0] tmp_124_fu_449_p3;
wire   [7:0] zext_ln39_1_fu_466_p1;
wire   [7:0] add_ln39_fu_469_p2;
wire   [6:0] tmp_125_fu_456_p3;
wire   [6:0] zext_ln39_fu_463_p1;
wire   [6:0] add_ln39_2_fu_483_p2;
wire   [11:0] tmp_67_fu_475_p3;
wire   [11:0] zext_ln39_3_fu_500_p1;
wire   [11:0] add_ln39_3_fu_503_p2;
wire   [10:0] tmp_68_fu_489_p3;
wire   [10:0] zext_ln39_2_fu_497_p1;
wire   [31:0] tmp_fu_520_p33;
wire   [31:0] tmp_s_fu_592_p33;
wire   [31:0] bitcast_ln4_8_fu_663_p1;
wire   [7:0] tmp_17_fu_666_p4;
wire   [22:0] trunc_ln4_fu_676_p1;
wire   [0:0] icmp_ln4_17_fu_686_p2;
wire   [0:0] icmp_ln4_16_fu_680_p2;
wire   [0:0] or_ln4_8_fu_692_p2;
wire   [0:0] and_ln4_8_fu_698_p2;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [3:0] tmp_fu_520_p1;
wire   [3:0] tmp_fu_520_p3;
wire   [3:0] tmp_fu_520_p5;
wire   [3:0] tmp_fu_520_p7;
wire   [3:0] tmp_fu_520_p9;
wire   [3:0] tmp_fu_520_p11;
wire   [3:0] tmp_fu_520_p13;
wire   [3:0] tmp_fu_520_p15;
wire  signed [3:0] tmp_fu_520_p17;
wire  signed [3:0] tmp_fu_520_p19;
wire  signed [3:0] tmp_fu_520_p21;
wire  signed [3:0] tmp_fu_520_p23;
wire  signed [3:0] tmp_fu_520_p25;
wire  signed [3:0] tmp_fu_520_p27;
wire  signed [3:0] tmp_fu_520_p29;
wire  signed [3:0] tmp_fu_520_p31;
wire   [3:0] tmp_s_fu_592_p1;
wire   [3:0] tmp_s_fu_592_p3;
wire   [3:0] tmp_s_fu_592_p5;
wire   [3:0] tmp_s_fu_592_p7;
wire   [3:0] tmp_s_fu_592_p9;
wire   [3:0] tmp_s_fu_592_p11;
wire   [3:0] tmp_s_fu_592_p13;
wire   [3:0] tmp_s_fu_592_p15;
wire  signed [3:0] tmp_s_fu_592_p17;
wire  signed [3:0] tmp_s_fu_592_p19;
wire  signed [3:0] tmp_s_fu_592_p21;
wire  signed [3:0] tmp_s_fu_592_p23;
wire  signed [3:0] tmp_s_fu_592_p25;
wire  signed [3:0] tmp_s_fu_592_p27;
wire  signed [3:0] tmp_s_fu_592_p29;
wire  signed [3:0] tmp_s_fu_592_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 w_fu_180 = 5'd0;
#0 h_fu_184 = 5'd0;
#0 indvar_flatten19_fu_188 = 10'd0;
#0 c_fu_192 = 5'd0;
#0 indvar_flatten32_fu_196 = 13'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) mobilenet_v1_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U563(
    .din0(32'd1077439879),
    .din1(32'd1082234332),
    .din2(32'd1077298945),
    .din3(32'd1078923103),
    .din4(32'd1072444206),
    .din5(32'd1074983760),
    .din6(32'd1059219031),
    .din7(32'd1071581832),
    .din8(32'd1074559288),
    .din9(32'd1072237342),
    .din10(32'd1071884064),
    .din11(32'd1058697531),
    .din12(32'd1079831327),
    .din13(32'd1072616018),
    .din14(32'd1075936175),
    .din15(32'd1079241292),
    .def(tmp_fu_520_p33),
    .sel(trunc_ln36_reg_755_pp0_iter3_reg),
    .dout(tmp_fu_520_p35)
);

(* dissolve_hierarchy = "yes" *) mobilenet_v1_sparsemux_33_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_33_4_32_1_1_U564(
    .din0(32'd1017250849),
    .din1(32'd1032283079),
    .din2(32'd3178884527),
    .din3(32'd3209415395),
    .din4(32'd1069086364),
    .din5(32'd3183355166),
    .din6(32'd1050551950),
    .din7(32'd1073963268),
    .din8(32'd1036949536),
    .din9(32'd1069417207),
    .din10(32'd3195043838),
    .din11(32'd1066092949),
    .din12(32'd1030737656),
    .din13(32'd1072795164),
    .din14(32'd1070833005),
    .din15(32'd3210725917),
    .def(tmp_s_fu_592_p33),
    .sel(trunc_ln36_reg_755_pp0_iter6_reg),
    .dout(tmp_s_fu_592_p35)
);

mobilenet_v1_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_192 <= 5'd0;
        end else if (((icmp_ln35_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            c_fu_192 <= select_ln35_1_fu_350_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            h_fu_184 <= 5'd0;
        end else if (((icmp_ln35_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            h_fu_184 <= select_ln36_fu_382_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_188 <= 10'd0;
        end else if (((icmp_ln35_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten19_fu_188 <= select_ln36_1_fu_416_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten32_fu_196 <= 13'd0;
        end else if (((icmp_ln35_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten32_fu_196 <= add_ln35_1_fu_297_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            w_fu_180 <= 5'd0;
        end else if (((icmp_ln35_fu_291_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            w_fu_180 <= add_ln37_fu_404_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln39_4_reg_788 <= add_ln39_4_fu_514_p2;
        add_ln39_4_reg_788_pp0_iter10_reg <= add_ln39_4_reg_788_pp0_iter9_reg;
        add_ln39_4_reg_788_pp0_iter11_reg <= add_ln39_4_reg_788_pp0_iter10_reg;
        add_ln39_4_reg_788_pp0_iter12_reg <= add_ln39_4_reg_788_pp0_iter11_reg;
        add_ln39_4_reg_788_pp0_iter13_reg <= add_ln39_4_reg_788_pp0_iter12_reg;
        add_ln39_4_reg_788_pp0_iter14_reg <= add_ln39_4_reg_788_pp0_iter13_reg;
        add_ln39_4_reg_788_pp0_iter3_reg <= add_ln39_4_reg_788;
        add_ln39_4_reg_788_pp0_iter4_reg <= add_ln39_4_reg_788_pp0_iter3_reg;
        add_ln39_4_reg_788_pp0_iter5_reg <= add_ln39_4_reg_788_pp0_iter4_reg;
        add_ln39_4_reg_788_pp0_iter6_reg <= add_ln39_4_reg_788_pp0_iter5_reg;
        add_ln39_4_reg_788_pp0_iter7_reg <= add_ln39_4_reg_788_pp0_iter6_reg;
        add_ln39_4_reg_788_pp0_iter8_reg <= add_ln39_4_reg_788_pp0_iter7_reg;
        add_ln39_4_reg_788_pp0_iter9_reg <= add_ln39_4_reg_788_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul_i_reg_808 <= grp_fu_2523_p_dout0;
        ofmap_dw0_load_reg_793 <= ofmap_dw0_q0;
        select_ln4_8_reg_820 <= select_ln4_8_fu_704_p3;
        tmp_s_reg_803 <= tmp_s_fu_592_p35;
        trunc_ln35_reg_774_pp0_iter10_reg <= trunc_ln35_reg_774_pp0_iter9_reg;
        trunc_ln35_reg_774_pp0_iter11_reg <= trunc_ln35_reg_774_pp0_iter10_reg;
        trunc_ln35_reg_774_pp0_iter12_reg <= trunc_ln35_reg_774_pp0_iter11_reg;
        trunc_ln35_reg_774_pp0_iter13_reg <= trunc_ln35_reg_774_pp0_iter12_reg;
        trunc_ln35_reg_774_pp0_iter14_reg <= trunc_ln35_reg_774_pp0_iter13_reg;
        trunc_ln35_reg_774_pp0_iter2_reg <= trunc_ln35_reg_774;
        trunc_ln35_reg_774_pp0_iter3_reg <= trunc_ln35_reg_774_pp0_iter2_reg;
        trunc_ln35_reg_774_pp0_iter4_reg <= trunc_ln35_reg_774_pp0_iter3_reg;
        trunc_ln35_reg_774_pp0_iter5_reg <= trunc_ln35_reg_774_pp0_iter4_reg;
        trunc_ln35_reg_774_pp0_iter6_reg <= trunc_ln35_reg_774_pp0_iter5_reg;
        trunc_ln35_reg_774_pp0_iter7_reg <= trunc_ln35_reg_774_pp0_iter6_reg;
        trunc_ln35_reg_774_pp0_iter8_reg <= trunc_ln35_reg_774_pp0_iter7_reg;
        trunc_ln35_reg_774_pp0_iter9_reg <= trunc_ln35_reg_774_pp0_iter8_reg;
        trunc_ln36_reg_755_pp0_iter2_reg <= trunc_ln36_reg_755;
        trunc_ln36_reg_755_pp0_iter3_reg <= trunc_ln36_reg_755_pp0_iter2_reg;
        trunc_ln36_reg_755_pp0_iter4_reg <= trunc_ln36_reg_755_pp0_iter3_reg;
        trunc_ln36_reg_755_pp0_iter5_reg <= trunc_ln36_reg_755_pp0_iter4_reg;
        trunc_ln36_reg_755_pp0_iter6_reg <= trunc_ln36_reg_755_pp0_iter5_reg;
        x_assign_8_reg_813 <= grp_fu_2467_p_dout0;
        x_assign_8_reg_813_pp0_iter13_reg <= x_assign_8_reg_813;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        lshr_ln_reg_778 <= {{select_ln35_1_fu_350_p3[3:1]}};
        select_ln36_reg_768 <= select_ln36_fu_382_p3;
        trunc_ln35_reg_774 <= trunc_ln35_fu_390_p1;
        trunc_ln36_reg_755 <= trunc_ln36_fu_358_p1;
        w_mid2_reg_762 <= w_mid2_fu_374_p3;
    end
end

always @ (*) begin
    if (((icmp_ln35_fu_291_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        ifmap_pw0_1_ce1_local = 1'b1;
    end else begin
        ifmap_pw0_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln35_reg_774_pp0_iter14_reg == 1'd1))) begin
        ifmap_pw0_1_we1_local = 1'b1;
    end else begin
        ifmap_pw0_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        ifmap_pw0_ce1_local = 1'b1;
    end else begin
        ifmap_pw0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln35_reg_774_pp0_iter14_reg == 1'd0))) begin
        ifmap_pw0_we1_local = 1'b1;
    end else begin
        ifmap_pw0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ofmap_dw0_ce0_local = 1'b1;
    end else begin
        ofmap_dw0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln35_1_fu_297_p2 = (indvar_flatten32_fu_196 + 13'd1);

assign add_ln35_fu_312_p2 = (c_fu_192 + 5'd1);

assign add_ln36_1_fu_410_p2 = (indvar_flatten19_fu_188 + 10'd1);

assign add_ln36_fu_362_p2 = (select_ln35_fu_324_p3 + 5'd1);

assign add_ln37_fu_404_p2 = (w_mid2_fu_374_p3 + 5'd1);

assign add_ln39_2_fu_483_p2 = (tmp_125_fu_456_p3 + zext_ln39_fu_463_p1);

assign add_ln39_3_fu_503_p2 = (tmp_67_fu_475_p3 + zext_ln39_3_fu_500_p1);

assign add_ln39_4_fu_514_p2 = (tmp_68_fu_489_p3 + zext_ln39_2_fu_497_p1);

assign add_ln39_fu_469_p2 = (tmp_124_fu_449_p3 + zext_ln39_1_fu_466_p1);

assign and_ln35_fu_344_p2 = (xor_ln35_fu_332_p2 & icmp_ln37_fu_338_p2);

assign and_ln4_8_fu_698_p2 = (or_ln4_8_fu_692_p2 & grp_fu_2599_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln4_8_fu_663_p1 = x_assign_8_reg_813_pp0_iter13_reg;

assign empty_fu_368_p2 = (icmp_ln36_fu_318_p2 | and_ln35_fu_344_p2);

assign grp_fu_2467_p_ce = 1'b1;

assign grp_fu_2467_p_din0 = mul_i_reg_808;

assign grp_fu_2467_p_din1 = tmp_s_reg_803;

assign grp_fu_2467_p_opcode = 2'd0;

assign grp_fu_2523_p_ce = 1'b1;

assign grp_fu_2523_p_din0 = ofmap_dw0_load_reg_793;

assign grp_fu_2523_p_din1 = tmp_fu_520_p35;

assign grp_fu_2599_p_ce = 1'b1;

assign grp_fu_2599_p_din0 = x_assign_8_reg_813;

assign grp_fu_2599_p_din1 = 32'd0;

assign grp_fu_2599_p_opcode = 5'd2;

assign icmp_ln35_fu_291_p2 = ((indvar_flatten32_fu_196 == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln36_fu_318_p2 = ((indvar_flatten19_fu_188 == 10'd256) ? 1'b1 : 1'b0);

assign icmp_ln37_fu_338_p2 = ((w_fu_180 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln4_16_fu_680_p2 = ((tmp_17_fu_666_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln4_17_fu_686_p2 = ((trunc_ln4_fu_676_p1 == 23'd0) ? 1'b1 : 1'b0);

assign ifmap_pw0_1_address1 = zext_ln39_5_fu_711_p1;

assign ifmap_pw0_1_ce1 = ifmap_pw0_1_ce1_local;

assign ifmap_pw0_1_d1 = select_ln4_8_reg_820;

assign ifmap_pw0_1_we1 = ifmap_pw0_1_we1_local;

assign ifmap_pw0_address1 = zext_ln39_5_fu_711_p1;

assign ifmap_pw0_ce1 = ifmap_pw0_ce1_local;

assign ifmap_pw0_d1 = select_ln4_8_reg_820;

assign ifmap_pw0_we1 = ifmap_pw0_we1_local;

assign ofmap_dw0_address0 = zext_ln39_4_fu_509_p1;

assign ofmap_dw0_ce0 = ofmap_dw0_ce0_local;

assign or_ln4_8_fu_692_p2 = (icmp_ln4_17_fu_686_p2 | icmp_ln4_16_fu_680_p2);

assign select_ln35_1_fu_350_p3 = ((icmp_ln36_fu_318_p2[0:0] == 1'b1) ? add_ln35_fu_312_p2 : c_fu_192);

assign select_ln35_fu_324_p3 = ((icmp_ln36_fu_318_p2[0:0] == 1'b1) ? 5'd0 : h_fu_184);

assign select_ln36_1_fu_416_p3 = ((icmp_ln36_fu_318_p2[0:0] == 1'b1) ? 10'd1 : add_ln36_1_fu_410_p2);

assign select_ln36_fu_382_p3 = ((and_ln35_fu_344_p2[0:0] == 1'b1) ? add_ln36_fu_362_p2 : select_ln35_fu_324_p3);

assign select_ln4_8_fu_704_p3 = ((and_ln4_8_fu_698_p2[0:0] == 1'b1) ? x_assign_8_reg_813_pp0_iter13_reg : 32'd0);

assign tmp_124_fu_449_p3 = {{trunc_ln36_reg_755}, {4'd0}};

assign tmp_125_fu_456_p3 = {{lshr_ln_reg_778}, {4'd0}};

assign tmp_17_fu_666_p4 = {{bitcast_ln4_8_fu_663_p1[30:23]}};

assign tmp_67_fu_475_p3 = {{add_ln39_fu_469_p2}, {4'd0}};

assign tmp_68_fu_489_p3 = {{add_ln39_2_fu_483_p2}, {4'd0}};

assign tmp_fu_520_p33 = 'bx;

assign tmp_s_fu_592_p33 = 'bx;

assign trunc_ln35_fu_390_p1 = select_ln35_1_fu_350_p3[0:0];

assign trunc_ln36_fu_358_p1 = select_ln35_1_fu_350_p3[3:0];

assign trunc_ln4_fu_676_p1 = bitcast_ln4_8_fu_663_p1[22:0];

assign w_mid2_fu_374_p3 = ((empty_fu_368_p2[0:0] == 1'b1) ? 5'd0 : w_fu_180);

assign xor_ln35_fu_332_p2 = (icmp_ln36_fu_318_p2 ^ 1'd1);

assign zext_ln39_1_fu_466_p1 = select_ln36_reg_768;

assign zext_ln39_2_fu_497_p1 = w_mid2_reg_762;

assign zext_ln39_3_fu_500_p1 = w_mid2_reg_762;

assign zext_ln39_4_fu_509_p1 = add_ln39_3_fu_503_p2;

assign zext_ln39_5_fu_711_p1 = add_ln39_4_reg_788_pp0_iter14_reg;

assign zext_ln39_fu_463_p1 = select_ln36_reg_768;

endmodule //mobilenet_v1_mobilenet_v1_Pipeline_BN_DW0_C_BN_DW0_H_BN_DW0_W
