// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_qat_mobilenet_v1_qat_Pipeline_LOAD_IC_LOAD_IH_LOAD_IW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY,
        m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID,
        m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA,
        m_axi_gmem_0_RLAST,
        m_axi_gmem_0_RID,
        m_axi_gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER,
        m_axi_gmem_0_RRESP,
        m_axi_gmem_0_BVALID,
        m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP,
        m_axi_gmem_0_BID,
        m_axi_gmem_0_BUSER,
        sext_ln11,
        in_buf_address0,
        in_buf_ce0,
        in_buf_we0,
        in_buf_d0,
        in_buf_1_address0,
        in_buf_1_ce0,
        in_buf_1_we0,
        in_buf_1_d0,
        in_buf_2_address0,
        in_buf_2_ce0,
        in_buf_2_we0,
        in_buf_2_d0,
        in_buf_3_address0,
        in_buf_3_ce0,
        in_buf_3_we0,
        in_buf_3_d0,
        in_buf_4_address0,
        in_buf_4_ce0,
        in_buf_4_we0,
        in_buf_4_d0,
        in_buf_5_address0,
        in_buf_5_ce0,
        in_buf_5_we0,
        in_buf_5_d0,
        in_buf_6_address0,
        in_buf_6_ce0,
        in_buf_6_we0,
        in_buf_6_d0,
        in_buf_7_address0,
        in_buf_7_ce0,
        in_buf_7_we0,
        in_buf_7_d0,
        in_buf_8_address0,
        in_buf_8_ce0,
        in_buf_8_we0,
        in_buf_8_d0,
        in_buf_9_address0,
        in_buf_9_ce0,
        in_buf_9_we0,
        in_buf_9_d0,
        in_buf_10_address0,
        in_buf_10_ce0,
        in_buf_10_we0,
        in_buf_10_d0,
        in_buf_11_address0,
        in_buf_11_ce0,
        in_buf_11_we0,
        in_buf_11_d0,
        in_buf_12_address0,
        in_buf_12_ce0,
        in_buf_12_we0,
        in_buf_12_d0,
        in_buf_13_address0,
        in_buf_13_ce0,
        in_buf_13_we0,
        in_buf_13_d0,
        in_buf_14_address0,
        in_buf_14_ce0,
        in_buf_14_we0,
        in_buf_14_d0,
        in_buf_15_address0,
        in_buf_15_ce0,
        in_buf_15_we0,
        in_buf_15_d0,
        in_buf_16_address0,
        in_buf_16_ce0,
        in_buf_16_we0,
        in_buf_16_d0,
        in_buf_17_address0,
        in_buf_17_ce0,
        in_buf_17_we0,
        in_buf_17_d0,
        in_buf_18_address0,
        in_buf_18_ce0,
        in_buf_18_we0,
        in_buf_18_d0,
        in_buf_19_address0,
        in_buf_19_ce0,
        in_buf_19_we0,
        in_buf_19_d0,
        in_buf_20_address0,
        in_buf_20_ce0,
        in_buf_20_we0,
        in_buf_20_d0,
        in_buf_21_address0,
        in_buf_21_ce0,
        in_buf_21_we0,
        in_buf_21_d0,
        in_buf_22_address0,
        in_buf_22_ce0,
        in_buf_22_we0,
        in_buf_22_d0,
        in_buf_23_address0,
        in_buf_23_ce0,
        in_buf_23_we0,
        in_buf_23_d0,
        in_buf_24_address0,
        in_buf_24_ce0,
        in_buf_24_we0,
        in_buf_24_d0,
        in_buf_25_address0,
        in_buf_25_ce0,
        in_buf_25_we0,
        in_buf_25_d0,
        in_buf_26_address0,
        in_buf_26_ce0,
        in_buf_26_we0,
        in_buf_26_d0,
        grp_fu_1113_p_din0,
        grp_fu_1113_p_din1,
        grp_fu_1113_p_dout0,
        grp_fu_1113_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_0_AWVALID;
input   m_axi_gmem_0_AWREADY;
output  [63:0] m_axi_gmem_0_AWADDR;
output  [0:0] m_axi_gmem_0_AWID;
output  [31:0] m_axi_gmem_0_AWLEN;
output  [2:0] m_axi_gmem_0_AWSIZE;
output  [1:0] m_axi_gmem_0_AWBURST;
output  [1:0] m_axi_gmem_0_AWLOCK;
output  [3:0] m_axi_gmem_0_AWCACHE;
output  [2:0] m_axi_gmem_0_AWPROT;
output  [3:0] m_axi_gmem_0_AWQOS;
output  [3:0] m_axi_gmem_0_AWREGION;
output  [0:0] m_axi_gmem_0_AWUSER;
output   m_axi_gmem_0_WVALID;
input   m_axi_gmem_0_WREADY;
output  [31:0] m_axi_gmem_0_WDATA;
output  [3:0] m_axi_gmem_0_WSTRB;
output   m_axi_gmem_0_WLAST;
output  [0:0] m_axi_gmem_0_WID;
output  [0:0] m_axi_gmem_0_WUSER;
output   m_axi_gmem_0_ARVALID;
input   m_axi_gmem_0_ARREADY;
output  [63:0] m_axi_gmem_0_ARADDR;
output  [0:0] m_axi_gmem_0_ARID;
output  [31:0] m_axi_gmem_0_ARLEN;
output  [2:0] m_axi_gmem_0_ARSIZE;
output  [1:0] m_axi_gmem_0_ARBURST;
output  [1:0] m_axi_gmem_0_ARLOCK;
output  [3:0] m_axi_gmem_0_ARCACHE;
output  [2:0] m_axi_gmem_0_ARPROT;
output  [3:0] m_axi_gmem_0_ARQOS;
output  [3:0] m_axi_gmem_0_ARREGION;
output  [0:0] m_axi_gmem_0_ARUSER;
input   m_axi_gmem_0_RVALID;
output   m_axi_gmem_0_RREADY;
input  [31:0] m_axi_gmem_0_RDATA;
input   m_axi_gmem_0_RLAST;
input  [0:0] m_axi_gmem_0_RID;
input  [8:0] m_axi_gmem_0_RFIFONUM;
input  [0:0] m_axi_gmem_0_RUSER;
input  [1:0] m_axi_gmem_0_RRESP;
input   m_axi_gmem_0_BVALID;
output   m_axi_gmem_0_BREADY;
input  [1:0] m_axi_gmem_0_BRESP;
input  [0:0] m_axi_gmem_0_BID;
input  [0:0] m_axi_gmem_0_BUSER;
input  [61:0] sext_ln11;
output  [6:0] in_buf_address0;
output   in_buf_ce0;
output   in_buf_we0;
output  [7:0] in_buf_d0;
output  [6:0] in_buf_1_address0;
output   in_buf_1_ce0;
output   in_buf_1_we0;
output  [7:0] in_buf_1_d0;
output  [6:0] in_buf_2_address0;
output   in_buf_2_ce0;
output   in_buf_2_we0;
output  [7:0] in_buf_2_d0;
output  [6:0] in_buf_3_address0;
output   in_buf_3_ce0;
output   in_buf_3_we0;
output  [7:0] in_buf_3_d0;
output  [6:0] in_buf_4_address0;
output   in_buf_4_ce0;
output   in_buf_4_we0;
output  [7:0] in_buf_4_d0;
output  [6:0] in_buf_5_address0;
output   in_buf_5_ce0;
output   in_buf_5_we0;
output  [7:0] in_buf_5_d0;
output  [6:0] in_buf_6_address0;
output   in_buf_6_ce0;
output   in_buf_6_we0;
output  [7:0] in_buf_6_d0;
output  [6:0] in_buf_7_address0;
output   in_buf_7_ce0;
output   in_buf_7_we0;
output  [7:0] in_buf_7_d0;
output  [6:0] in_buf_8_address0;
output   in_buf_8_ce0;
output   in_buf_8_we0;
output  [7:0] in_buf_8_d0;
output  [6:0] in_buf_9_address0;
output   in_buf_9_ce0;
output   in_buf_9_we0;
output  [7:0] in_buf_9_d0;
output  [6:0] in_buf_10_address0;
output   in_buf_10_ce0;
output   in_buf_10_we0;
output  [7:0] in_buf_10_d0;
output  [6:0] in_buf_11_address0;
output   in_buf_11_ce0;
output   in_buf_11_we0;
output  [7:0] in_buf_11_d0;
output  [6:0] in_buf_12_address0;
output   in_buf_12_ce0;
output   in_buf_12_we0;
output  [7:0] in_buf_12_d0;
output  [6:0] in_buf_13_address0;
output   in_buf_13_ce0;
output   in_buf_13_we0;
output  [7:0] in_buf_13_d0;
output  [6:0] in_buf_14_address0;
output   in_buf_14_ce0;
output   in_buf_14_we0;
output  [7:0] in_buf_14_d0;
output  [6:0] in_buf_15_address0;
output   in_buf_15_ce0;
output   in_buf_15_we0;
output  [7:0] in_buf_15_d0;
output  [6:0] in_buf_16_address0;
output   in_buf_16_ce0;
output   in_buf_16_we0;
output  [7:0] in_buf_16_d0;
output  [6:0] in_buf_17_address0;
output   in_buf_17_ce0;
output   in_buf_17_we0;
output  [7:0] in_buf_17_d0;
output  [6:0] in_buf_18_address0;
output   in_buf_18_ce0;
output   in_buf_18_we0;
output  [7:0] in_buf_18_d0;
output  [6:0] in_buf_19_address0;
output   in_buf_19_ce0;
output   in_buf_19_we0;
output  [7:0] in_buf_19_d0;
output  [6:0] in_buf_20_address0;
output   in_buf_20_ce0;
output   in_buf_20_we0;
output  [7:0] in_buf_20_d0;
output  [6:0] in_buf_21_address0;
output   in_buf_21_ce0;
output   in_buf_21_we0;
output  [7:0] in_buf_21_d0;
output  [6:0] in_buf_22_address0;
output   in_buf_22_ce0;
output   in_buf_22_we0;
output  [7:0] in_buf_22_d0;
output  [6:0] in_buf_23_address0;
output   in_buf_23_ce0;
output   in_buf_23_we0;
output  [7:0] in_buf_23_d0;
output  [6:0] in_buf_24_address0;
output   in_buf_24_ce0;
output   in_buf_24_we0;
output  [7:0] in_buf_24_d0;
output  [6:0] in_buf_25_address0;
output   in_buf_25_ce0;
output   in_buf_25_we0;
output  [7:0] in_buf_25_d0;
output  [6:0] in_buf_26_address0;
output   in_buf_26_ce0;
output   in_buf_26_we0;
output  [7:0] in_buf_26_d0;
output  [31:0] grp_fu_1113_p_din0;
output  [31:0] grp_fu_1113_p_din1;
input  [31:0] grp_fu_1113_p_dout0;
output   grp_fu_1113_p_ce;

reg ap_idle;
reg m_axi_gmem_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln11_fu_660_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [4:0] mask_table_address0;
wire   [22:0] mask_table_q0;
wire   [4:0] one_half_table_address0;
wire   [23:0] one_half_table_q0;
reg    gmem_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln12_fu_681_p2;
reg   [0:0] icmp_ln12_reg_1304;
wire   [1:0] select_ln11_1_fu_687_p3;
reg   [1:0] select_ln11_1_reg_1311;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter1_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter2_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter3_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter4_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter5_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter6_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter7_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter8_reg;
reg   [1:0] select_ln11_1_reg_1311_pp0_iter9_reg;
wire   [5:0] iw_mid2_fu_773_p3;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
wire   [5:0] select_ln12_fu_781_p3;
reg   [4:0] tmp_reg_1325;
reg   [4:0] tmp_150_reg_1330;
reg   [4:0] tmp_150_reg_1330_pp0_iter2_reg;
reg   [4:0] tmp_150_reg_1330_pp0_iter3_reg;
reg   [31:0] gmem_addr_read_reg_1340;
wire   [31:0] bitcast_ln15_fu_869_p1;
wire   [6:0] grp_fu_1252_p3;
reg   [6:0] add_ln19_reg_1355;
reg   [6:0] add_ln19_reg_1355_pp0_iter6_reg;
reg   [6:0] add_ln19_reg_1355_pp0_iter7_reg;
reg   [6:0] add_ln19_reg_1355_pp0_iter8_reg;
reg   [6:0] add_ln19_reg_1355_pp0_iter9_reg;
reg   [31:0] val_reg_1360;
wire   [31:0] data_3_fu_873_p1;
reg   [31:0] data_3_reg_1365;
wire   [0:0] icmp_ln167_fu_885_p2;
reg   [0:0] icmp_ln167_reg_1370;
reg   [0:0] tmp_151_reg_1376;
wire   [0:0] icmp_ln170_fu_899_p2;
reg   [0:0] icmp_ln170_reg_1381;
reg   [0:0] xs_sign_reg_1396;
wire   [22:0] trunc_ln342_fu_1035_p1;
reg   [22:0] trunc_ln342_reg_1401;
wire   [8:0] add_ln317_fu_1043_p2;
reg   [8:0] add_ln317_reg_1406;
reg   [0:0] tmp_153_reg_1411;
wire   [7:0] sub_ln18_fu_1057_p2;
reg   [7:0] sub_ln18_reg_1417;
wire   [31:0] result_fu_1138_p3;
reg   [31:0] result_reg_1422;
reg   [24:0] tmp_154_reg_1427;
wire   [63:0] zext_ln179_fu_915_p1;
wire    ap_block_pp0_stage0_grp0;
wire   [63:0] zext_ln19_1_fu_1160_p1;
reg   [5:0] iw_fu_198;
wire   [5:0] add_ln13_fu_841_p2;
wire    ap_loop_init;
reg   [5:0] ih_fu_202;
reg   [11:0] indvar_flatten_fu_206;
wire   [11:0] select_ln12_1_fu_709_p3;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0;
reg   [1:0] ic_fu_210;
reg   [1:0] ap_sig_allocacmp_ic_load;
reg   [11:0] indvar_flatten12_fu_214;
wire   [11:0] add_ln11_1_fu_666_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    mask_table_ce0_local;
reg    one_half_table_ce0_local;
reg    in_buf_13_we0_local;
wire   [1:0] trunc_ln12_fu_1155_p1;
wire   [1:0] trunc_ln10_fu_1190_p1;
wire   [7:0] select_ln19_fu_1217_p3;
reg    in_buf_13_ce0_local;
reg    in_buf_12_we0_local;
reg    in_buf_12_ce0_local;
reg    in_buf_14_we0_local;
reg    in_buf_14_ce0_local;
reg    in_buf_10_we0_local;
reg    in_buf_10_ce0_local;
reg    in_buf_9_we0_local;
reg    in_buf_9_ce0_local;
reg    in_buf_11_we0_local;
reg    in_buf_11_ce0_local;
reg    in_buf_16_we0_local;
reg    in_buf_16_ce0_local;
reg    in_buf_15_we0_local;
reg    in_buf_15_ce0_local;
reg    in_buf_17_we0_local;
reg    in_buf_17_ce0_local;
reg    in_buf_4_we0_local;
reg    in_buf_4_ce0_local;
reg    in_buf_3_we0_local;
reg    in_buf_3_ce0_local;
reg    in_buf_5_we0_local;
reg    in_buf_5_ce0_local;
reg    in_buf_1_we0_local;
reg    in_buf_1_ce0_local;
reg    in_buf_we0_local;
reg    in_buf_ce0_local;
reg    in_buf_2_we0_local;
reg    in_buf_2_ce0_local;
reg    in_buf_7_we0_local;
reg    in_buf_7_ce0_local;
reg    in_buf_6_we0_local;
reg    in_buf_6_ce0_local;
reg    in_buf_8_we0_local;
reg    in_buf_8_ce0_local;
reg    in_buf_22_we0_local;
reg    in_buf_22_ce0_local;
reg    in_buf_21_we0_local;
reg    in_buf_21_ce0_local;
reg    in_buf_23_we0_local;
reg    in_buf_23_ce0_local;
reg    in_buf_19_we0_local;
reg    in_buf_19_ce0_local;
reg    in_buf_18_we0_local;
reg    in_buf_18_ce0_local;
reg    in_buf_20_we0_local;
reg    in_buf_20_ce0_local;
reg    in_buf_25_we0_local;
reg    in_buf_25_ce0_local;
reg    in_buf_24_we0_local;
reg    in_buf_24_ce0_local;
reg    in_buf_26_we0_local;
reg    in_buf_26_ce0_local;
wire   [1:0] add_ln11_fu_675_p2;
wire   [11:0] add_ln12_1_fu_703_p2;
wire   [0:0] icmp_ln13_fu_750_p2;
wire   [0:0] xor_ln11_fu_745_p2;
wire   [5:0] select_ln11_fu_738_p3;
wire   [0:0] and_ln11_fu_756_p2;
wire   [0:0] empty_fu_768_p2;
wire   [5:0] add_ln12_fu_762_p2;
wire   [5:0] mul_ln12_fu_793_p0;
wire   [7:0] mul_ln12_fu_793_p1;
wire   [12:0] mul_ln12_fu_793_p2;
wire   [2:0] grp_fu_809_p1;
wire   [5:0] mul_ln10_fu_819_p0;
wire   [7:0] mul_ln10_fu_819_p1;
wire   [12:0] mul_ln10_fu_819_p2;
wire   [2:0] grp_fu_835_p1;
wire   [7:0] xs_exp_1_fu_877_p3;
wire   [4:0] index_fu_905_p4;
wire   [31:0] t_fu_921_p3;
wire   [31:0] zext_ln175_fu_932_p1;
wire   [31:0] data_2_fu_936_p2;
wire   [22:0] trunc_ln301_fu_941_p1;
wire   [22:0] xor_ln184_fu_945_p2;
wire   [8:0] tmp_1_i_fu_957_p4;
wire   [22:0] xs_sig_fu_951_p2;
wire   [31:0] t_2_fu_967_p3;
wire   [0:0] xor_ln167_fu_979_p2;
wire   [0:0] and_ln170_fu_984_p2;
wire   [31:0] dc_1_fu_996_p2;
wire   [31:0] dc_1_fu_996_p6;
wire   [31:0] dc_1_fu_996_p7;
wire   [1:0] dc_1_fu_996_p8;
wire   [31:0] dc_1_fu_996_p9;
wire   [31:0] data_fu_1015_p1;
wire   [7:0] xs_exp_fu_1027_p3;
wire   [8:0] zext_ln317_fu_1039_p1;
wire   [24:0] mantissa_fu_1063_p4;
wire  signed [8:0] sext_ln18_fu_1076_p1;
wire   [8:0] select_ln18_fu_1079_p3;
wire  signed [31:0] sext_ln18_1_fu_1085_p1;
wire   [78:0] zext_ln15_fu_1072_p1;
wire   [78:0] zext_ln18_fu_1089_p1;
wire   [78:0] lshr_ln18_fu_1093_p2;
wire   [78:0] shl_ln18_fu_1099_p2;
wire   [31:0] tmp_s_fu_1105_p4;
wire   [31:0] tmp_144_fu_1115_p4;
wire   [31:0] val_1_fu_1125_p3;
wire   [31:0] result_2_fu_1132_p2;
wire   [1:0] grp_fu_809_p2;
wire   [1:0] grp_fu_835_p2;
wire   [0:0] icmp_ln17_fu_1195_p2;
wire   [31:0] r_1_fu_1200_p3;
wire   [0:0] icmp_ln18_fu_1207_p2;
wire   [7:0] trunc_ln19_fu_1213_p1;
wire   [4:0] grp_fu_1252_p0;
wire   [3:0] grp_fu_1252_p1;
wire   [4:0] grp_fu_1252_p2;
reg    grp_fu_606_ce;
reg    grp_fu_809_ce;
reg    grp_fu_835_ce;
reg    grp_fu_1252_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [6:0] grp_fu_1252_p00;
wire   [6:0] grp_fu_1252_p20;
wire   [12:0] mul_ln10_fu_819_p00;
wire   [12:0] mul_ln12_fu_793_p00;
reg    ap_condition_386;
wire  signed [1:0] dc_1_fu_996_p1;
wire   [1:0] dc_1_fu_996_p3;
wire   [1:0] dc_1_fu_996_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 iw_fu_198 = 6'd0;
#0 ih_fu_202 = 6'd0;
#0 indvar_flatten_fu_206 = 12'd0;
#0 ic_fu_210 = 2'd0;
#0 indvar_flatten12_fu_214 = 12'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_v1_qat_mobilenet_v1_qat_Pipeline_LOAD_IC_LOAD_IH_LOAD_IW_mask_table_ROM_AUTO_1R #(
    .DataWidth( 23 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
mask_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mask_table_address0),
    .ce0(mask_table_ce0_local),
    .q0(mask_table_q0)
);

mobilenet_v1_qat_mobilenet_v1_qat_Pipeline_LOAD_IC_LOAD_IH_LOAD_IW_one_half_table_ROM_AUTO_1R #(
    .DataWidth( 24 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
one_half_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(one_half_table_address0),
    .ce0(one_half_table_ce0_local),
    .q0(one_half_table_q0)
);

mobilenet_v1_qat_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U2(
    .din0(mul_ln12_fu_793_p0),
    .din1(mul_ln12_fu_793_p1),
    .dout(mul_ln12_fu_793_p2)
);

mobilenet_v1_qat_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln12_fu_781_p3),
    .din1(grp_fu_809_p1),
    .ce(grp_fu_809_ce),
    .dout(grp_fu_809_p2)
);

mobilenet_v1_qat_mul_6ns_8ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 13 ))
mul_6ns_8ns_13_1_1_U4(
    .din0(mul_ln10_fu_819_p0),
    .din1(mul_ln10_fu_819_p1),
    .dout(mul_ln10_fu_819_p2)
);

mobilenet_v1_qat_urem_6ns_3ns_2_10_1 #(
    .ID( 1 ),
    .NUM_STAGE( 10 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_6ns_3ns_2_10_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(iw_mid2_fu_773_p3),
    .din1(grp_fu_835_p1),
    .ce(grp_fu_835_ce),
    .dout(grp_fu_835_p2)
);

(* dissolve_hierarchy = "yes" *) mobilenet_v1_qat_sparsemux_7_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 32 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
sparsemux_7_2_32_1_1_U6(
    .din0(dc_1_fu_996_p2),
    .din1(val_reg_1360),
    .din2(dc_1_fu_996_p6),
    .def(dc_1_fu_996_p7),
    .sel(dc_1_fu_996_p8),
    .dout(dc_1_fu_996_p9)
);

mobilenet_v1_qat_mac_muladd_5ns_4ns_5ns_7_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 5 ),
    .dout_WIDTH( 7 ))
mac_muladd_5ns_4ns_5ns_7_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1252_p0),
    .din1(grp_fu_1252_p1),
    .din2(grp_fu_1252_p2),
    .ce(grp_fu_1252_ce),
    .dout(grp_fu_1252_p3)
);

mobilenet_v1_qat_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln11_fu_660_p2 == 1'd0))) begin
            ic_fu_210 <= select_ln11_1_fu_687_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_210 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_386)) begin
        if ((ap_loop_init == 1'b1)) begin
            ih_fu_202 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ih_fu_202 <= select_ln12_fu_781_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln11_fu_660_p2 == 1'd0))) begin
            indvar_flatten12_fu_214 <= add_ln11_1_fu_666_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_214 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln11_fu_660_p2 == 1'd0))) begin
            indvar_flatten_fu_206 <= select_ln12_1_fu_709_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_206 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_386)) begin
        if ((ap_loop_init == 1'b1)) begin
            iw_fu_198 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            iw_fu_198 <= add_ln13_fu_841_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln19_reg_1355 <= grp_fu_1252_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        add_ln19_reg_1355_pp0_iter6_reg <= add_ln19_reg_1355;
        add_ln19_reg_1355_pp0_iter7_reg <= add_ln19_reg_1355_pp0_iter6_reg;
        add_ln19_reg_1355_pp0_iter8_reg <= add_ln19_reg_1355_pp0_iter7_reg;
        add_ln19_reg_1355_pp0_iter9_reg <= add_ln19_reg_1355_pp0_iter8_reg;
        add_ln317_reg_1406 <= add_ln317_fu_1043_p2;
        data_3_reg_1365 <= data_3_fu_873_p1;
        icmp_ln167_reg_1370 <= icmp_ln167_fu_885_p2;
        icmp_ln170_reg_1381 <= icmp_ln170_fu_899_p2;
        result_reg_1422 <= result_fu_1138_p3;
        sub_ln18_reg_1417 <= sub_ln18_fu_1057_p2;
        tmp_150_reg_1330_pp0_iter2_reg <= tmp_150_reg_1330;
        tmp_150_reg_1330_pp0_iter3_reg <= tmp_150_reg_1330_pp0_iter2_reg;
        tmp_151_reg_1376 <= data_3_fu_873_p1[32'd31];
        tmp_153_reg_1411 <= add_ln317_fu_1043_p2[32'd8];
        tmp_154_reg_1427 <= {{result_fu_1138_p3[31:7]}};
        trunc_ln342_reg_1401 <= trunc_ln342_fu_1035_p1;
        val_reg_1360 <= grp_fu_1113_p_dout0;
        xs_sign_reg_1396 <= data_fu_1015_p1[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln12_reg_1304 <= icmp_ln12_fu_681_p2;
        select_ln11_1_reg_1311 <= select_ln11_1_fu_687_p3;
        select_ln11_1_reg_1311_pp0_iter1_reg <= select_ln11_1_reg_1311;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        select_ln11_1_reg_1311_pp0_iter2_reg <= select_ln11_1_reg_1311_pp0_iter1_reg;
        select_ln11_1_reg_1311_pp0_iter3_reg <= select_ln11_1_reg_1311_pp0_iter2_reg;
        select_ln11_1_reg_1311_pp0_iter4_reg <= select_ln11_1_reg_1311_pp0_iter3_reg;
        select_ln11_1_reg_1311_pp0_iter5_reg <= select_ln11_1_reg_1311_pp0_iter4_reg;
        select_ln11_1_reg_1311_pp0_iter6_reg <= select_ln11_1_reg_1311_pp0_iter5_reg;
        select_ln11_1_reg_1311_pp0_iter7_reg <= select_ln11_1_reg_1311_pp0_iter6_reg;
        select_ln11_1_reg_1311_pp0_iter8_reg <= select_ln11_1_reg_1311_pp0_iter7_reg;
        select_ln11_1_reg_1311_pp0_iter9_reg <= select_ln11_1_reg_1311_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001_grp1)) begin
        gmem_addr_read_reg_1340 <= m_axi_gmem_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        tmp_150_reg_1330 <= {{mul_ln10_fu_819_p2[12:8]}};
        tmp_reg_1325 <= {{mul_ln12_fu_793_p2[12:8]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln11_fu_660_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter9_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_ic_load = 2'd0;
    end else begin
        ap_sig_allocacmp_ic_load = ic_fu_210;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_214;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_206;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_grp1))) begin
        gmem_blk_n_R = m_axi_gmem_0_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_1252_ce = 1'b1;
    end else begin
        grp_fu_1252_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_606_ce = 1'b1;
    end else begin
        grp_fu_606_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_809_ce = 1'b1;
    end else begin
        grp_fu_809_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        grp_fu_835_ce = 1'b1;
    end else begin
        grp_fu_835_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_10_ce0_local = 1'b1;
    end else begin
        in_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_10_we0_local = 1'b1;
    end else begin
        in_buf_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_11_ce0_local = 1'b1;
    end else begin
        in_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_11_we0_local = 1'b1;
    end else begin
        in_buf_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_12_ce0_local = 1'b1;
    end else begin
        in_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd0) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_12_we0_local = 1'b1;
    end else begin
        in_buf_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_13_ce0_local = 1'b1;
    end else begin
        in_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_13_we0_local = 1'b1;
    end else begin
        in_buf_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_14_ce0_local = 1'b1;
    end else begin
        in_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_14_we0_local = 1'b1;
    end else begin
        in_buf_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_15_ce0_local = 1'b1;
    end else begin
        in_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_15_we0_local = 1'b1;
    end else begin
        in_buf_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_16_ce0_local = 1'b1;
    end else begin
        in_buf_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_16_we0_local = 1'b1;
    end else begin
        in_buf_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_17_ce0_local = 1'b1;
    end else begin
        in_buf_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_17_we0_local = 1'b1;
    end else begin
        in_buf_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_18_ce0_local = 1'b1;
    end else begin
        in_buf_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd0) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_18_we0_local = 1'b1;
    end else begin
        in_buf_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_19_ce0_local = 1'b1;
    end else begin
        in_buf_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_19_we0_local = 1'b1;
    end else begin
        in_buf_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_1_ce0_local = 1'b1;
    end else begin
        in_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_1_we0_local = 1'b1;
    end else begin
        in_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_20_ce0_local = 1'b1;
    end else begin
        in_buf_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_20_we0_local = 1'b1;
    end else begin
        in_buf_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_21_ce0_local = 1'b1;
    end else begin
        in_buf_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd0) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_21_we0_local = 1'b1;
    end else begin
        in_buf_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_22_ce0_local = 1'b1;
    end else begin
        in_buf_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_22_we0_local = 1'b1;
    end else begin
        in_buf_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_23_ce0_local = 1'b1;
    end else begin
        in_buf_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_23_we0_local = 1'b1;
    end else begin
        in_buf_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_24_ce0_local = 1'b1;
    end else begin
        in_buf_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_24_we0_local = 1'b1;
    end else begin
        in_buf_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_25_ce0_local = 1'b1;
    end else begin
        in_buf_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_25_we0_local = 1'b1;
    end else begin
        in_buf_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_26_ce0_local = 1'b1;
    end else begin
        in_buf_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & ~(select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_26_we0_local = 1'b1;
    end else begin
        in_buf_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_2_ce0_local = 1'b1;
    end else begin
        in_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_2_we0_local = 1'b1;
    end else begin
        in_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_3_ce0_local = 1'b1;
    end else begin
        in_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd0) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_3_we0_local = 1'b1;
    end else begin
        in_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_4_ce0_local = 1'b1;
    end else begin
        in_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_4_we0_local = 1'b1;
    end else begin
        in_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_5_ce0_local = 1'b1;
    end else begin
        in_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & (trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_5_we0_local = 1'b1;
    end else begin
        in_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_6_ce0_local = 1'b1;
    end else begin
        in_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_6_we0_local = 1'b1;
    end else begin
        in_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_7_ce0_local = 1'b1;
    end else begin
        in_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & (trunc_ln10_fu_1190_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_7_we0_local = 1'b1;
    end else begin
        in_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_8_ce0_local = 1'b1;
    end else begin
        in_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln12_fu_1155_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd0) & ~(trunc_ln10_fu_1190_p1 == 2'd1) & ~(trunc_ln12_fu_1155_p1 == 2'd1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_8_we0_local = 1'b1;
    end else begin
        in_buf_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_9_ce0_local = 1'b1;
    end else begin
        in_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd0) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_9_we0_local = 1'b1;
    end else begin
        in_buf_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_ce0_local = 1'b1;
    end else begin
        in_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln10_fu_1190_p1 == 2'd0) & (trunc_ln12_fu_1155_p1 == 2'd0) & (ap_enable_reg_pp0_iter10 == 1'b1) & (select_ln11_1_reg_1311_pp0_iter9_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        in_buf_we0_local = 1'b1;
    end else begin
        in_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        m_axi_gmem_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        mask_table_ce0_local = 1'b1;
    end else begin
        mask_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        one_half_table_ce0_local = 1'b1;
    end else begin
        one_half_table_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln11_1_fu_666_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 12'd1);

assign add_ln11_fu_675_p2 = (ap_sig_allocacmp_ic_load + 2'd1);

assign add_ln12_1_fu_703_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln12_fu_762_p2 = (select_ln11_fu_738_p3 + 6'd1);

assign add_ln13_fu_841_p2 = (iw_mid2_fu_773_p3 + 6'd1);

assign add_ln317_fu_1043_p2 = ($signed(zext_ln317_fu_1039_p1) + $signed(9'd385));

assign and_ln11_fu_756_p2 = (xor_ln11_fu_745_p2 & icmp_ln13_fu_750_p2);

assign and_ln170_fu_984_p2 = (xor_ln167_fu_979_p2 & icmp_ln170_reg_1381);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_386 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bitcast_ln15_fu_869_p1 = gmem_addr_read_reg_1340;

assign data_2_fu_936_p2 = (zext_ln175_fu_932_p1 + data_3_reg_1365);

assign data_3_fu_873_p1 = grp_fu_1113_p_dout0;

assign data_fu_1015_p1 = dc_1_fu_996_p9;

assign dc_1_fu_996_p2 = t_fu_921_p3;

assign dc_1_fu_996_p6 = t_2_fu_967_p3;

assign dc_1_fu_996_p7 = 'bx;

assign dc_1_fu_996_p8 = {{icmp_ln167_reg_1370}, {and_ln170_fu_984_p2}};

assign empty_fu_768_p2 = (icmp_ln12_reg_1304 | and_ln11_fu_756_p2);

assign grp_fu_1113_p_ce = grp_fu_606_ce;

assign grp_fu_1113_p_din0 = bitcast_ln15_fu_869_p1;

assign grp_fu_1113_p_din1 = 32'd1110997533;

assign grp_fu_1252_p0 = grp_fu_1252_p00;

assign grp_fu_1252_p00 = tmp_reg_1325;

assign grp_fu_1252_p1 = 7'd11;

assign grp_fu_1252_p2 = grp_fu_1252_p20;

assign grp_fu_1252_p20 = tmp_150_reg_1330_pp0_iter3_reg;

assign grp_fu_809_p1 = 6'd3;

assign grp_fu_835_p1 = 6'd3;

assign icmp_ln11_fu_660_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 12'd3072) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_681_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd1024) ? 1'b1 : 1'b0);

assign icmp_ln13_fu_750_p2 = ((iw_fu_198 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_885_p2 = ((xs_exp_1_fu_877_p3 < 8'd126) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_899_p2 = ((xs_exp_1_fu_877_p3 > 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_1195_p2 = (($signed(tmp_154_reg_1427) > $signed(25'd0)) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_1207_p2 = (($signed(r_1_fu_1200_p3) < $signed(32'd4294967168)) ? 1'b1 : 1'b0);

assign in_buf_10_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_10_ce0 = in_buf_10_ce0_local;

assign in_buf_10_d0 = select_ln19_fu_1217_p3;

assign in_buf_10_we0 = in_buf_10_we0_local;

assign in_buf_11_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_11_ce0 = in_buf_11_ce0_local;

assign in_buf_11_d0 = select_ln19_fu_1217_p3;

assign in_buf_11_we0 = in_buf_11_we0_local;

assign in_buf_12_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_12_ce0 = in_buf_12_ce0_local;

assign in_buf_12_d0 = select_ln19_fu_1217_p3;

assign in_buf_12_we0 = in_buf_12_we0_local;

assign in_buf_13_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_13_ce0 = in_buf_13_ce0_local;

assign in_buf_13_d0 = select_ln19_fu_1217_p3;

assign in_buf_13_we0 = in_buf_13_we0_local;

assign in_buf_14_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_14_ce0 = in_buf_14_ce0_local;

assign in_buf_14_d0 = select_ln19_fu_1217_p3;

assign in_buf_14_we0 = in_buf_14_we0_local;

assign in_buf_15_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_15_ce0 = in_buf_15_ce0_local;

assign in_buf_15_d0 = select_ln19_fu_1217_p3;

assign in_buf_15_we0 = in_buf_15_we0_local;

assign in_buf_16_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_16_ce0 = in_buf_16_ce0_local;

assign in_buf_16_d0 = select_ln19_fu_1217_p3;

assign in_buf_16_we0 = in_buf_16_we0_local;

assign in_buf_17_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_17_ce0 = in_buf_17_ce0_local;

assign in_buf_17_d0 = select_ln19_fu_1217_p3;

assign in_buf_17_we0 = in_buf_17_we0_local;

assign in_buf_18_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_18_ce0 = in_buf_18_ce0_local;

assign in_buf_18_d0 = select_ln19_fu_1217_p3;

assign in_buf_18_we0 = in_buf_18_we0_local;

assign in_buf_19_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_19_ce0 = in_buf_19_ce0_local;

assign in_buf_19_d0 = select_ln19_fu_1217_p3;

assign in_buf_19_we0 = in_buf_19_we0_local;

assign in_buf_1_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_1_ce0 = in_buf_1_ce0_local;

assign in_buf_1_d0 = select_ln19_fu_1217_p3;

assign in_buf_1_we0 = in_buf_1_we0_local;

assign in_buf_20_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_20_ce0 = in_buf_20_ce0_local;

assign in_buf_20_d0 = select_ln19_fu_1217_p3;

assign in_buf_20_we0 = in_buf_20_we0_local;

assign in_buf_21_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_21_ce0 = in_buf_21_ce0_local;

assign in_buf_21_d0 = select_ln19_fu_1217_p3;

assign in_buf_21_we0 = in_buf_21_we0_local;

assign in_buf_22_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_22_ce0 = in_buf_22_ce0_local;

assign in_buf_22_d0 = select_ln19_fu_1217_p3;

assign in_buf_22_we0 = in_buf_22_we0_local;

assign in_buf_23_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_23_ce0 = in_buf_23_ce0_local;

assign in_buf_23_d0 = select_ln19_fu_1217_p3;

assign in_buf_23_we0 = in_buf_23_we0_local;

assign in_buf_24_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_24_ce0 = in_buf_24_ce0_local;

assign in_buf_24_d0 = select_ln19_fu_1217_p3;

assign in_buf_24_we0 = in_buf_24_we0_local;

assign in_buf_25_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_25_ce0 = in_buf_25_ce0_local;

assign in_buf_25_d0 = select_ln19_fu_1217_p3;

assign in_buf_25_we0 = in_buf_25_we0_local;

assign in_buf_26_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_26_ce0 = in_buf_26_ce0_local;

assign in_buf_26_d0 = select_ln19_fu_1217_p3;

assign in_buf_26_we0 = in_buf_26_we0_local;

assign in_buf_2_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_2_ce0 = in_buf_2_ce0_local;

assign in_buf_2_d0 = select_ln19_fu_1217_p3;

assign in_buf_2_we0 = in_buf_2_we0_local;

assign in_buf_3_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_3_ce0 = in_buf_3_ce0_local;

assign in_buf_3_d0 = select_ln19_fu_1217_p3;

assign in_buf_3_we0 = in_buf_3_we0_local;

assign in_buf_4_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_4_ce0 = in_buf_4_ce0_local;

assign in_buf_4_d0 = select_ln19_fu_1217_p3;

assign in_buf_4_we0 = in_buf_4_we0_local;

assign in_buf_5_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_5_ce0 = in_buf_5_ce0_local;

assign in_buf_5_d0 = select_ln19_fu_1217_p3;

assign in_buf_5_we0 = in_buf_5_we0_local;

assign in_buf_6_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_6_ce0 = in_buf_6_ce0_local;

assign in_buf_6_d0 = select_ln19_fu_1217_p3;

assign in_buf_6_we0 = in_buf_6_we0_local;

assign in_buf_7_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_7_ce0 = in_buf_7_ce0_local;

assign in_buf_7_d0 = select_ln19_fu_1217_p3;

assign in_buf_7_we0 = in_buf_7_we0_local;

assign in_buf_8_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_8_ce0 = in_buf_8_ce0_local;

assign in_buf_8_d0 = select_ln19_fu_1217_p3;

assign in_buf_8_we0 = in_buf_8_we0_local;

assign in_buf_9_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_9_ce0 = in_buf_9_ce0_local;

assign in_buf_9_d0 = select_ln19_fu_1217_p3;

assign in_buf_9_we0 = in_buf_9_we0_local;

assign in_buf_address0 = zext_ln19_1_fu_1160_p1;

assign in_buf_ce0 = in_buf_ce0_local;

assign in_buf_d0 = select_ln19_fu_1217_p3;

assign in_buf_we0 = in_buf_we0_local;

assign index_fu_905_p4 = {{data_3_fu_873_p1[27:23]}};

assign iw_mid2_fu_773_p3 = ((empty_fu_768_p2[0:0] == 1'b1) ? 6'd0 : iw_fu_198);

assign lshr_ln18_fu_1093_p2 = zext_ln15_fu_1072_p1 >> zext_ln18_fu_1089_p1;

assign m_axi_gmem_0_ARADDR = 64'd0;

assign m_axi_gmem_0_ARBURST = 2'd0;

assign m_axi_gmem_0_ARCACHE = 4'd0;

assign m_axi_gmem_0_ARID = 1'd0;

assign m_axi_gmem_0_ARLEN = 32'd0;

assign m_axi_gmem_0_ARLOCK = 2'd0;

assign m_axi_gmem_0_ARPROT = 3'd0;

assign m_axi_gmem_0_ARQOS = 4'd0;

assign m_axi_gmem_0_ARREGION = 4'd0;

assign m_axi_gmem_0_ARSIZE = 3'd0;

assign m_axi_gmem_0_ARUSER = 1'd0;

assign m_axi_gmem_0_ARVALID = 1'b0;

assign m_axi_gmem_0_AWADDR = 64'd0;

assign m_axi_gmem_0_AWBURST = 2'd0;

assign m_axi_gmem_0_AWCACHE = 4'd0;

assign m_axi_gmem_0_AWID = 1'd0;

assign m_axi_gmem_0_AWLEN = 32'd0;

assign m_axi_gmem_0_AWLOCK = 2'd0;

assign m_axi_gmem_0_AWPROT = 3'd0;

assign m_axi_gmem_0_AWQOS = 4'd0;

assign m_axi_gmem_0_AWREGION = 4'd0;

assign m_axi_gmem_0_AWSIZE = 3'd0;

assign m_axi_gmem_0_AWUSER = 1'd0;

assign m_axi_gmem_0_AWVALID = 1'b0;

assign m_axi_gmem_0_BREADY = 1'b0;

assign m_axi_gmem_0_WDATA = 32'd0;

assign m_axi_gmem_0_WID = 1'd0;

assign m_axi_gmem_0_WLAST = 1'b0;

assign m_axi_gmem_0_WSTRB = 4'd0;

assign m_axi_gmem_0_WUSER = 1'd0;

assign m_axi_gmem_0_WVALID = 1'b0;

assign mantissa_fu_1063_p4 = {{{{1'd1}, {trunc_ln342_reg_1401}}}, {1'd0}};

assign mask_table_address0 = zext_ln179_fu_915_p1;

assign mul_ln10_fu_819_p0 = mul_ln10_fu_819_p00;

assign mul_ln10_fu_819_p00 = iw_mid2_fu_773_p3;

assign mul_ln10_fu_819_p1 = 13'd86;

assign mul_ln12_fu_793_p0 = mul_ln12_fu_793_p00;

assign mul_ln12_fu_793_p00 = select_ln12_fu_781_p3;

assign mul_ln12_fu_793_p1 = 13'd86;

assign one_half_table_address0 = zext_ln179_fu_915_p1;

assign r_1_fu_1200_p3 = ((icmp_ln17_fu_1195_p2[0:0] == 1'b1) ? 32'd127 : result_reg_1422);

assign result_2_fu_1132_p2 = (32'd0 - val_1_fu_1125_p3);

assign result_fu_1138_p3 = ((xs_sign_reg_1396[0:0] == 1'b1) ? result_2_fu_1132_p2 : val_1_fu_1125_p3);

assign select_ln11_1_fu_687_p3 = ((icmp_ln12_fu_681_p2[0:0] == 1'b1) ? add_ln11_fu_675_p2 : ap_sig_allocacmp_ic_load);

assign select_ln11_fu_738_p3 = ((icmp_ln12_reg_1304[0:0] == 1'b1) ? 6'd0 : ih_fu_202);

assign select_ln12_1_fu_709_p3 = ((icmp_ln12_fu_681_p2[0:0] == 1'b1) ? 12'd1 : add_ln12_1_fu_703_p2);

assign select_ln12_fu_781_p3 = ((and_ln11_fu_756_p2[0:0] == 1'b1) ? add_ln12_fu_762_p2 : select_ln11_fu_738_p3);

assign select_ln18_fu_1079_p3 = ((tmp_153_reg_1411[0:0] == 1'b1) ? sext_ln18_fu_1076_p1 : add_ln317_reg_1406);

assign select_ln19_fu_1217_p3 = ((icmp_ln18_fu_1207_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln19_fu_1213_p1);

assign sext_ln18_1_fu_1085_p1 = $signed(select_ln18_fu_1079_p3);

assign sext_ln18_fu_1076_p1 = $signed(sub_ln18_reg_1417);

assign shl_ln18_fu_1099_p2 = zext_ln15_fu_1072_p1 << zext_ln18_fu_1089_p1;

assign sub_ln18_fu_1057_p2 = (8'd127 - xs_exp_fu_1027_p3);

assign t_2_fu_967_p3 = {{tmp_1_i_fu_957_p4}, {xs_sig_fu_951_p2}};

assign t_fu_921_p3 = {{tmp_151_reg_1376}, {31'd0}};

assign tmp_144_fu_1115_p4 = {{shl_ln18_fu_1099_p2[55:24]}};

assign tmp_1_i_fu_957_p4 = {{data_2_fu_936_p2[31:23]}};

assign tmp_s_fu_1105_p4 = {{lshr_ln18_fu_1093_p2[55:24]}};

assign trunc_ln10_fu_1190_p1 = grp_fu_835_p2[1:0];

assign trunc_ln12_fu_1155_p1 = grp_fu_809_p2[1:0];

assign trunc_ln19_fu_1213_p1 = r_1_fu_1200_p3[7:0];

assign trunc_ln301_fu_941_p1 = data_2_fu_936_p2[22:0];

assign trunc_ln342_fu_1035_p1 = data_fu_1015_p1[22:0];

assign val_1_fu_1125_p3 = ((tmp_153_reg_1411[0:0] == 1'b1) ? tmp_s_fu_1105_p4 : tmp_144_fu_1115_p4);

assign xor_ln11_fu_745_p2 = (icmp_ln12_reg_1304 ^ 1'd1);

assign xor_ln167_fu_979_p2 = (icmp_ln167_reg_1370 ^ 1'd1);

assign xor_ln184_fu_945_p2 = (mask_table_q0 ^ 23'd8388607);

assign xs_exp_1_fu_877_p3 = {{data_3_fu_873_p1[30:23]}};

assign xs_exp_fu_1027_p3 = {{data_fu_1015_p1[30:23]}};

assign xs_sig_fu_951_p2 = (xor_ln184_fu_945_p2 & trunc_ln301_fu_941_p1);

assign zext_ln15_fu_1072_p1 = mantissa_fu_1063_p4;

assign zext_ln175_fu_932_p1 = one_half_table_q0;

assign zext_ln179_fu_915_p1 = index_fu_905_p4;

assign zext_ln18_fu_1089_p1 = $unsigned(sext_ln18_1_fu_1085_p1);

assign zext_ln19_1_fu_1160_p1 = add_ln19_reg_1355_pp0_iter9_reg;

assign zext_ln317_fu_1039_p1 = xs_exp_fu_1027_p3;

endmodule //mobilenet_v1_qat_mobilenet_v1_qat_Pipeline_LOAD_IC_LOAD_IH_LOAD_IW
