// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module mobilenet_v1_qat_dw3_qat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ifmap_0_0_address0,
        ifmap_0_0_ce0,
        ifmap_0_0_q0,
        ifmap_0_1_address0,
        ifmap_0_1_ce0,
        ifmap_0_1_q0,
        ifmap_0_2_address0,
        ifmap_0_2_ce0,
        ifmap_0_2_q0,
        ifmap_0_3_address0,
        ifmap_0_3_ce0,
        ifmap_0_3_q0,
        ifmap_1_0_address0,
        ifmap_1_0_ce0,
        ifmap_1_0_q0,
        ifmap_1_1_address0,
        ifmap_1_1_ce0,
        ifmap_1_1_q0,
        ifmap_1_2_address0,
        ifmap_1_2_ce0,
        ifmap_1_2_q0,
        ifmap_1_3_address0,
        ifmap_1_3_ce0,
        ifmap_1_3_q0,
        ifmap_2_0_address0,
        ifmap_2_0_ce0,
        ifmap_2_0_q0,
        ifmap_2_1_address0,
        ifmap_2_1_ce0,
        ifmap_2_1_q0,
        ifmap_2_2_address0,
        ifmap_2_2_ce0,
        ifmap_2_2_q0,
        ifmap_2_3_address0,
        ifmap_2_3_ce0,
        ifmap_2_3_q0,
        ifmap_3_0_address0,
        ifmap_3_0_ce0,
        ifmap_3_0_q0,
        ifmap_3_1_address0,
        ifmap_3_1_ce0,
        ifmap_3_1_q0,
        ifmap_3_2_address0,
        ifmap_3_2_ce0,
        ifmap_3_2_q0,
        ifmap_3_3_address0,
        ifmap_3_3_ce0,
        ifmap_3_3_q0,
        ofmap_0_address1,
        ofmap_0_ce1,
        ofmap_0_we1,
        ofmap_0_d1,
        ofmap_1_address1,
        ofmap_1_ce1,
        ofmap_1_we1,
        ofmap_1_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] ifmap_0_0_address0;
output   ifmap_0_0_ce0;
input  [6:0] ifmap_0_0_q0;
output  [6:0] ifmap_0_1_address0;
output   ifmap_0_1_ce0;
input  [6:0] ifmap_0_1_q0;
output  [6:0] ifmap_0_2_address0;
output   ifmap_0_2_ce0;
input  [6:0] ifmap_0_2_q0;
output  [6:0] ifmap_0_3_address0;
output   ifmap_0_3_ce0;
input  [6:0] ifmap_0_3_q0;
output  [6:0] ifmap_1_0_address0;
output   ifmap_1_0_ce0;
input  [6:0] ifmap_1_0_q0;
output  [6:0] ifmap_1_1_address0;
output   ifmap_1_1_ce0;
input  [6:0] ifmap_1_1_q0;
output  [6:0] ifmap_1_2_address0;
output   ifmap_1_2_ce0;
input  [6:0] ifmap_1_2_q0;
output  [6:0] ifmap_1_3_address0;
output   ifmap_1_3_ce0;
input  [6:0] ifmap_1_3_q0;
output  [6:0] ifmap_2_0_address0;
output   ifmap_2_0_ce0;
input  [6:0] ifmap_2_0_q0;
output  [6:0] ifmap_2_1_address0;
output   ifmap_2_1_ce0;
input  [6:0] ifmap_2_1_q0;
output  [6:0] ifmap_2_2_address0;
output   ifmap_2_2_ce0;
input  [6:0] ifmap_2_2_q0;
output  [6:0] ifmap_2_3_address0;
output   ifmap_2_3_ce0;
input  [6:0] ifmap_2_3_q0;
output  [6:0] ifmap_3_0_address0;
output   ifmap_3_0_ce0;
input  [6:0] ifmap_3_0_q0;
output  [6:0] ifmap_3_1_address0;
output   ifmap_3_1_ce0;
input  [6:0] ifmap_3_1_q0;
output  [6:0] ifmap_3_2_address0;
output   ifmap_3_2_ce0;
input  [6:0] ifmap_3_2_q0;
output  [6:0] ifmap_3_3_address0;
output   ifmap_3_3_ce0;
input  [6:0] ifmap_3_3_q0;
output  [7:0] ofmap_0_address1;
output   ofmap_0_ce1;
output   ofmap_0_we1;
output  [6:0] ofmap_0_d1;
output  [7:0] ofmap_1_address1;
output   ofmap_1_ce1;
output   ofmap_1_we1;
output  [6:0] ofmap_1_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln111_fu_571_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] features_3_dw_b_fold_address0;
wire  signed [11:0] features_3_dw_b_fold_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_1_1_address0;
wire  signed [7:0] p_ZL20features_3_dw_w_fold_1_1_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_1_2_address0;
wire  signed [6:0] p_ZL20features_3_dw_w_fold_1_2_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_2_1_address0;
wire   [7:0] p_ZL20features_3_dw_w_fold_2_1_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_0_0_address0;
wire  signed [7:0] p_ZL20features_3_dw_w_fold_0_0_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_0_1_address0;
wire  signed [7:0] p_ZL20features_3_dw_w_fold_0_1_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_0_2_address0;
wire  signed [6:0] p_ZL20features_3_dw_w_fold_0_2_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_1_0_address0;
wire  signed [6:0] p_ZL20features_3_dw_w_fold_1_0_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_2_0_address0;
wire  signed [7:0] p_ZL20features_3_dw_w_fold_2_0_q0;
wire   [6:0] p_ZL20features_3_dw_w_fold_2_2_address0;
wire  signed [6:0] p_ZL20features_3_dw_w_fold_2_2_q0;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln111_fu_666_p1;
reg   [63:0] zext_ln111_reg_1230;
reg   [63:0] zext_ln111_reg_1230_pp0_iter1_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter2_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter3_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter4_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter5_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter6_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter7_reg;
reg   [63:0] zext_ln111_reg_1230_pp0_iter8_reg;
wire   [0:0] trunc_ln111_fu_672_p1;
reg   [0:0] trunc_ln111_reg_1258;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter1_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter2_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter3_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter4_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter5_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter6_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter7_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter8_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter9_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter10_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter11_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter12_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter13_reg;
reg   [0:0] trunc_ln111_reg_1258_pp0_iter14_reg;
wire   [0:0] trunc_ln120_fu_712_p1;
reg   [0:0] trunc_ln120_reg_1272;
reg   [0:0] trunc_ln120_reg_1272_pp0_iter1_reg;
reg   [0:0] trunc_ln120_reg_1272_pp0_iter2_reg;
reg   [0:0] trunc_ln120_reg_1272_pp0_iter3_reg;
reg   [0:0] trunc_ln120_reg_1272_pp0_iter4_reg;
reg   [0:0] trunc_ln120_reg_1272_pp0_iter5_reg;
wire   [7:0] add_ln129_1_fu_732_p2;
reg   [7:0] add_ln129_1_reg_1278;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter1_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter2_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter3_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter4_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter5_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter6_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter7_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter8_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter9_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter10_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter11_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter12_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter13_reg;
reg   [7:0] add_ln129_1_reg_1278_pp0_iter14_reg;
wire   [0:0] trunc_ln121_fu_738_p1;
reg   [0:0] trunc_ln121_reg_1283;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter1_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter2_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter3_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter4_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter5_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter6_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter7_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter8_reg;
reg   [0:0] trunc_ln121_reg_1283_pp0_iter9_reg;
wire   [0:0] icmp_ln122_fu_760_p2;
reg   [0:0] icmp_ln122_reg_1289;
reg   [0:0] icmp_ln122_reg_1289_pp0_iter1_reg;
reg   [0:0] icmp_ln122_reg_1289_pp0_iter2_reg;
reg   [0:0] icmp_ln122_reg_1289_pp0_iter3_reg;
wire   [0:0] icmp_ln124_fu_766_p2;
reg   [0:0] icmp_ln124_reg_1294;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter1_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter2_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter3_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter4_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter5_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter6_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter7_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter8_reg;
reg   [0:0] icmp_ln124_reg_1294_pp0_iter9_reg;
wire   [0:0] icmp_ln124_1_fu_772_p2;
reg   [0:0] icmp_ln124_1_reg_1306;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter1_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter2_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter3_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter4_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter5_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter6_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter7_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter8_reg;
reg   [0:0] icmp_ln124_1_reg_1306_pp0_iter9_reg;
reg   [6:0] ifmap_1_1_load_reg_1331;
reg   [6:0] ifmap_1_1_load_reg_1331_pp0_iter2_reg;
reg   [6:0] ifmap_1_1_load_reg_1331_pp0_iter3_reg;
reg   [6:0] ifmap_1_1_load_reg_1331_pp0_iter4_reg;
reg   [6:0] ifmap_1_1_load_reg_1331_pp0_iter5_reg;
reg   [6:0] ifmap_1_1_load_reg_1331_pp0_iter6_reg;
wire   [6:0] select_ln124_fu_835_p3;
reg   [6:0] select_ln124_reg_1367;
reg   [6:0] select_ln124_reg_1367_pp0_iter3_reg;
reg   [6:0] select_ln124_reg_1367_pp0_iter4_reg;
reg   [6:0] select_ln124_reg_1367_pp0_iter5_reg;
reg   [6:0] select_ln124_reg_1367_pp0_iter6_reg;
reg   [6:0] select_ln124_reg_1367_pp0_iter7_reg;
reg   [6:0] select_ln124_reg_1367_pp0_iter8_reg;
reg   [6:0] select_ln124_reg_1367_pp0_iter9_reg;
wire  signed [14:0] sext_ln125_fu_846_p1;
reg  signed [14:0] sext_ln125_reg_1377;
wire   [6:0] select_ln124_1_fu_854_p3;
reg   [6:0] select_ln124_1_reg_1403;
reg   [6:0] select_ln124_1_reg_1403_pp0_iter4_reg;
reg   [6:0] select_ln124_1_reg_1403_pp0_iter5_reg;
reg   [6:0] select_ln124_1_reg_1403_pp0_iter6_reg;
reg   [6:0] select_ln124_1_reg_1403_pp0_iter7_reg;
reg   [6:0] ifmap_0_1_load_reg_1418;
reg   [6:0] ifmap_2_1_load_reg_1423;
wire  signed [15:0] sext_ln115_fu_873_p1;
reg  signed [15:0] sext_ln115_reg_1443;
reg  signed [15:0] sext_ln115_reg_1443_pp0_iter5_reg;
wire  signed [16:0] sext_ln115_1_fu_929_p1;
reg  signed [16:0] sext_ln115_1_reg_1510;
reg   [6:0] ifmap_3_1_load_reg_1531;
wire  signed [16:0] grp_fu_1145_p3;
wire  signed [17:0] sext_ln115_2_fu_997_p1;
reg  signed [17:0] sext_ln115_2_reg_1581;
reg  signed [7:0] p_ZL20features_3_dw_w_fold_2_1_load_reg_1587;
wire   [6:0] select_ln124_11_fu_1012_p3;
reg   [6:0] select_ln124_11_reg_1597;
wire   [6:0] out8_5_fu_1096_p3;
reg   [6:0] out8_5_reg_1602;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln129_2_fu_1104_p1;
reg   [1:0] ow_fu_148;
wire   [1:0] add_ln113_fu_778_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_ow_load;
reg   [1:0] oh_fu_152;
wire   [1:0] select_ln112_fu_658_p3;
reg   [1:0] ap_sig_allocacmp_oh_load;
reg   [3:0] indvar_flatten_fu_156;
wire   [3:0] select_ln112_1_fu_790_p3;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [7:0] c_fu_160;
wire   [7:0] select_ln111_1_fu_630_p3;
reg   [7:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten12_fu_164;
wire   [9:0] add_ln111_1_fu_577_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    ifmap_1_1_ce0_local;
reg    p_ZL20features_3_dw_w_fold_0_0_ce0_local;
reg    ifmap_1_0_ce0_local;
reg    ifmap_1_2_ce0_local;
reg    p_ZL20features_3_dw_w_fold_0_1_ce0_local;
reg    features_3_dw_b_fold_ce0_local;
reg    ifmap_1_3_ce0_local;
reg    p_ZL20features_3_dw_w_fold_0_2_ce0_local;
reg    ifmap_0_1_ce0_local;
reg    ifmap_2_1_ce0_local;
reg    p_ZL20features_3_dw_w_fold_1_0_ce0_local;
reg    p_ZL20features_3_dw_w_fold_1_2_ce0_local;
reg    ifmap_0_3_ce0_local;
reg    ifmap_2_3_ce0_local;
reg    p_ZL20features_3_dw_w_fold_1_1_ce0_local;
reg    ifmap_0_0_ce0_local;
reg    ifmap_0_2_ce0_local;
reg    ifmap_2_0_ce0_local;
reg    ifmap_2_2_ce0_local;
reg    ifmap_3_1_ce0_local;
reg    p_ZL20features_3_dw_w_fold_2_0_ce0_local;
reg    ifmap_3_3_ce0_local;
reg    p_ZL20features_3_dw_w_fold_2_2_ce0_local;
reg    p_ZL20features_3_dw_w_fold_2_1_ce0_local;
reg    ifmap_3_0_ce0_local;
reg    ifmap_3_2_ce0_local;
reg    ofmap_0_we1_local;
reg    ofmap_0_ce1_local;
reg    ofmap_1_we1_local;
reg    ofmap_1_ce1_local;
wire   [0:0] icmp_ln112_fu_598_p2;
wire   [0:0] icmp_ln113_fu_618_p2;
wire   [0:0] xor_ln111_fu_612_p2;
wire   [7:0] add_ln111_fu_592_p2;
wire   [1:0] select_ln111_fu_604_p3;
wire   [0:0] and_ln111_fu_624_p2;
wire   [0:0] empty_fu_644_p2;
wire   [1:0] add_ln112_fu_638_p2;
wire   [5:0] lshr_ln_fu_676_p4;
wire   [6:0] tmp_fu_686_p3;
wire   [6:0] zext_ln129_fu_694_p1;
wire   [6:0] add_ln129_fu_698_p2;
wire   [1:0] shl_ln120_fu_716_p2;
wire   [1:0] ow_mid2_fu_650_p3;
wire   [7:0] tmp_155_fu_704_p3;
wire   [7:0] zext_ln129_1_fu_728_p1;
wire   [1:0] shl_ln121_fu_742_p2;
wire   [1:0] add_ln122_1_fu_748_p2;
wire   [1:0] add_ln122_fu_722_p2;
wire   [1:0] or_ln122_fu_754_p2;
wire   [3:0] add_ln112_1_fu_784_p2;
wire  signed [14:0] grp_fu_1109_p3;
wire  signed [14:0] acc_2_fu_868_p3;
wire   [6:0] select_ln124_2_fu_877_p3;
wire  signed [15:0] grp_fu_1118_p3;
wire   [6:0] select_ln124_7_fu_903_p3;
wire   [6:0] select_ln124_6_fu_897_p3;
wire   [6:0] select_ln124_8_fu_909_p3;
wire  signed [15:0] grp_fu_1127_p3;
wire  signed [15:0] acc_6_fu_924_p3;
wire   [6:0] select_ln124_4_fu_940_p3;
wire   [6:0] select_ln124_3_fu_933_p3;
wire   [6:0] select_ln124_5_fu_947_p3;
wire  signed [16:0] grp_fu_1136_p3;
wire   [6:0] select_ln124_9_fu_967_p3;
wire   [6:0] select_ln124_12_fu_981_p3;
wire   [6:0] select_ln124_13_fu_987_p3;
wire  signed [16:0] grp_fu_1153_p3;
wire  signed [17:0] grp_fu_1162_p3;
wire   [6:0] select_ln124_10_fu_1005_p3;
wire   [6:0] mul_ln125_5_fu_1024_p0;
wire  signed [14:0] mul_ln125_5_fu_1024_p2;
wire  signed [31:0] out32_fu_1034_p1;
wire   [31:0] grp_fu_1179_p4;
wire  signed [31:0] tmp_156_fu_1043_p1;
wire   [3:0] tmp_156_fu_1043_p4;
wire   [0:0] icmp_ln86_fu_1052_p2;
wire   [10:0] out32_fu_1034_p4;
wire   [10:0] out32_5_fu_1058_p3;
wire   [0:0] icmp_ln87_fu_1066_p2;
wire   [7:0] trunc_ln88_fu_1072_p1;
wire   [7:0] out8_fu_1076_p3;
wire   [0:0] tmp_157_fu_1088_p3;
wire   [6:0] trunc_ln88_5_fu_1084_p1;
wire   [6:0] grp_fu_1109_p1;
wire   [6:0] grp_fu_1118_p1;
wire   [6:0] grp_fu_1127_p0;
wire  signed [15:0] grp_fu_1127_p2;
wire   [6:0] grp_fu_1136_p0;
wire   [6:0] grp_fu_1145_p0;
wire  signed [16:0] grp_fu_1145_p2;
wire   [6:0] grp_fu_1153_p1;
wire   [6:0] grp_fu_1162_p1;
wire   [6:0] grp_fu_1171_p0;
wire  signed [17:0] grp_fu_1171_p2;
wire  signed [17:0] grp_fu_1171_p3;
wire   [15:0] grp_fu_1179_p2;
wire   [20:0] grp_fu_1179_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] grp_fu_1109_p10;
wire   [14:0] grp_fu_1118_p10;
wire   [13:0] grp_fu_1127_p00;
wire   [13:0] grp_fu_1136_p00;
wire   [13:0] grp_fu_1145_p00;
wire   [14:0] grp_fu_1153_p10;
wire   [14:0] grp_fu_1162_p10;
wire   [13:0] grp_fu_1171_p00;
wire   [14:0] mul_ln125_5_fu_1024_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ow_fu_148 = 2'd0;
#0 oh_fu_152 = 2'd0;
#0 indvar_flatten_fu_156 = 4'd0;
#0 c_fu_160 = 8'd0;
#0 indvar_flatten12_fu_164 = 10'd0;
#0 ap_done_reg = 1'b0;
end

mobilenet_v1_qat_dw3_qat_features_3_dw_b_fold_ROM_AUTO_1R #(
    .DataWidth( 12 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
features_3_dw_b_fold_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(features_3_dw_b_fold_address0),
    .ce0(features_3_dw_b_fold_ce0_local),
    .q0(features_3_dw_b_fold_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_1_1_ROM_2P_BRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_1_1_address0),
    .ce0(p_ZL20features_3_dw_w_fold_1_1_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_1_1_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_1_2_ROM_2P_BRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_1_2_address0),
    .ce0(p_ZL20features_3_dw_w_fold_1_2_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_1_2_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_2_1_ROM_2P_BRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_2_1_address0),
    .ce0(p_ZL20features_3_dw_w_fold_2_1_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_2_1_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_0_0_ROM_2P_BRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_0_0_address0),
    .ce0(p_ZL20features_3_dw_w_fold_0_0_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_0_0_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_0_1_ROM_2P_BRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_0_1_address0),
    .ce0(p_ZL20features_3_dw_w_fold_0_1_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_0_1_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_0_2_ROM_2P_BRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_0_2_address0),
    .ce0(p_ZL20features_3_dw_w_fold_0_2_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_0_2_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_1_0_ROM_2P_BRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_1_0_address0),
    .ce0(p_ZL20features_3_dw_w_fold_1_0_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_1_0_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_2_0_ROM_2P_BRAM_1R #(
    .DataWidth( 8 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_2_0_address0),
    .ce0(p_ZL20features_3_dw_w_fold_2_0_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_2_0_q0)
);

mobilenet_v1_qat_dw3_qat_p_ZL20features_3_dw_w_fold_2_2_ROM_2P_BRAM_1R #(
    .DataWidth( 7 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
p_ZL20features_3_dw_w_fold_2_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL20features_3_dw_w_fold_2_2_address0),
    .ce0(p_ZL20features_3_dw_w_fold_2_2_ce0_local),
    .q0(p_ZL20features_3_dw_w_fold_2_2_q0)
);

mobilenet_v1_qat_mul_7ns_8s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_7ns_8s_15_1_1_U613(
    .din0(mul_ln125_5_fu_1024_p0),
    .din1(p_ZL20features_3_dw_w_fold_2_1_load_reg_1587),
    .dout(mul_ln125_5_fu_1024_p2)
);

mobilenet_v1_qat_mac_muladd_8s_7ns_12s_15_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 15 ))
mac_muladd_8s_7ns_12s_15_4_1_U614(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL20features_3_dw_w_fold_0_0_q0),
    .din1(grp_fu_1109_p1),
    .din2(features_3_dw_b_fold_q0),
    .ce(1'b1),
    .dout(grp_fu_1109_p3)
);

mobilenet_v1_qat_mac_muladd_8s_7ns_15s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 16 ))
mac_muladd_8s_7ns_15s_16_4_1_U615(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL20features_3_dw_w_fold_0_1_q0),
    .din1(grp_fu_1118_p1),
    .din2(acc_2_fu_868_p3),
    .ce(1'b1),
    .dout(grp_fu_1118_p3)
);

mobilenet_v1_qat_mac_muladd_7ns_7s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_7ns_7s_16s_16_4_1_U616(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1127_p0),
    .din1(p_ZL20features_3_dw_w_fold_0_2_q0),
    .din2(grp_fu_1127_p2),
    .ce(1'b1),
    .dout(grp_fu_1127_p3)
);

mobilenet_v1_qat_mac_muladd_7ns_7s_16s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_7ns_7s_16s_17_4_1_U617(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1136_p0),
    .din1(p_ZL20features_3_dw_w_fold_1_0_q0),
    .din2(acc_6_fu_924_p3),
    .ce(1'b1),
    .dout(grp_fu_1136_p3)
);

mobilenet_v1_qat_mac_muladd_7ns_7s_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_7ns_7s_17s_17_4_1_U618(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1145_p0),
    .din1(p_ZL20features_3_dw_w_fold_1_2_q0),
    .din2(grp_fu_1145_p2),
    .ce(1'b1),
    .dout(grp_fu_1145_p3)
);

mobilenet_v1_qat_mac_muladd_8s_7ns_17s_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_8s_7ns_17s_17_4_1_U619(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL20features_3_dw_w_fold_1_1_q0),
    .din1(grp_fu_1153_p1),
    .din2(grp_fu_1145_p3),
    .ce(1'b1),
    .dout(grp_fu_1153_p3)
);

mobilenet_v1_qat_mac_muladd_8s_7ns_17s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 18 ))
mac_muladd_8s_7ns_17s_18_4_1_U620(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL20features_3_dw_w_fold_2_0_q0),
    .din1(grp_fu_1162_p1),
    .din2(grp_fu_1153_p3),
    .ce(1'b1),
    .dout(grp_fu_1162_p3)
);

mobilenet_v1_qat_mac_muladd_7ns_7s_18s_18_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 18 ),
    .dout_WIDTH( 18 ))
mac_muladd_7ns_7s_18s_18_4_1_U621(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1171_p0),
    .din1(p_ZL20features_3_dw_w_fold_2_2_q0),
    .din2(grp_fu_1171_p2),
    .ce(1'b1),
    .dout(grp_fu_1171_p3)
);

mobilenet_v1_qat_ama_addmuladd_18s_15s_16ns_21ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 21 ),
    .dout_WIDTH( 32 ))
ama_addmuladd_18s_15s_16ns_21ns_32_4_1_U622(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1171_p3),
    .din1(mul_ln125_5_fu_1024_p2),
    .din2(grp_fu_1179_p2),
    .din3(grp_fu_1179_p3),
    .ce(1'b1),
    .dout(grp_fu_1179_p4)
);

mobilenet_v1_qat_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_571_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_160 <= select_ln111_1_fu_630_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_160 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_571_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten12_fu_164 <= add_ln111_1_fu_577_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_164 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_571_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_156 <= select_ln112_1_fu_790_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_156 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_571_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            oh_fu_152 <= select_ln112_fu_658_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oh_fu_152 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_571_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            ow_fu_148 <= add_ln113_fu_778_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            ow_fu_148 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln129_1_reg_1278 <= add_ln129_1_fu_732_p2;
        add_ln129_1_reg_1278_pp0_iter1_reg <= add_ln129_1_reg_1278;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln122_reg_1289 <= icmp_ln122_fu_760_p2;
        icmp_ln122_reg_1289_pp0_iter1_reg <= icmp_ln122_reg_1289;
        icmp_ln124_1_reg_1306 <= icmp_ln124_1_fu_772_p2;
        icmp_ln124_1_reg_1306_pp0_iter1_reg <= icmp_ln124_1_reg_1306;
        icmp_ln124_reg_1294 <= icmp_ln124_fu_766_p2;
        icmp_ln124_reg_1294_pp0_iter1_reg <= icmp_ln124_reg_1294;
        ifmap_1_1_load_reg_1331 <= ifmap_1_1_q0;
        trunc_ln111_reg_1258 <= trunc_ln111_fu_672_p1;
        trunc_ln111_reg_1258_pp0_iter1_reg <= trunc_ln111_reg_1258;
        trunc_ln120_reg_1272 <= trunc_ln120_fu_712_p1;
        trunc_ln120_reg_1272_pp0_iter1_reg <= trunc_ln120_reg_1272;
        trunc_ln121_reg_1283 <= trunc_ln121_fu_738_p1;
        trunc_ln121_reg_1283_pp0_iter1_reg <= trunc_ln121_reg_1283;
        zext_ln111_reg_1230[7 : 0] <= zext_ln111_fu_666_p1[7 : 0];
        zext_ln111_reg_1230_pp0_iter1_reg[7 : 0] <= zext_ln111_reg_1230[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln129_1_reg_1278_pp0_iter10_reg <= add_ln129_1_reg_1278_pp0_iter9_reg;
        add_ln129_1_reg_1278_pp0_iter11_reg <= add_ln129_1_reg_1278_pp0_iter10_reg;
        add_ln129_1_reg_1278_pp0_iter12_reg <= add_ln129_1_reg_1278_pp0_iter11_reg;
        add_ln129_1_reg_1278_pp0_iter13_reg <= add_ln129_1_reg_1278_pp0_iter12_reg;
        add_ln129_1_reg_1278_pp0_iter14_reg <= add_ln129_1_reg_1278_pp0_iter13_reg;
        add_ln129_1_reg_1278_pp0_iter2_reg <= add_ln129_1_reg_1278_pp0_iter1_reg;
        add_ln129_1_reg_1278_pp0_iter3_reg <= add_ln129_1_reg_1278_pp0_iter2_reg;
        add_ln129_1_reg_1278_pp0_iter4_reg <= add_ln129_1_reg_1278_pp0_iter3_reg;
        add_ln129_1_reg_1278_pp0_iter5_reg <= add_ln129_1_reg_1278_pp0_iter4_reg;
        add_ln129_1_reg_1278_pp0_iter6_reg <= add_ln129_1_reg_1278_pp0_iter5_reg;
        add_ln129_1_reg_1278_pp0_iter7_reg <= add_ln129_1_reg_1278_pp0_iter6_reg;
        add_ln129_1_reg_1278_pp0_iter8_reg <= add_ln129_1_reg_1278_pp0_iter7_reg;
        add_ln129_1_reg_1278_pp0_iter9_reg <= add_ln129_1_reg_1278_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        icmp_ln122_reg_1289_pp0_iter2_reg <= icmp_ln122_reg_1289_pp0_iter1_reg;
        icmp_ln122_reg_1289_pp0_iter3_reg <= icmp_ln122_reg_1289_pp0_iter2_reg;
        icmp_ln124_1_reg_1306_pp0_iter2_reg <= icmp_ln124_1_reg_1306_pp0_iter1_reg;
        icmp_ln124_1_reg_1306_pp0_iter3_reg <= icmp_ln124_1_reg_1306_pp0_iter2_reg;
        icmp_ln124_1_reg_1306_pp0_iter4_reg <= icmp_ln124_1_reg_1306_pp0_iter3_reg;
        icmp_ln124_1_reg_1306_pp0_iter5_reg <= icmp_ln124_1_reg_1306_pp0_iter4_reg;
        icmp_ln124_1_reg_1306_pp0_iter6_reg <= icmp_ln124_1_reg_1306_pp0_iter5_reg;
        icmp_ln124_1_reg_1306_pp0_iter7_reg <= icmp_ln124_1_reg_1306_pp0_iter6_reg;
        icmp_ln124_1_reg_1306_pp0_iter8_reg <= icmp_ln124_1_reg_1306_pp0_iter7_reg;
        icmp_ln124_1_reg_1306_pp0_iter9_reg <= icmp_ln124_1_reg_1306_pp0_iter8_reg;
        icmp_ln124_reg_1294_pp0_iter2_reg <= icmp_ln124_reg_1294_pp0_iter1_reg;
        icmp_ln124_reg_1294_pp0_iter3_reg <= icmp_ln124_reg_1294_pp0_iter2_reg;
        icmp_ln124_reg_1294_pp0_iter4_reg <= icmp_ln124_reg_1294_pp0_iter3_reg;
        icmp_ln124_reg_1294_pp0_iter5_reg <= icmp_ln124_reg_1294_pp0_iter4_reg;
        icmp_ln124_reg_1294_pp0_iter6_reg <= icmp_ln124_reg_1294_pp0_iter5_reg;
        icmp_ln124_reg_1294_pp0_iter7_reg <= icmp_ln124_reg_1294_pp0_iter6_reg;
        icmp_ln124_reg_1294_pp0_iter8_reg <= icmp_ln124_reg_1294_pp0_iter7_reg;
        icmp_ln124_reg_1294_pp0_iter9_reg <= icmp_ln124_reg_1294_pp0_iter8_reg;
        ifmap_0_1_load_reg_1418 <= ifmap_0_1_q0;
        ifmap_1_1_load_reg_1331_pp0_iter2_reg <= ifmap_1_1_load_reg_1331;
        ifmap_1_1_load_reg_1331_pp0_iter3_reg <= ifmap_1_1_load_reg_1331_pp0_iter2_reg;
        ifmap_1_1_load_reg_1331_pp0_iter4_reg <= ifmap_1_1_load_reg_1331_pp0_iter3_reg;
        ifmap_1_1_load_reg_1331_pp0_iter5_reg <= ifmap_1_1_load_reg_1331_pp0_iter4_reg;
        ifmap_1_1_load_reg_1331_pp0_iter6_reg <= ifmap_1_1_load_reg_1331_pp0_iter5_reg;
        ifmap_2_1_load_reg_1423 <= ifmap_2_1_q0;
        ifmap_3_1_load_reg_1531 <= ifmap_3_1_q0;
        out8_5_reg_1602 <= out8_5_fu_1096_p3;
        p_ZL20features_3_dw_w_fold_2_1_load_reg_1587 <= p_ZL20features_3_dw_w_fold_2_1_q0;
        select_ln124_11_reg_1597 <= select_ln124_11_fu_1012_p3;
        select_ln124_1_reg_1403 <= select_ln124_1_fu_854_p3;
        select_ln124_1_reg_1403_pp0_iter4_reg <= select_ln124_1_reg_1403;
        select_ln124_1_reg_1403_pp0_iter5_reg <= select_ln124_1_reg_1403_pp0_iter4_reg;
        select_ln124_1_reg_1403_pp0_iter6_reg <= select_ln124_1_reg_1403_pp0_iter5_reg;
        select_ln124_1_reg_1403_pp0_iter7_reg <= select_ln124_1_reg_1403_pp0_iter6_reg;
        select_ln124_reg_1367 <= select_ln124_fu_835_p3;
        select_ln124_reg_1367_pp0_iter3_reg <= select_ln124_reg_1367;
        select_ln124_reg_1367_pp0_iter4_reg <= select_ln124_reg_1367_pp0_iter3_reg;
        select_ln124_reg_1367_pp0_iter5_reg <= select_ln124_reg_1367_pp0_iter4_reg;
        select_ln124_reg_1367_pp0_iter6_reg <= select_ln124_reg_1367_pp0_iter5_reg;
        select_ln124_reg_1367_pp0_iter7_reg <= select_ln124_reg_1367_pp0_iter6_reg;
        select_ln124_reg_1367_pp0_iter8_reg <= select_ln124_reg_1367_pp0_iter7_reg;
        select_ln124_reg_1367_pp0_iter9_reg <= select_ln124_reg_1367_pp0_iter8_reg;
        sext_ln115_1_reg_1510 <= sext_ln115_1_fu_929_p1;
        sext_ln115_2_reg_1581 <= sext_ln115_2_fu_997_p1;
        sext_ln115_reg_1443 <= sext_ln115_fu_873_p1;
        sext_ln115_reg_1443_pp0_iter5_reg <= sext_ln115_reg_1443;
        sext_ln125_reg_1377 <= sext_ln125_fu_846_p1;
        trunc_ln111_reg_1258_pp0_iter10_reg <= trunc_ln111_reg_1258_pp0_iter9_reg;
        trunc_ln111_reg_1258_pp0_iter11_reg <= trunc_ln111_reg_1258_pp0_iter10_reg;
        trunc_ln111_reg_1258_pp0_iter12_reg <= trunc_ln111_reg_1258_pp0_iter11_reg;
        trunc_ln111_reg_1258_pp0_iter13_reg <= trunc_ln111_reg_1258_pp0_iter12_reg;
        trunc_ln111_reg_1258_pp0_iter14_reg <= trunc_ln111_reg_1258_pp0_iter13_reg;
        trunc_ln111_reg_1258_pp0_iter2_reg <= trunc_ln111_reg_1258_pp0_iter1_reg;
        trunc_ln111_reg_1258_pp0_iter3_reg <= trunc_ln111_reg_1258_pp0_iter2_reg;
        trunc_ln111_reg_1258_pp0_iter4_reg <= trunc_ln111_reg_1258_pp0_iter3_reg;
        trunc_ln111_reg_1258_pp0_iter5_reg <= trunc_ln111_reg_1258_pp0_iter4_reg;
        trunc_ln111_reg_1258_pp0_iter6_reg <= trunc_ln111_reg_1258_pp0_iter5_reg;
        trunc_ln111_reg_1258_pp0_iter7_reg <= trunc_ln111_reg_1258_pp0_iter6_reg;
        trunc_ln111_reg_1258_pp0_iter8_reg <= trunc_ln111_reg_1258_pp0_iter7_reg;
        trunc_ln111_reg_1258_pp0_iter9_reg <= trunc_ln111_reg_1258_pp0_iter8_reg;
        trunc_ln120_reg_1272_pp0_iter2_reg <= trunc_ln120_reg_1272_pp0_iter1_reg;
        trunc_ln120_reg_1272_pp0_iter3_reg <= trunc_ln120_reg_1272_pp0_iter2_reg;
        trunc_ln120_reg_1272_pp0_iter4_reg <= trunc_ln120_reg_1272_pp0_iter3_reg;
        trunc_ln120_reg_1272_pp0_iter5_reg <= trunc_ln120_reg_1272_pp0_iter4_reg;
        trunc_ln121_reg_1283_pp0_iter2_reg <= trunc_ln121_reg_1283_pp0_iter1_reg;
        trunc_ln121_reg_1283_pp0_iter3_reg <= trunc_ln121_reg_1283_pp0_iter2_reg;
        trunc_ln121_reg_1283_pp0_iter4_reg <= trunc_ln121_reg_1283_pp0_iter3_reg;
        trunc_ln121_reg_1283_pp0_iter5_reg <= trunc_ln121_reg_1283_pp0_iter4_reg;
        trunc_ln121_reg_1283_pp0_iter6_reg <= trunc_ln121_reg_1283_pp0_iter5_reg;
        trunc_ln121_reg_1283_pp0_iter7_reg <= trunc_ln121_reg_1283_pp0_iter6_reg;
        trunc_ln121_reg_1283_pp0_iter8_reg <= trunc_ln121_reg_1283_pp0_iter7_reg;
        trunc_ln121_reg_1283_pp0_iter9_reg <= trunc_ln121_reg_1283_pp0_iter8_reg;
        zext_ln111_reg_1230_pp0_iter2_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter1_reg[7 : 0];
        zext_ln111_reg_1230_pp0_iter3_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter2_reg[7 : 0];
        zext_ln111_reg_1230_pp0_iter4_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter3_reg[7 : 0];
        zext_ln111_reg_1230_pp0_iter5_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter4_reg[7 : 0];
        zext_ln111_reg_1230_pp0_iter6_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter5_reg[7 : 0];
        zext_ln111_reg_1230_pp0_iter7_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter6_reg[7 : 0];
        zext_ln111_reg_1230_pp0_iter8_reg[7 : 0] <= zext_ln111_reg_1230_pp0_iter7_reg[7 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln111_fu_571_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter14_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 8'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_160;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_164;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_156;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oh_load = 2'd0;
    end else begin
        ap_sig_allocacmp_oh_load = oh_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_ow_load = 2'd0;
    end else begin
        ap_sig_allocacmp_ow_load = ow_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        features_3_dw_b_fold_ce0_local = 1'b1;
    end else begin
        features_3_dw_b_fold_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ifmap_0_0_ce0_local = 1'b1;
    end else begin
        ifmap_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ifmap_0_1_ce0_local = 1'b1;
    end else begin
        ifmap_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ifmap_0_2_ce0_local = 1'b1;
    end else begin
        ifmap_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ifmap_0_3_ce0_local = 1'b1;
    end else begin
        ifmap_0_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ifmap_1_0_ce0_local = 1'b1;
    end else begin
        ifmap_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ifmap_1_1_ce0_local = 1'b1;
    end else begin
        ifmap_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ifmap_1_2_ce0_local = 1'b1;
    end else begin
        ifmap_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ifmap_1_3_ce0_local = 1'b1;
    end else begin
        ifmap_1_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ifmap_2_0_ce0_local = 1'b1;
    end else begin
        ifmap_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ifmap_2_1_ce0_local = 1'b1;
    end else begin
        ifmap_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ifmap_2_2_ce0_local = 1'b1;
    end else begin
        ifmap_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ifmap_2_3_ce0_local = 1'b1;
    end else begin
        ifmap_2_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ifmap_3_0_ce0_local = 1'b1;
    end else begin
        ifmap_3_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ifmap_3_1_ce0_local = 1'b1;
    end else begin
        ifmap_3_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ifmap_3_2_ce0_local = 1'b1;
    end else begin
        ifmap_3_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ifmap_3_3_ce0_local = 1'b1;
    end else begin
        ifmap_3_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        ofmap_0_ce1_local = 1'b1;
    end else begin
        ofmap_0_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln111_reg_1258_pp0_iter14_reg == 1'd0))) begin
        ofmap_0_we1_local = 1'b1;
    end else begin
        ofmap_0_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        ofmap_1_ce1_local = 1'b1;
    end else begin
        ofmap_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1) & (trunc_ln111_reg_1258_pp0_iter14_reg == 1'd1))) begin
        ofmap_1_we1_local = 1'b1;
    end else begin
        ofmap_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL20features_3_dw_w_fold_0_0_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_0_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL20features_3_dw_w_fold_0_1_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_0_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_0_2_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_0_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_1_0_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_1_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_1_1_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_1_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_1_2_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_1_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_2_0_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_2_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_2_1_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_2_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        p_ZL20features_3_dw_w_fold_2_2_ce0_local = 1'b1;
    end else begin
        p_ZL20features_3_dw_w_fold_2_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_2_fu_868_p3 = ((icmp_ln122_reg_1289_pp0_iter3_reg[0:0] == 1'b1) ? grp_fu_1109_p3 : sext_ln125_reg_1377);

assign acc_6_fu_924_p3 = ((trunc_ln120_reg_1272_pp0_iter5_reg[0:0] == 1'b1) ? grp_fu_1127_p3 : sext_ln115_reg_1443_pp0_iter5_reg);

assign add_ln111_1_fu_577_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 10'd1);

assign add_ln111_fu_592_p2 = (ap_sig_allocacmp_c_load + 8'd1);

assign add_ln112_1_fu_784_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln112_fu_638_p2 = (select_ln111_fu_604_p3 + 2'd1);

assign add_ln113_fu_778_p2 = (ow_mid2_fu_650_p3 + 2'd1);

assign add_ln122_1_fu_748_p2 = ($signed(shl_ln121_fu_742_p2) + $signed(2'd3));

assign add_ln122_fu_722_p2 = ($signed(shl_ln120_fu_716_p2) + $signed(2'd3));

assign add_ln129_1_fu_732_p2 = (tmp_155_fu_704_p3 + zext_ln129_1_fu_728_p1);

assign add_ln129_fu_698_p2 = (tmp_fu_686_p3 + zext_ln129_fu_694_p1);

assign and_ln111_fu_624_p2 = (xor_ln111_fu_612_p2 & icmp_ln113_fu_618_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_644_p2 = (icmp_ln112_fu_598_p2 | and_ln111_fu_624_p2);

assign features_3_dw_b_fold_address0 = zext_ln111_reg_1230_pp0_iter1_reg;

assign grp_fu_1109_p1 = grp_fu_1109_p10;

assign grp_fu_1109_p10 = ifmap_1_1_q0;

assign grp_fu_1118_p1 = grp_fu_1118_p10;

assign grp_fu_1118_p10 = select_ln124_fu_835_p3;

assign grp_fu_1127_p0 = grp_fu_1127_p00;

assign grp_fu_1127_p00 = select_ln124_1_fu_854_p3;

assign grp_fu_1127_p2 = ((trunc_ln120_reg_1272_pp0_iter4_reg[0:0] == 1'b1) ? grp_fu_1118_p3 : sext_ln115_reg_1443);

assign grp_fu_1136_p0 = grp_fu_1136_p00;

assign grp_fu_1136_p00 = select_ln124_2_fu_877_p3;

assign grp_fu_1145_p0 = grp_fu_1145_p00;

assign grp_fu_1145_p00 = select_ln124_8_fu_909_p3;

assign grp_fu_1145_p2 = ((trunc_ln121_reg_1283_pp0_iter6_reg[0:0] == 1'b1) ? grp_fu_1136_p3 : sext_ln115_1_reg_1510);

assign grp_fu_1153_p1 = grp_fu_1153_p10;

assign grp_fu_1153_p10 = select_ln124_5_fu_947_p3;

assign grp_fu_1162_p1 = grp_fu_1162_p10;

assign grp_fu_1162_p10 = select_ln124_9_fu_967_p3;

assign grp_fu_1171_p0 = grp_fu_1171_p00;

assign grp_fu_1171_p00 = select_ln124_13_fu_987_p3;

assign grp_fu_1171_p2 = ((trunc_ln121_reg_1283_pp0_iter9_reg[0:0] == 1'b1) ? grp_fu_1162_p3 : sext_ln115_2_reg_1581);

assign grp_fu_1179_p2 = 32'd58363;

assign grp_fu_1179_p3 = 32'd1048576;

assign icmp_ln111_fu_571_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln112_fu_598_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln113_fu_618_p2 = ((ap_sig_allocacmp_ow_load == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln122_fu_760_p2 = ((or_ln122_fu_754_p2 != 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln124_1_fu_772_p2 = ((select_ln112_fu_658_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln124_fu_766_p2 = ((ow_mid2_fu_650_p3 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_1052_p2 = (($signed(tmp_156_fu_1043_p4) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_1066_p2 = (($signed(out32_5_fu_1058_p3) < $signed(11'd1920)) ? 1'b1 : 1'b0);

assign ifmap_0_0_address0 = zext_ln111_reg_1230_pp0_iter4_reg;

assign ifmap_0_0_ce0 = ifmap_0_0_ce0_local;

assign ifmap_0_1_address0 = zext_ln111_reg_1230_pp0_iter2_reg;

assign ifmap_0_1_ce0 = ifmap_0_1_ce0_local;

assign ifmap_0_2_address0 = zext_ln111_reg_1230_pp0_iter4_reg;

assign ifmap_0_2_ce0 = ifmap_0_2_ce0_local;

assign ifmap_0_3_address0 = zext_ln111_reg_1230_pp0_iter3_reg;

assign ifmap_0_3_ce0 = ifmap_0_3_ce0_local;

assign ifmap_1_0_address0 = zext_ln111_reg_1230;

assign ifmap_1_0_ce0 = ifmap_1_0_ce0_local;

assign ifmap_1_1_address0 = zext_ln111_fu_666_p1;

assign ifmap_1_1_ce0 = ifmap_1_1_ce0_local;

assign ifmap_1_2_address0 = zext_ln111_reg_1230;

assign ifmap_1_2_ce0 = ifmap_1_2_ce0_local;

assign ifmap_1_3_address0 = zext_ln111_reg_1230_pp0_iter1_reg;

assign ifmap_1_3_ce0 = ifmap_1_3_ce0_local;

assign ifmap_2_0_address0 = zext_ln111_reg_1230_pp0_iter4_reg;

assign ifmap_2_0_ce0 = ifmap_2_0_ce0_local;

assign ifmap_2_1_address0 = zext_ln111_reg_1230_pp0_iter2_reg;

assign ifmap_2_1_ce0 = ifmap_2_1_ce0_local;

assign ifmap_2_2_address0 = zext_ln111_reg_1230_pp0_iter4_reg;

assign ifmap_2_2_ce0 = ifmap_2_2_ce0_local;

assign ifmap_2_3_address0 = zext_ln111_reg_1230_pp0_iter3_reg;

assign ifmap_2_3_ce0 = ifmap_2_3_ce0_local;

assign ifmap_3_0_address0 = zext_ln111_reg_1230_pp0_iter8_reg;

assign ifmap_3_0_ce0 = ifmap_3_0_ce0_local;

assign ifmap_3_1_address0 = zext_ln111_reg_1230_pp0_iter5_reg;

assign ifmap_3_1_ce0 = ifmap_3_1_ce0_local;

assign ifmap_3_2_address0 = zext_ln111_reg_1230_pp0_iter8_reg;

assign ifmap_3_2_ce0 = ifmap_3_2_ce0_local;

assign ifmap_3_3_address0 = zext_ln111_reg_1230_pp0_iter6_reg;

assign ifmap_3_3_ce0 = ifmap_3_3_ce0_local;

assign lshr_ln_fu_676_p4 = {{select_ln111_1_fu_630_p3[6:1]}};

assign mul_ln125_5_fu_1024_p0 = mul_ln125_5_fu_1024_p00;

assign mul_ln125_5_fu_1024_p00 = select_ln124_11_reg_1597;

assign ofmap_0_address1 = zext_ln129_2_fu_1104_p1;

assign ofmap_0_ce1 = ofmap_0_ce1_local;

assign ofmap_0_d1 = out8_5_reg_1602;

assign ofmap_0_we1 = ofmap_0_we1_local;

assign ofmap_1_address1 = zext_ln129_2_fu_1104_p1;

assign ofmap_1_ce1 = ofmap_1_ce1_local;

assign ofmap_1_d1 = out8_5_reg_1602;

assign ofmap_1_we1 = ofmap_1_we1_local;

assign or_ln122_fu_754_p2 = (add_ln122_fu_722_p2 | add_ln122_1_fu_748_p2);

assign out32_5_fu_1058_p3 = ((icmp_ln86_fu_1052_p2[0:0] == 1'b1) ? 11'd127 : out32_fu_1034_p4);

assign out32_fu_1034_p1 = grp_fu_1179_p4;

assign out32_fu_1034_p4 = {{out32_fu_1034_p1[31:21]}};

assign out8_5_fu_1096_p3 = ((tmp_157_fu_1088_p3[0:0] == 1'b1) ? 7'd0 : trunc_ln88_5_fu_1084_p1);

assign out8_fu_1076_p3 = ((icmp_ln87_fu_1066_p2[0:0] == 1'b1) ? 8'd128 : trunc_ln88_fu_1072_p1);

assign ow_mid2_fu_650_p3 = ((empty_fu_644_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_ow_load);

assign p_ZL20features_3_dw_w_fold_0_0_address0 = zext_ln111_fu_666_p1;

assign p_ZL20features_3_dw_w_fold_0_1_address0 = zext_ln111_reg_1230;

assign p_ZL20features_3_dw_w_fold_0_2_address0 = zext_ln111_reg_1230_pp0_iter1_reg;

assign p_ZL20features_3_dw_w_fold_1_0_address0 = zext_ln111_reg_1230_pp0_iter2_reg;

assign p_ZL20features_3_dw_w_fold_1_1_address0 = zext_ln111_reg_1230_pp0_iter4_reg;

assign p_ZL20features_3_dw_w_fold_1_2_address0 = zext_ln111_reg_1230_pp0_iter3_reg;

assign p_ZL20features_3_dw_w_fold_2_0_address0 = zext_ln111_reg_1230_pp0_iter5_reg;

assign p_ZL20features_3_dw_w_fold_2_1_address0 = zext_ln111_reg_1230_pp0_iter8_reg;

assign p_ZL20features_3_dw_w_fold_2_2_address0 = zext_ln111_reg_1230_pp0_iter6_reg;

assign select_ln111_1_fu_630_p3 = ((icmp_ln112_fu_598_p2[0:0] == 1'b1) ? add_ln111_fu_592_p2 : ap_sig_allocacmp_c_load);

assign select_ln111_fu_604_p3 = ((icmp_ln112_fu_598_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_oh_load);

assign select_ln112_1_fu_790_p3 = ((icmp_ln112_fu_598_p2[0:0] == 1'b1) ? 4'd1 : add_ln112_1_fu_784_p2);

assign select_ln112_fu_658_p3 = ((and_ln111_fu_624_p2[0:0] == 1'b1) ? add_ln112_fu_638_p2 : select_ln111_fu_604_p3);

assign select_ln124_10_fu_1005_p3 = ((icmp_ln124_reg_1294_pp0_iter9_reg[0:0] == 1'b1) ? ifmap_3_2_q0 : ifmap_3_0_q0);

assign select_ln124_11_fu_1012_p3 = ((icmp_ln124_1_reg_1306_pp0_iter9_reg[0:0] == 1'b1) ? select_ln124_10_fu_1005_p3 : select_ln124_reg_1367_pp0_iter9_reg);

assign select_ln124_12_fu_981_p3 = ((icmp_ln124_reg_1294_pp0_iter7_reg[0:0] == 1'b1) ? ifmap_3_3_q0 : ifmap_3_1_load_reg_1531);

assign select_ln124_13_fu_987_p3 = ((icmp_ln124_1_reg_1306_pp0_iter7_reg[0:0] == 1'b1) ? select_ln124_12_fu_981_p3 : select_ln124_1_reg_1403_pp0_iter7_reg);

assign select_ln124_1_fu_854_p3 = ((icmp_ln124_reg_1294_pp0_iter2_reg[0:0] == 1'b1) ? ifmap_1_3_q0 : ifmap_1_1_load_reg_1331_pp0_iter2_reg);

assign select_ln124_2_fu_877_p3 = ((icmp_ln124_1_reg_1306_pp0_iter3_reg[0:0] == 1'b1) ? ifmap_2_1_q0 : ifmap_0_1_q0);

assign select_ln124_3_fu_933_p3 = ((icmp_ln124_reg_1294_pp0_iter5_reg[0:0] == 1'b1) ? ifmap_0_2_q0 : ifmap_0_0_q0);

assign select_ln124_4_fu_940_p3 = ((icmp_ln124_reg_1294_pp0_iter5_reg[0:0] == 1'b1) ? ifmap_2_2_q0 : ifmap_2_0_q0);

assign select_ln124_5_fu_947_p3 = ((icmp_ln124_1_reg_1306_pp0_iter5_reg[0:0] == 1'b1) ? select_ln124_4_fu_940_p3 : select_ln124_3_fu_933_p3);

assign select_ln124_6_fu_897_p3 = ((icmp_ln124_reg_1294_pp0_iter4_reg[0:0] == 1'b1) ? ifmap_0_3_q0 : ifmap_0_1_load_reg_1418);

assign select_ln124_7_fu_903_p3 = ((icmp_ln124_reg_1294_pp0_iter4_reg[0:0] == 1'b1) ? ifmap_2_3_q0 : ifmap_2_1_load_reg_1423);

assign select_ln124_8_fu_909_p3 = ((icmp_ln124_1_reg_1306_pp0_iter4_reg[0:0] == 1'b1) ? select_ln124_7_fu_903_p3 : select_ln124_6_fu_897_p3);

assign select_ln124_9_fu_967_p3 = ((icmp_ln124_1_reg_1306_pp0_iter6_reg[0:0] == 1'b1) ? ifmap_3_1_q0 : ifmap_1_1_load_reg_1331_pp0_iter6_reg);

assign select_ln124_fu_835_p3 = ((icmp_ln124_reg_1294_pp0_iter1_reg[0:0] == 1'b1) ? ifmap_1_2_q0 : ifmap_1_0_q0);

assign sext_ln115_1_fu_929_p1 = acc_6_fu_924_p3;

assign sext_ln115_2_fu_997_p1 = grp_fu_1153_p3;

assign sext_ln115_fu_873_p1 = acc_2_fu_868_p3;

assign sext_ln125_fu_846_p1 = features_3_dw_b_fold_q0;

assign shl_ln120_fu_716_p2 = select_ln112_fu_658_p3 << 2'd1;

assign shl_ln121_fu_742_p2 = ow_mid2_fu_650_p3 << 2'd1;

assign tmp_155_fu_704_p3 = {{add_ln129_fu_698_p2}, {1'd0}};

assign tmp_156_fu_1043_p1 = grp_fu_1179_p4;

assign tmp_156_fu_1043_p4 = {{tmp_156_fu_1043_p1[31:28]}};

assign tmp_157_fu_1088_p3 = out8_fu_1076_p3[32'd7];

assign tmp_fu_686_p3 = {{lshr_ln_fu_676_p4}, {1'd0}};

assign trunc_ln111_fu_672_p1 = select_ln111_1_fu_630_p3[0:0];

assign trunc_ln120_fu_712_p1 = select_ln112_fu_658_p3[0:0];

assign trunc_ln121_fu_738_p1 = ow_mid2_fu_650_p3[0:0];

assign trunc_ln88_5_fu_1084_p1 = out8_fu_1076_p3[6:0];

assign trunc_ln88_fu_1072_p1 = out32_5_fu_1058_p3[7:0];

assign xor_ln111_fu_612_p2 = (icmp_ln112_fu_598_p2 ^ 1'd1);

assign zext_ln111_fu_666_p1 = select_ln111_1_fu_630_p3;

assign zext_ln129_1_fu_728_p1 = ow_mid2_fu_650_p3;

assign zext_ln129_2_fu_1104_p1 = add_ln129_1_reg_1278_pp0_iter14_reg;

assign zext_ln129_fu_694_p1 = select_ln112_fu_658_p3;

always @ (posedge ap_clk) begin
    zext_ln111_reg_1230[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter2_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter3_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter4_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter5_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter6_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter7_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln111_reg_1230_pp0_iter8_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //mobilenet_v1_qat_dw3_qat
