-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mobilenet_v1_fc_Pipeline_FC_IC is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    arrayidx19_9_promoted21_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_8_promoted19_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_7_promoted17_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_6_promoted15_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_5_promoted13_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_4_promoted11_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_3_promoted9_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_2_promoted7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_1_promoted5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    arrayidx19_promoted3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
    ifmap_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ifmap_ce0 : OUT STD_LOGIC;
    ifmap_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    add_917_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_917_out_ap_vld : OUT STD_LOGIC;
    add_816_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_816_out_ap_vld : OUT STD_LOGIC;
    add_715_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_715_out_ap_vld : OUT STD_LOGIC;
    add_614_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_614_out_ap_vld : OUT STD_LOGIC;
    add_513_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_513_out_ap_vld : OUT STD_LOGIC;
    add_412_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_412_out_ap_vld : OUT STD_LOGIC;
    add_311_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_311_out_ap_vld : OUT STD_LOGIC;
    add_210_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_210_out_ap_vld : OUT STD_LOGIC;
    add_19_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add_19_out_ap_vld : OUT STD_LOGIC;
    add8_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    add8_out_ap_vld : OUT STD_LOGIC;
    grp_fu_452_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_452_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_452_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_452_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_452_p_ce : OUT STD_LOGIC;
    grp_fu_456_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_456_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_456_p_opcode : OUT STD_LOGIC_VECTOR (1 downto 0);
    grp_fu_456_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_456_p_ce : OUT STD_LOGIC;
    grp_fu_460_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_460_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_460_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_460_p_ce : OUT STD_LOGIC;
    grp_fu_464_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_464_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_464_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_464_p_ce : OUT STD_LOGIC );
end;


architecture behav of mobilenet_v1_fc_Pipeline_FC_IC is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln17_reg_740 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage5 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZL9fc_weight_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_4_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_5_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_6_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_7_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_8_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_8_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_9_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_ZL9fc_weight_9_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_425 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal reg_429 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln17_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln17_reg_740_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ifmap_load_reg_799 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_0_load_reg_805 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_1_load_reg_810 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_2_load_reg_815 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_3_load_reg_820 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_4_load_reg_825 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_5_load_reg_830 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_6_load_reg_835 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_7_load_reg_840 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_8_load_reg_845 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_ZL9fc_weight_9_load_reg_850 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_reg_855 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_1_reg_860 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_2_reg_875 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_3_reg_880 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_4_reg_895 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_5_reg_900 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_6_reg_915 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_7_reg_920 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal mul_8_reg_935 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_9_reg_940 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal zext_ln17_fu_503_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add8_fu_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter1_stage3 : STD_LOGIC;
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal add_19_fu_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_210_fu_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal add_311_fu_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_412_fu_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal add_513_fu_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_614_fu_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_715_fu_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal add_816_fu_124 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal add_917_fu_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ic_fu_132 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln17_fu_497_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_ic_1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage3_01001 : BOOLEAN;
    signal ifmap_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_0_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_1_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_2_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_3_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_4_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_5_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_6_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_7_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_8_ce0_local : STD_LOGIC;
    signal p_ZL9fc_weight_9_ce0_local : STD_LOGIC;
    signal grp_fu_409_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_409_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_413_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_413_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_417_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal grp_fu_421_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_block_pp0_stage0_00001 : BOOLEAN;
    signal ap_block_pp0_stage1_00001 : BOOLEAN;
    signal ap_block_pp0_stage2_00001 : BOOLEAN;
    signal ap_block_pp0_stage3_00001 : BOOLEAN;
    signal ap_block_pp0_stage4_00001 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component mobilenet_v1_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_5_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_6_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_7_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_8_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_9_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mobilenet_v1_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p_ZL9fc_weight_0_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_0_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_0_address0,
        ce0 => p_ZL9fc_weight_0_ce0_local,
        q0 => p_ZL9fc_weight_0_q0);

    p_ZL9fc_weight_1_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_1_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_1_address0,
        ce0 => p_ZL9fc_weight_1_ce0_local,
        q0 => p_ZL9fc_weight_1_q0);

    p_ZL9fc_weight_2_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_2_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_2_address0,
        ce0 => p_ZL9fc_weight_2_ce0_local,
        q0 => p_ZL9fc_weight_2_q0);

    p_ZL9fc_weight_3_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_3_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_3_address0,
        ce0 => p_ZL9fc_weight_3_ce0_local,
        q0 => p_ZL9fc_weight_3_q0);

    p_ZL9fc_weight_4_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_4_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_4_address0,
        ce0 => p_ZL9fc_weight_4_ce0_local,
        q0 => p_ZL9fc_weight_4_q0);

    p_ZL9fc_weight_5_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_5_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_5_address0,
        ce0 => p_ZL9fc_weight_5_ce0_local,
        q0 => p_ZL9fc_weight_5_q0);

    p_ZL9fc_weight_6_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_6_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_6_address0,
        ce0 => p_ZL9fc_weight_6_ce0_local,
        q0 => p_ZL9fc_weight_6_q0);

    p_ZL9fc_weight_7_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_7_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_7_address0,
        ce0 => p_ZL9fc_weight_7_ce0_local,
        q0 => p_ZL9fc_weight_7_q0);

    p_ZL9fc_weight_8_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_8_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_8_address0,
        ce0 => p_ZL9fc_weight_8_ce0_local,
        q0 => p_ZL9fc_weight_8_q0);

    p_ZL9fc_weight_9_U : component mobilenet_v1_fc_Pipeline_FC_IC_p_ZL9fc_weight_9_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL9fc_weight_9_address0,
        ce0 => p_ZL9fc_weight_9_ce0_local,
        q0 => p_ZL9fc_weight_9_q0);

    flow_control_loop_pipe_sequential_init_U : component mobilenet_v1_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage5,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage5)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    add8_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add8_fu_92 <= arrayidx19_promoted3_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                add8_fu_92 <= reg_425;
            end if; 
        end if;
    end process;

    add_19_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_19_fu_96 <= arrayidx19_1_promoted5_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                add_19_fu_96 <= reg_429;
            end if; 
        end if;
    end process;

    add_210_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    add_210_fu_100 <= arrayidx19_2_promoted7_reload;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    add_210_fu_100 <= reg_425;
                end if;
            end if; 
        end if;
    end process;

    add_311_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    add_311_fu_104 <= arrayidx19_3_promoted9_reload;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    add_311_fu_104 <= reg_429;
                end if;
            end if; 
        end if;
    end process;

    add_412_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_412_fu_108 <= arrayidx19_4_promoted11_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                add_412_fu_108 <= reg_425;
            end if; 
        end if;
    end process;

    add_513_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_513_fu_112 <= arrayidx19_5_promoted13_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                add_513_fu_112 <= reg_429;
            end if; 
        end if;
    end process;

    add_614_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_614_fu_116 <= arrayidx19_6_promoted15_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                add_614_fu_116 <= reg_425;
            end if; 
        end if;
    end process;

    add_715_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_715_fu_120 <= arrayidx19_7_promoted17_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                add_715_fu_120 <= reg_429;
            end if; 
        end if;
    end process;

    add_816_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_816_fu_124 <= arrayidx19_8_promoted19_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                add_816_fu_124 <= reg_425;
            end if; 
        end if;
    end process;

    add_917_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                add_917_fu_128 <= arrayidx19_9_promoted21_reload;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                add_917_fu_128 <= reg_429;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage3))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ic_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln17_fu_491_p2 = ap_const_lv1_0))) then 
                    ic_fu_132 <= add_ln17_fu_497_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ic_fu_132 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln17_reg_740 <= icmp_ln17_fu_491_p2;
                icmp_ln17_reg_740_pp0_iter1_reg <= icmp_ln17_reg_740;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                ifmap_load_reg_799 <= ifmap_q0;
                p_ZL9fc_weight_0_load_reg_805 <= p_ZL9fc_weight_0_q0;
                p_ZL9fc_weight_1_load_reg_810 <= p_ZL9fc_weight_1_q0;
                p_ZL9fc_weight_2_load_reg_815 <= p_ZL9fc_weight_2_q0;
                p_ZL9fc_weight_3_load_reg_820 <= p_ZL9fc_weight_3_q0;
                p_ZL9fc_weight_4_load_reg_825 <= p_ZL9fc_weight_4_q0;
                p_ZL9fc_weight_5_load_reg_830 <= p_ZL9fc_weight_5_q0;
                p_ZL9fc_weight_6_load_reg_835 <= p_ZL9fc_weight_6_q0;
                p_ZL9fc_weight_7_load_reg_840 <= p_ZL9fc_weight_7_q0;
                p_ZL9fc_weight_8_load_reg_845 <= p_ZL9fc_weight_8_q0;
                p_ZL9fc_weight_9_load_reg_850 <= p_ZL9fc_weight_9_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                mul_1_reg_860 <= grp_fu_464_p_dout0;
                mul_reg_855 <= grp_fu_460_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                mul_2_reg_875 <= grp_fu_460_p_dout0;
                mul_3_reg_880 <= grp_fu_464_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                mul_4_reg_895 <= grp_fu_460_p_dout0;
                mul_5_reg_900 <= grp_fu_464_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                mul_6_reg_915 <= grp_fu_460_p_dout0;
                mul_7_reg_920 <= grp_fu_464_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                mul_8_reg_935 <= grp_fu_460_p_dout0;
                mul_9_reg_940 <= grp_fu_464_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)))) then
                reg_425 <= grp_fu_452_p_dout0;
                reg_429 <= grp_fu_456_p_dout0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage5_subdone, ap_block_pp0_stage3_subdone, ap_condition_exit_pp0_iter1_stage3, ap_idle_pp0_0to0, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage4_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_idle_pp0 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if (((ap_idle_pp0_0to0 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage3))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add8_out <= add8_fu_92;

    add8_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add8_out_ap_vld <= ap_const_logic_1;
        else 
            add8_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_19_out <= add_19_fu_96;

    add_19_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_19_out_ap_vld <= ap_const_logic_1;
        else 
            add_19_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_210_out <= add_210_fu_100;

    add_210_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_210_out_ap_vld <= ap_const_logic_1;
        else 
            add_210_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_311_out <= add_311_fu_104;

    add_311_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_311_out_ap_vld <= ap_const_logic_1;
        else 
            add_311_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_412_out <= add_412_fu_108;

    add_412_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_412_out_ap_vld <= ap_const_logic_1;
        else 
            add_412_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_513_out <= add_513_fu_112;

    add_513_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_513_out_ap_vld <= ap_const_logic_1;
        else 
            add_513_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_614_out <= add_614_fu_116;

    add_614_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_614_out_ap_vld <= ap_const_logic_1;
        else 
            add_614_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_715_out <= add_715_fu_120;

    add_715_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_715_out_ap_vld <= ap_const_logic_1;
        else 
            add_715_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_816_out <= add_816_fu_124;

    add_816_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_816_out_ap_vld <= ap_const_logic_1;
        else 
            add_816_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_917_out <= add_917_fu_128;

    add_917_out_ap_vld_assign_proc : process(icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            add_917_out_ap_vld <= ap_const_logic_1;
        else 
            add_917_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln17_fu_497_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ic_1) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_00001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage5_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln17_reg_740)
    begin
        if (((icmp_ln17_reg_740 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            ap_condition_exit_pp0_iter0_stage5 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage3_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln17_reg_740_pp0_iter1_reg, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln17_reg_740_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_condition_exit_pp0_iter1_stage3 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage3 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage3_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage5;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ic_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ic_fu_132)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_ic_1 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_ic_1 <= ic_fu_132;
        end if; 
    end process;


    grp_fu_409_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0, add8_fu_92, ap_block_pp0_stage3, add_210_fu_100, ap_block_pp0_stage1, add_412_fu_108, ap_block_pp0_stage2, add_614_fu_116, add_816_fu_124, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                grp_fu_409_p0 <= add_816_fu_124;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                grp_fu_409_p0 <= add_614_fu_116;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_409_p0 <= add_412_fu_108;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_409_p0 <= add_210_fu_100;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_409_p0 <= add8_fu_92;
            else 
                grp_fu_409_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_409_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_409_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, mul_reg_855, mul_2_reg_875, mul_4_reg_895, mul_6_reg_915, ap_CS_fsm_pp0_stage3, mul_8_reg_935, ap_block_pp0_stage0, ap_block_pp0_stage3, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                grp_fu_409_p1 <= mul_8_reg_935;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                grp_fu_409_p1 <= mul_6_reg_915;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_409_p1 <= mul_4_reg_895;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_409_p1 <= mul_2_reg_875;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_409_p1 <= mul_reg_855;
            else 
                grp_fu_409_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_409_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_413_p0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0, ap_block_pp0_stage3, add_19_fu_96, ap_block_pp0_stage1, add_311_fu_104, ap_block_pp0_stage2, add_513_fu_112, add_715_fu_120, ap_block_pp0_stage4, add_917_fu_128)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                grp_fu_413_p0 <= add_917_fu_128;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                grp_fu_413_p0 <= add_715_fu_120;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_413_p0 <= add_513_fu_112;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_413_p0 <= add_311_fu_104;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_413_p0 <= add_19_fu_96;
            else 
                grp_fu_413_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_413_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_413_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, mul_1_reg_860, mul_3_reg_880, mul_5_reg_900, mul_7_reg_920, ap_CS_fsm_pp0_stage3, mul_9_reg_940, ap_block_pp0_stage0, ap_block_pp0_stage3, ap_block_pp0_stage1, ap_block_pp0_stage2, ap_block_pp0_stage4)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                grp_fu_413_p1 <= mul_9_reg_940;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                grp_fu_413_p1 <= mul_7_reg_920;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                grp_fu_413_p1 <= mul_5_reg_900;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                grp_fu_413_p1 <= mul_3_reg_880;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                grp_fu_413_p1 <= mul_1_reg_860;
            else 
                grp_fu_413_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            grp_fu_413_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_417_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage5, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, p_ZL9fc_weight_0_load_reg_805, p_ZL9fc_weight_2_load_reg_815, p_ZL9fc_weight_4_load_reg_825, p_ZL9fc_weight_6_load_reg_835, p_ZL9fc_weight_8_load_reg_845, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0, ap_block_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage4, ap_block_pp0_stage5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_417_p1 <= p_ZL9fc_weight_8_load_reg_845;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            grp_fu_417_p1 <= p_ZL9fc_weight_6_load_reg_835;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            grp_fu_417_p1 <= p_ZL9fc_weight_4_load_reg_825;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_417_p1 <= p_ZL9fc_weight_2_load_reg_815;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_417_p1 <= p_ZL9fc_weight_0_load_reg_805;
        else 
            grp_fu_417_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_421_p1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage5, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage2, p_ZL9fc_weight_1_load_reg_810, p_ZL9fc_weight_3_load_reg_820, p_ZL9fc_weight_5_load_reg_830, p_ZL9fc_weight_7_load_reg_840, p_ZL9fc_weight_9_load_reg_850, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage0, ap_block_pp0_stage3, ap_block_pp0_stage2, ap_block_pp0_stage4, ap_block_pp0_stage5)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_421_p1 <= p_ZL9fc_weight_9_load_reg_850;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            grp_fu_421_p1 <= p_ZL9fc_weight_7_load_reg_840;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            grp_fu_421_p1 <= p_ZL9fc_weight_5_load_reg_830;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            grp_fu_421_p1 <= p_ZL9fc_weight_3_load_reg_820;
        elsif (((ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            grp_fu_421_p1 <= p_ZL9fc_weight_1_load_reg_810;
        else 
            grp_fu_421_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_fu_452_p_ce <= ap_const_logic_1;
    grp_fu_452_p_din0 <= grp_fu_409_p0;
    grp_fu_452_p_din1 <= grp_fu_409_p1;
    grp_fu_452_p_opcode <= ap_const_lv2_0;
    grp_fu_456_p_ce <= ap_const_logic_1;
    grp_fu_456_p_din0 <= grp_fu_413_p0;
    grp_fu_456_p_din1 <= grp_fu_413_p1;
    grp_fu_456_p_opcode <= ap_const_lv2_0;
    grp_fu_460_p_ce <= ap_const_logic_1;
    grp_fu_460_p_din0 <= ifmap_load_reg_799;
    grp_fu_460_p_din1 <= grp_fu_417_p1;
    grp_fu_464_p_ce <= ap_const_logic_1;
    grp_fu_464_p_din0 <= ifmap_load_reg_799;
    grp_fu_464_p_din1 <= grp_fu_421_p1;
    icmp_ln17_fu_491_p2 <= "1" when (ap_sig_allocacmp_ic_1 = ap_const_lv9_100) else "0";
    ifmap_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);
    ifmap_ce0 <= ifmap_ce0_local;

    ifmap_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ifmap_ce0_local <= ap_const_logic_1;
        else 
            ifmap_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_0_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_1_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_2_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_3_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_4_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_4_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_5_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_5_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_6_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_6_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_7_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_7_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_8_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_8_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL9fc_weight_9_address0 <= zext_ln17_fu_503_p1(8 - 1 downto 0);

    p_ZL9fc_weight_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL9fc_weight_9_ce0_local <= ap_const_logic_1;
        else 
            p_ZL9fc_weight_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln17_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_ic_1),64));
end behav;
