-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_conv0_p_ZL13conv_0_weight_0_0_2_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);
 
          address1        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce1             : in std_logic; 
          q1              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_conv0_p_ZL13conv_0_weight_0_0_2_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0);  
signal address1_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111101100011110100010111010001", 1 => "00111101011010000001101000101011", 2 => "00111101100110000111011011001100", 3 => "00111110000000011001001010011000", 
    4 => "10111110000011100011010111100101", 5 => "10111011110011100101101010000001", 6 => "00111110110100110010010011000000", 7 => "10111110000111011010110110101000", 
    8 => "00111110100000010000111011011010", 9 => "00111101110100001111100010000110", 10 => "10111110001000011001100001111011", 11 => "10111110001110100111101110001110", 
    12 => "00111110010100111110101110100110", 13 => "00111101000001111111010101010111", 14 => "00111110111000110000011100110011", 15 => "00111110101100111101111101011101", 
    16 => "10111101101011101110001110011111", 17 => "10111101111100111110001101101000", 18 => "10111110101100011010111010010110", 19 => "00111110100101110011010111011110", 
    20 => "00111110110111001111001111001100", 21 => "10111110000111111000110000000011", 22 => "10111110101100100110100100001110", 23 => "10111111000100100111111001110001", 
    24 => "00111101010001110101000110000000", 25 => "00111101001100010101111001011100", 26 => "10111110001101111010010101011000", 27 => "00111110100011101000111000110011", 
    28 => "10111100000011110011101001100101", 29 => "00111011111101010011001010011101", 30 => "10111101111100010001101010101011", 31 => "00111111000100001110001111111011");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;
 
memory_access_guard_1: process (address1) 
begin
      address1_tmp <= address1;
--synthesis translate_off
      if (CONV_INTEGER(address1) > AddressRange-1) then
           address1_tmp <= (others => '0');
      else 
           address1_tmp <= address1;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;
 
        if (ce1 = '1') then  
            q1 <= mem0(CONV_INTEGER(address1_tmp)); 
        end if;

end if;
end process;

end rtl;

