-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_1_1_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_1_1_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111111000000101001000111011010", 1 => "00111111000110001101010011110010", 2 => "00111110000001000110100111010101", 3 => "00111110101101010001101100110011", 
    4 => "10111110101010011011111100001110", 5 => "00111110111110001101100110001101", 6 => "00111111001010110000100110001101", 7 => "10111111000001000001111100111001", 
    8 => "10111100010011010110000010010001", 9 => "00111101101001011100001011100001", 10 => "00111111001010010110110000110110", 11 => "00111110100010110110100001101010", 
    12 => "10111111000011101111110011100011", 13 => "10111111000000100101100111000111", 14 => "00111100111011111001010000110010", 15 => "00111101101110110110001011101000", 
    16 => "00111110111110001111111010001001", 17 => "10111111000110001010010010100000", 18 => "00111111000000100001010101111011", 19 => "00111110010110001011001010000111", 
    20 => "00111110111001100000010111011000", 21 => "00111101100110001011010011010110", 22 => "10111111000001010100110100000001", 23 => "00111111000001111111000010100010", 
    24 => "00111111000001000010011110100000", 25 => "10111111000000000011111100111100", 26 => "00111101000011110001110010000000", 27 => "00111111000100010011101000111010", 
    28 => "00111110111111111010111101010010", 29 => "00111111001000000001011101110011", 30 => "00111111000110110001100110010001", 31 => "10111111000000000001011100001111");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

