-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_1_0_ROM_2P_BRAM_1R is 
    generic(
             DataWidth     : integer := 32; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of mobilenet_v1_dw1_p_ZL26features_1_deepwise_weight_1_0_ROM_2P_BRAM_1R is 
attribute DowngradeIPIdentifiedWarnings : string;
attribute DowngradeIPIdentifiedWarnings of rtl: architecture is "yes";
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "00111110100110011110110100111001", 1 => "00111110101010000001000100000101", 2 => "00111110010100111100000011000010", 3 => "10111101100001111111110101110110", 
    4 => "00111110011100100111111101001000", 5 => "10111001010011000100110111110111", 6 => "00111110111001000000101111001100", 7 => "10111110101101010011111001011000", 
    8 => "00111110110111110101011110000000", 9 => "10111111000000011100111011011001", 10 => "00111110101110011100001001010100", 11 => "00111110100011000101110001101010", 
    12 => "10111111000000110001010011100110", 13 => "10111110111110110100010001010010", 14 => "10111110111101001101001001101110", 15 => "00111101011100111101000111000111", 
    16 => "00111110001011101011010111011010", 17 => "10111110110000111010000001101001", 18 => "00111110111000011110111110110000", 19 => "00111110011100010010001111100010", 
    20 => "00111110110001010110101101010100", 21 => "00111110110100010001001010101101", 22 => "00111111000000110110011100110100", 23 => "00111110011111100101011010010110", 
    24 => "00111110110011010111010100100011", 25 => "10111101110000000001111111011110", 26 => "00111110101101001000100111110110", 27 => "00111110000010100111010101010011", 
    28 => "00111110110011001100101101001010", 29 => "00111110101111111010111001101011", 30 => "00111110110110111110001110111100", 31 => "10111110110001011111001001000101");



attribute syn_rom_style : string;

attribute syn_rom_style of mem0 : signal is "block"; 
attribute ROM_STYLE : string;

attribute ROM_STYLE of mem0 : signal is "block";

begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

