[hls]
relative_roots=/home/nhanenten/Desktop/HK6/Project-1/MobileNet-V1/FP32_HLS
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=fc/FC_BIAS 
syn.directive.pipeline=fc/FC_OUTPUT 
syn.directive.pipeline=mobilenet_v1/GAP_C 
# Inferred from performance & pipeline pragmas/directives
syn.directive.array_partition=mobilenet_v1/ofmap_conv0 dim=3 type=complete variable=ofmap_conv0
syn.directive.loop_flatten=batchnorm_conv0/BN_CONV0_C  
syn.directive.loop_flatten=mobilenet_v1/BN_DW0_H  
syn.directive.loop_flatten=mobilenet_v1/BN_DW0_C  
syn.directive.array_partition=mobilenet_v1/ofmap_pw0 dim=3 type=complete variable=ofmap_pw0
syn.directive.array_partition=mobilenet_v1/ifmap_dw1 dim=3 type=complete variable=ifmap_dw1
syn.directive.loop_flatten=batchnorm_pw0/BN_PW0_C  
syn.directive.array_partition=mobilenet_v1/ofmap_dw1 dim=3 type=complete variable=ofmap_dw1
syn.directive.array_partition=mobilenet_v1/ifmap_pw1_0 dim=3 type=complete variable=ifmap_pw1_0
syn.directive.loop_flatten=mobilenet_v1/BN_DW1_C  
syn.directive.array_partition=mobilenet_v1/ofmap_pw1 dim=3 type=complete variable=ofmap_pw1
syn.directive.loop_flatten=mobilenet_v1/BN_PW1_C  
syn.directive.array_partition=mobilenet_v1/ofmap_dw2 dim=3 type=complete variable=ofmap_dw2
syn.directive.array_partition=mobilenet_v1/ifmap_pw2_0 dim=3 type=complete variable=ifmap_pw2_0
syn.directive.loop_flatten=mobilenet_v1/BN_DW2_C  
syn.directive.array_partition=mobilenet_v1/ofmap_pw2 dim=3 type=complete variable=ofmap_pw2
syn.directive.array_partition=mobilenet_v1/ifmap_dw3 dim=3 type=complete variable=ifmap_dw3
syn.directive.loop_flatten=mobilenet_v1/BN_PW2_C  
syn.directive.array_partition=mobilenet_v1/ifmap_pw3_0 dim=3 type=complete variable=ifmap_pw3_0
syn.directive.loop_flatten=mobilenet_v1/BN_DW3_C  
syn.directive.loop_flatten=mobilenet_v1/BN_PW3_C  
syn.directive.array_partition=mobilenet_v1/in_buf_0 dim=3 type=cyclic factor=3 variable=in_buf_0
syn.directive.loop_flatten=conv0/CONV0_OH  
syn.directive.loop_flatten=conv0/CONV0_OC  
syn.directive.array_partition=mobilenet_v1/ifmap_dw0 dim=3 type=complete variable=ifmap_dw0
syn.directive.loop_flatten=dw0/DW0_OH  
syn.directive.loop_flatten=dw0/DW0_C  
syn.directive.loop_flatten=dw1/DW1_OH  
syn.directive.loop_flatten=dw1/DW1_C  
syn.directive.array_partition=mobilenet_v1/ifmap_dw2 dim=3 type=complete variable=ifmap_dw2
syn.directive.loop_flatten=dw2/DW2_OH  
syn.directive.loop_flatten=dw2/DW2_C  
syn.directive.loop_flatten=dw3/DW3_OH  
syn.directive.loop_flatten=dw3/DW3_C  
syn.directive.loop_flatten=pw0/PW0_OH  
syn.directive.loop_flatten=pw0/PW0_OC  
syn.directive.loop_flatten=pw1/PW1_OH  
syn.directive.loop_flatten=pw1/PW1_OC  
syn.directive.loop_flatten=pw2/PW2_OH  
syn.directive.loop_flatten=pw2/PW2_OC  
syn.directive.loop_flatten=pw3/PW3_OH  
syn.directive.loop_flatten=pw3/PW3_OC  
syn.directive.loop_flatten=mobilenet_v1/LOAD_INH  
syn.directive.loop_flatten=mobilenet_v1/LOAD_INC  


